### ISSUE TITLE
Voltage devider in wiring section

### ISSUE THREAD

**Issue by WyvernDex** [luc-github/ESP3D#103]
Hi,
the voltage devider (1k and 2k in the rx line) caused connection problems in my setup.
Why do you inserted them?
In case of the Davinci, the UART works with 3.3V, so no voltage adaption is needed.

**Comment by luc-github** [comment]
Hi electronic is not my area - so it may be not optimized I agree - I used the wiring long time ago from here : http://www.martyncurrey.com/arduino-to-esp8266-serial-commincation/

It works on my davinci 2.0 and my RADDS/DUE as well as my FTDI (3.3), before i use it I had random exception and no more after - so I concluded it was Ok.

**Comment by WyvernDex** [comment]
At the page you posted are the both resistors correct, because the arduino is a 5V device and could destroy the 3.3V esp module.

In this case leaving them out would improve stbility.

**Comment by luc-github** [comment]
but on picture is connected to 3.3v, as said I never got issue so never think about this since

**Comment by luc-github** [comment]
May I know what kind of issue you meet ? your board is which model ?

**Comment by luc-github** [comment]
If no update I close issue
