### ISSUE TITLE
Add Netbios support feature

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#109]
as now it is available in esp core git : https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266NetBIOS

**Comment by luc-github** [comment]
But need git version of ESP Core

**Comment by Pablo2048** [comment]
So until the next version of Core is released You can use my original library from http://www.xpablo.cz/?p=751 ...

**Comment by luc-github** [comment]
Thank you  - do you plan to do an english version of your pages ? would be easier to spread it

**Comment by Pablo2048** [comment]
Unfortunately i'm not good in english so probably not :-( . But at least i can translate my comments inside the library into english ones...

**Comment by luc-github** [comment]
May be not all articles but - you will gain a lot at least for your library and other any code you do - just my 2 cents

great job anyway - thanks for sharing you work

**Comment by Pablo2048** [comment]
Thank You. Maybe after a lot of learning I can try... :-)

**Comment by luc-github** [comment]
This present in core 2.4 and git version so I can close issue
