### ISSUE TITLE
Where is the license of this project ?

### ISSUE THREAD

**Issue by patrickelectric** [luc-github/ESP3D#123]

**Comment by luc-github** [comment]
in files list : https://github.com/luc-github/ESP3D/blob/master/gpl.txt
in each header of files : https://github.com/luc-github/ESP3D/blob/master/esp3d/esp3d.ino#L1-L25
in each web page footer : https://github.com/luc-github/ESP3D/blob/master/esp3d/data/footer.inc#L4

**Comment by luc-github** [comment]
If no update I close topic
