### ISSUE TITLE
error opening : /home.tpl

### ISSUE THREAD

**Issue by ekaggrat** [luc-github/ESP3D#125]
hi i am getting this error on connecting to the esp via wifi in access point mode. where am i making a mistake to upload the firmware?

**Comment by luc-github** [comment]
did you uploaded the tpl files after uploading FW ?

**Comment by ekaggrat** [comment]
okay i cont find the instructions at first so i this issue.. not i am able to login fine .. soon i will test it on ,y printer. thanks

**Comment by luc-github** [comment]
Ok I close issue then
