### ISSUE TITLE
Connection not possible to SSID with space character

### ISSUE THREAD

**Issue by szepnorbee** [luc-github/ESP3D#126]
Hi! I cant connect to my SSID with "HUN Wlan" network name. I selected this from the list and i typed the password also. I get always "No SSID found" error message. Why? Space char in the SSID not allowed?

**Comment by luc-github** [comment]
I did because of this : https://github.com/esp8266/Arduino/issues/1342

you can remove this part to see if you experience issue https://github.com/luc-github/ESP3D/blob/master/esp3d/config.cpp#L73-L75 - I did not checked as issue is still open

**Comment by szepnorbee** [comment]
Thanks! It works after removed this part of code. (Core 2.3.0.0 ;Arduino 1.6.8)

**Comment by luc-github** [comment]
Thanks for the feedback - so I guess I can remove the limitation now - allowing space for SSID should not be a problem for ESP commands but will check

**Comment by luc-github** [comment]
I have removed the check - thank you
https://github.com/luc-github/ESP3D/commit/ec90a27e7e666d3dfe3129783c5fe4b21d45ed56
