### ISSUE TITLE
New pipe to catch command bug with Repetier

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#130]
Repetier send continuously "wait" when idle so serial purge cannot work - need to find a workaround
So when send a command from web ui it goes to dead loop

**Comment by openhardwarecoza** [comment]
You can disable the echo wait from configuration.h -  in fact that is the
recommended configuration

**Comment by luc-github** [comment]
Yes but I would like to avoid people to trick their printer FW for ESP ^_^ - hopefully I have already the solution on test now - just fine tune some flag

**Comment by luc-github** [comment]
Fixed by https://github.com/luc-github/ESP3D/commit/3dae051e0c6cb990fab525ae60747f5e2458f670

![image](https://cloud.githubusercontent.com/assets/8822552/20219449/c0486ad2-a829-11e6-938d-7166f072b7dd.png)
