### ISSUE TITLE
SD upload using M28/29 seems broken

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#134]
I guess it is linked to latest update as now SD upload failed - the file is created but it is empty

**Comment by luc-github** [comment]
Seems actually ok on Smoothie and failed on repetier

**Comment by luc-github** [comment]
orz... I have tried to upload file which is not GCODE file so of course it failed when doing the content check....
M28/M29 check content unlike direct file upload

**Comment by denmorru** [comment]
There is issue with file delete M30 command (from BIN button): it does not seem to work at all in web interface of current version. It makes confirmation popup dialog, and nothing else (the same about "Print" button).
Tested Marlin/RAMPS. In case I send from "Command" form proper GCODE, it does deletion well.

**Comment by luc-github** [comment]
@denmorru this is not related to this closed issue which you can see it is invalid actually 

please open a new issue describing :
1 - which FW version you are using - 
2 - which ESP coreversion you are using 
3 - which UI you are using  
4 - which arduino ide version you are using 

this will help to keep one ticket for one issue

Thank you
