### ISSUE TITLE
'class HardwareSerial' has no member named 'setRxBufferSize' in Windows 7

### ISSUE THREAD

**Issue by khseal** [luc-github/ESP3D#137]
Software versions
Windows 7 Arduino 1.6.9 ESP core 2.3.0
Tried different versions.
In Ubuntu all ok.

**Comment by khseal** [comment]
In Ubuntu all ok.

**Comment by khseal** [comment]
Strangely clone git arduino.esp8266.com all ok.
Used http://arduino.esp8266.com/stable/package_esp8266com_index.json no work...

**Comment by luc-github** [comment]
setRxBufferSize is only available on esp core  git is not part of release yet, if you use my latest git version and not the release you must use latest git version of ESP core also.

NetBios support is also currently only available on git but not on stable, speed on git is 2x the speed of stable
