### ISSUE TITLE
Add support Relay in Sonoff

### ISSUE THREAD

**Issue by khseal** [luc-github/ESP3D#138]
That device https://www.itead.cc/wiki/Sonoff
You can add a relay control via a web interface? 
Use the relay can be switched on and off remotely 3D printer.
Relay connected GPIO12.

**Comment by luc-github** [comment]
git version has already direct pin access :
```
*Get/Set pin value
[ESP201]P<pin> V<value> [PULLUP=YES RAW=YES]
if no V<value> get P<pin> value
if V<value> 0/1 set INPUT_PULLUP value, but for GPIO16 INPUT_PULLDOWN_16
GPIO1 and GPIO3 cannot be used as they are used for serial
if PULLUP=YES set input pull up, if not set input
if RAW=YES do not set pinmode just read value
```
about modifying UI it is up to you according which one you are using,
if you use my sample UI there is a Javascript command for this that you can embedded in button or image:
`Sendcommand('[ESP201]P12 V0');` and `Sendcommand('[ESP201]P12 V1');`
you may also add a read command to handle a toggle state

I hope it answer your question

**Comment by khseal** [comment]
Nice, thanks for information!

**Comment by luc-github** [comment]
I just ordered this module to have a look - seems already have a fw on it - how did you flahed it ?

**Comment by khseal** [comment]
Quite simply, that's pinout
![image](https://cloud.githubusercontent.com/assets/11374629/20825887/4367891c-b878-11e6-980b-15d26c071b2d.png)
To flash the need to hold the button when turned on.
There is a detailed description of
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/wiki/Compile-and-Upload

**Comment by luc-github** [comment]
I see, thanks for sharing

**Comment by khseal** [comment]
Only I have one problem. When connected to a 3D printer  Ramps 1.4 + Marlin 1.1.0-RC7. Arduino is not always start when connected to ESP. Disconnects Rx input Arduino. Arduino runs without problems.

**Comment by luc-github** [comment]
what esp board do you use ? what setting do you have ? be sure debug is disabled

**Comment by khseal** [comment]
Debugging disabled. I use this device Sonoff.
Almost all settings by default. Wi-fi in client mode.
I chose #define FIRMWARE_TARGET MARLIN
I think that the problem is in the order of start microcontrollers. I'll try to  individually supply power the ESP board.

**Comment by luc-github** [comment]
My esp are connected to board due with repetier and smoothieboards AZMSZ / Azteeg 5 with smoothieware and no issue, I did not try marlin / mega ramps since a while.
is you arduino/ramps powered by PC or by external power when you test ?

Issue can be too much current drawn a boot or garbage coming from esp boot loader that do some glitch on start in that case just comment the serial.begin(xxxx); in marlin FW for test should confirm the problem

**Comment by khseal** [comment]
One power supply for Arduino and ESP. I tried to connect to a PC and take power from him. Nothing changed. The first start everything is OK, after second boot the Arduino freezes at startup.

I'll try to use the power source of ESP. 
I did buttons for relay control. Everything is working
![image](https://cloud.githubusercontent.com/assets/11374629/20827219/83233d04-b881-11e6-9b34-d33dfca4a230.png)

**Comment by khseal** [comment]
Everything is fine. Remote power control work. 
Sonoff powered from its  internal power source, Arduino is now always run. 
Simultaneous power on Arduino and ESP resulted to a problem startup Arduino.
If ESP is enabled before Arduino, then all is well.
I recommend Sonoff for 3d printer =)

**Comment by luc-github** [comment]
good news ^_^

thanks for sharing

**Comment by luc-github** [comment]
I see there is a connector for DTH11 do you use it ?

**Comment by khseal** [comment]
There is a free gpio on the board. Depending on revision of the PCB.
I do not connect DTH11. I have another device with the measurement environment parameters.

**Comment by luc-github** [comment]
so actually you just connect gnd / rx /tx from ESP to Arduino and it is ok - right ?
vcc is not necessary as self powered as you say

**Comment by khseal** [comment]
Yes that's right. I used a resistor divider  for input Rx ESP. Arduino has a logic voltage is 5V.

**Comment by luc-github** [comment]
Thanks - I think would be nice to have a wiki page (https://github.com/luc-github/ESP3D/wiki) for this setup - feel free to contribute 
I will see when I get the module

**Comment by luc-github** [comment]
Got some module but no idea when will have time to work on them

**Comment by luc-github** [comment]
I have created the page in wiki which very basic information but it is a start -  can be completed later 
https://github.com/luc-github/ESP3D/wiki/Sonoff

Thank you
