### ISSUE TITLE
Status and Information empty.

### ISSUE THREAD

**Issue by khseal** [luc-github/ESP3D#139]
This is normal and that the status information is constantly empty?
 Marlin Firmware

**Comment by luc-github** [comment]
This UI is originaly done for my version of Repetier FW which has a lot of flag. I think Marlin do not have info: flag in serial messages so no information

**Comment by khseal** [comment]
I try to find information. Error information is displayed in the logs.

**Comment by luc-github** [comment]
the flag are processed here : https://github.com/luc-github/ESP3D/blob/master/esp3d/command.cpp#L524-L556

May be marlin ones have different case or changed since I checked

**Comment by khseal** [comment]
Information message have flag "echo:".  It seems there are no status messages in Marlin.

**Comment by luc-github** [comment]
Ok will add this flag then for marlin

**Comment by luc-github** [comment]
should be done by https://github.com/luc-github/ESP3D/commit/6cbb11ddf0f34105d585c51b0d36d17ad87f99f4
