### ISSUE TITLE
Firmware Updater. How to use?

### ISSUE THREAD

**Issue by khseal** [luc-github/ESP3D#140]
I compile the firmware in Arduino IDE.
I tried to flash. I got a firmware canсel.

**Comment by khseal** [comment]
I have a flash memory of 1MB. Under spiff allocated 512kb. Possible to update the firmware is not enough memory, and it was necessary to allocate a spiff 128kb?

**Comment by luc-github** [comment]
Did you check the FAQ? https://github.com/luc-github/ESP3D/issues?utf8=%E2%9C%93&q=label%3AFAQ+

**Comment by khseal** [comment]
I checked. Nothing about the update is not found. But I realized that himself has created the problem.

**Comment by luc-github** [comment]
Yes I am confused you talk about SPIFFS size necessary for having webupdate working, so this is in FAQ
and now you talk about update not found ? it is a file upload in system page

**Comment by khseal** [comment]
My English is very bad. Therefore, I can not right the first time to find information in English. =)
