### ISSUE TITLE
"Incorrect SSID" when trying to connect to station with spaces in SSID

### ISSUE THREAD

**Issue by denr01** [luc-github/ESP3D#155]
I tried to connect to my home wifi, and got this error. Aparently, this is because of spaces in the station name. I commented out the 'for' loop in the WEBINTERFACE_CLASS::isSSIDValid function, and it connected successfully, but I think it's better to be fixed, to make sure that no one else will have this problem.

**Comment by luc-github** [comment]
Hi what version are you using ? the released one ?
the git version already do not check the space anymore as ESP core support it now

**Comment by denr01** [comment]
Yes, I have downloaded the latest version from releases. Now I downloaded the git version, installed it and it seems to work fine. Thanks!
