### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Aleks-MO** [luc-github/ESP3D#156]
Compilation error, I can not understand what's wrong....?
![error esp12f](https://cloud.githubusercontent.com/assets/22274265/23943525/365fa6d4-0989-11e7-8af2-255f7214f309.jpg)

**Comment by luc-github** [comment]
as you use master git version you must use latest git version of esp core to get all update from core

**Comment by Aleks-MO** [comment]
It is possible with the link to the latest version, my version is 2.3.0, I did not find the other one.

**Comment by luc-github** [comment]
read 
https://github.com/esp8266/Arduino/blob/master/README.md#using-git-version

unfortunatly AFIK the night build is not working yet so no way to use the board manager yet

**Comment by luc-github** [comment]
the latest naight build seems ok so you may want to give a try  http://arduino.esp8266.com/nightly/package_esp8266com_index.json
but this is not same as latest git one - as it is from 22nd february

**Comment by luc-github** [comment]
but I cannnot confirm will still be the case in future update

**Comment by Aleks-MO** [comment]
Thanks, the compilation went fine! I'm very impressed.
![error esp12fz](https://cloud.githubusercontent.com/assets/22274265/23957228/4f5a1fdc-09b8-11e7-84a2-bc1a74ab5074.jpg)
I will conduct the test of 3D print ...

**Comment by luc-github** [comment]
good , ^_^
I close issue then

**Comment by Aleks-MO** [comment]
the question is closed.

**Comment by denmorru** [comment]
Rename this issue to smart searchable error text:
esp3d:99: error: 'class HardwareSerial' has no member named 'setRxBufferSize'

**Comment by luc-github** [comment]
hmm issue is closed and FAQ is clear IMHO

**Comment by denmorru** [comment]
Clear? Maybe. But badly searchable.
"Error when compiling" is absolutely not smart topic (header) for issue. There are lots of different errors on compilation with different solutions.
Link to  http://arduino.esp8266.com/nightly/package_esp8266com_index.json is not found by text search in Wiki, in readme... Troubleshooting needs higher searchabilities. 
Look at this issue https://github.com/luc-github/ESP3D/issues/137 with proper error description "'class HardwareSerial' has no member named 'setRxBufferSize'" put to topic. I offered rename this issue like that.

**Comment by luc-github** [comment]
well if your read what I wrote : night build are not working  yet
so that is why you hardly find some reference to : http://arduino.esp8266.com/nightly/package_esp8266com_index.json
even on esp core github
