### ISSUE TITLE
DEBUG_OUTPUT_SPIFFS compilation: error: 'File' was not declared in this scope

### ISSUE THREAD

**Issue by denmorru** [luc-github/ESP3D#159]
enable in config.h 
```
#define DEBUG_ESP3D
#define DEBUG_OUTPUT_SPIFFS
```
because need LOG to be saved to 1M flash filesystem.

esp3d FW: 0.9.78  with ESP8266 package 2.4.0. in Arduino IDE 1.6.8

**Comment by luc-github** [comment]
wrong line commented 
fixed with https://github.com/luc-github/ESP3D/commit/7626717d9459908ff13fb0cb5688346a3d1e6175
