### ISSUE TITLE
Join web user interface tabs "AP" and "Station" into one

### ISSUE THREAD

**Issue by denmorru** [luc-github/ESP3D#160]
Pending rework of user interface would be offered here.
Network connectivity settings are not often used, and they are minor in ESP3D usage time. 
So, move those network tabs into one small tab in the end of the menu list.
I suggest ESP3D software to be targeted to 3D printer functions, which must go on first tab, default tab.
Network connectivity is well implemented in other public free libraries, like <WiFiManager.h>, so, they must not take time from developers in this project, until proved opposite.

**Comment by luc-github** [comment]
current devt fw does not have anymore the /HOME /PRINTER /etc page but only one 
Wifi Config is one tab - Printer config is one tab - Camera is one tab - printer page is default tab
  
![image](https://cloud.githubusercontent.com/assets/8822552/24475406/02ec242e-14d0-11e7-820b-9cd5c42f9c7c.png)
![image](https://cloud.githubusercontent.com/assets/8822552/24475463/3492df86-14d0-11e7-9531-ab9c4b810716.png)
Printer tab is inspired from imrahil UI for smoothieware
![image](https://cloud.githubusercontent.com/assets/8822552/24475486/484578d6-14d0-11e7-8931-9c4942a4162f.png)

 and I do a second one with repetier host UI 
![image](https://cloud.githubusercontent.com/assets/8822552/24475557/7ffeb620-14d0-11e7-9720-54b589e60371.png)

SPIFFS and web update are just a dialog box launched from menu when needed

So all you describe is already done from ESP FW point of view - I am still working on UI part to get good asynch reactivity

**Comment by denmorru** [comment]
So, where is actual version of web user interface for test?
https://github.com/luc-github/ESP3D/tree/master/UI is this working with current firmware?
So, tabs will be:
1) Printer control page, including SD-card browser
2) Camera and system information, including ex-HOME
3) Printer and system config, including SPIFFS browser , firmware update, ex-EXTRA
4) WiFi config 
?

**Comment by denmorru** [comment]
One more suggest on how to arrange master branch:
move https://github.com/luc-github/ESP3D/tree/master/docs  to https://github.com/luc-github/ESP3D/wiki
So, targeting to clean distributive

**Comment by luc-github** [comment]
No it won't be compatible as no more template engine - which break everything in current UI but save some memory to add more query features - so I won't share before FW has finished UI to work with
