### ISSUE TITLE
Disabled TCP_IP_DATA_FEATURE cause compilation failure: 'send2TCP' is not a member of 'BRIDGE'

### ISSUE THREAD

**Issue by denmorru** [luc-github/ESP3D#162]
```
bridge.cpp:144: error: 'send2TCP' is not a member of 'BRIDGE'
BRIDGE::send2TCP(st);
```
Also: "MAX_SRV_CLIENTS" redefined
config.h:33
config.h:142
`#undef MAX_SRV_CLIENTS` ignored
IDE 1.8.2

**Comment by luc-github** [comment]
fixed with https://github.com/luc-github/ESP3D/commit/f546cb230c0a723ef61ff85c25a802ef22caf225
I need to  update travis with all tests flag but no time
