### ISSUE TITLE
Allow printable ASCII in SSID name

### ISSUE THREAD

**Issue by ligius-** [luc-github/ESP3D#174]
Currently the firmware rejects any non-alphanumeric letters in the SSID name (when acting as a client), I haven't studied this extensively, but I believe most printable characters should be supported. By commenting out some code inside "isSSIDValid" I can get the firmware to successfully connect to a "Fritz!Box".

**Comment by luc-github** [comment]
what fw version are you using? looking at master there is no more check already

**Comment by luc-github** [comment]
https://github.com/luc-github/ESP3D/blob/master/esp3d/config.cpp#L62

**Comment by luc-github** [comment]
and devt branch use isPrintable, so it should work

**Comment by luc-github** [comment]
Any update ?

**Comment by ligius-** [comment]
Sorry for the late reply. I was testing on the release branch (0.6.2), as that's what is currently most accessible to potential users. Now it would be your choice on how the handle this: reject this as "not applicable" or mark it as fixed when a new release is made.

**Comment by luc-github** [comment]
Hi Ok noted - so it is already fixed in master - I plan to do a release in coming days of master and move devet to master as stable now
