### ISSUE TITLE
OLED support 

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#186]
Now Oled LCD can be very cheap (2$) it can be nice to display IP / wifi status / signal on it - if printer do not have screen or to have always information available

I plan to use https://github.com/squix78/esp8266-oled-ssd1306 because I tested it - but open to another if exists

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/32105122-a6f90f70-bb27-11e7-86f5-058366f89d04.png)

**Comment by luc-github** [comment]
Here a possible UI : 
Line 1 : SSID used and signal if station mode - SSID and access Point icon if AP mode
Line 2: SSID
Line 3: Message
Line 4: Message or progression bar
![image](https://user-images.githubusercontent.com/8822552/33242009-45a1ccd0-d2ce-11e7-8c03-f38717589e84.png)

**Comment by shaddow501** [comment]
Dear Luc

I have made a case for Lolin ESP32 OLED if you are interested with 3D print.

https://www.thingiverse.com/thing:2752734

**Comment by luc-github** [comment]
Note: 
Heltec wifi kit 32 with embeded oled screen need extra init : 
```
 //For Embeded OLED on Wifi kit 32
   pinMode(16,OUTPUT);
   digitalWrite(16, LOW);   // turn the LED on (HIGH is the voltage level)
   delay(100);                       // wait for a second
   digitalWrite(16, HIGH);    // turn the LED off by making the voltage LOW
```
the standalone oled screen I have do not need such extra initialization but better to plan it with a flag

**Comment by luc-github** [comment]
Test skech to evaluate rendering show that SSID can over load screen so need a banner rendering function that do not rely on delay / yield to be used with async webserver - it should not be linked but better plan it
So IP and SSID have exchanged positions to meet the screen size constraint:
![image](https://user-images.githubusercontent.com/8822552/35052255-6e9bdc8c-fba7-11e7-945a-2c2bb3510325.png)
![image](https://user-images.githubusercontent.com/8822552/35052523-1289836c-fba8-11e7-81e5-faae79840074.png)

**Comment by luc-github** [comment]
I close issue as it is in TODO list #179
