### ISSUE TITLE
Diagram of HY_BASE_L V1.0

### ISSUE THREAD

**Issue by arcidodo** [luc-github/ESP3D#193]
Hi there,

i bought an Infitary m508 printer but cant find any information about the board (HY_BASE_L V1.0). can someone tell me where the RX/TX is located? 

![image](https://user-images.githubusercontent.com/678514/33872560-9b8c811c-df17-11e7-87bb-746309930c53.png)

https://www.alunar.net/m508-self-assembly-3d-printer.html

**Comment by luc-github** [comment]
Looks like MKS base depopulated - what are the 8 pins close to the Z end stop cable ? looks like the Aux 1 connector

**Comment by arcidodo** [comment]
thats D12, D11 & A12, A11

**Comment by ekaggrat** [comment]
i dont think they have broken it out.. you will need to solder it directly from the chip if your soldering skills are good enough

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/33877169-dc614bf4-df27-11e7-8166-282fd7446d55.png)
what about the others free connectors ?

**Comment by arcidodo** [comment]
there are 2 ICSP ports on it, the 2 connectors below the USB connection. and the pins above the LCD screen port are D12, D11 & A12, A11

**Comment by luc-github** [comment]
did find out ?

**Comment by luc-github** [comment]
Close it as no update - feel free to reopen if new info

**Comment by henri98** [comment]
Any updates on this?

**Comment by azoul21** [comment]
moi j'ai un problème avec cette carte mère car quand j'imprime des grand fichier d'une dure de 20H la moindre  coupure de courant l'imprimante revient a imprimer a zero il n’y pas de solution a ça merci
