### ISSUE TITLE
Add support for 3rd party application like GCodePrintr / octodroid

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#20]
but need to define first for what app - seems octodroid has a repo but it is not very active https://github.com/mariogrip/octodroid

or I code client myself

**Comment by TRoager** [comment]
theres also: 
https://gitlab.com/damfle/SmoothieControl

**Comment by luc-github** [comment]
Thanks for sharing I will have look ^_^

**Comment by TRoager** [comment]
Your welcome, i check this hub daily :)

**Comment by luc-github** [comment]
Seems websocket is the way to go to properly support any app

**Comment by luc-github** [comment]
But first need to identify an App to target it - so far I did not found any stable one

**Comment by luc-github** [comment]
As UI is now monolitic I do not see a real use of working on standalone client

**Comment by luc-github** [comment]
Just a note :    
Seems 3D Fox - 3D Printer / CNC Controller  https://play.google.com/store/apps/details?id=com.fox3d.controller
works pretty well with data port and ESP3D
