### ISSUE TITLE
Esp wifi printer on HA

### ISSUE THREAD

**Issue by vMeph** [luc-github/ESP3D#201]
@luc-github do you know homassistant?
You could expand your project into HA comunity if you could adapt a homassistat component to interact with the ESP and HA

**Comment by luc-github** [comment]
Yes I know it - there is a ticket for Jeedom as it is the one I use today but it should cover all home server as I explained here : https://github.com/luc-github/ESP3D/issues/179#issuecomment-341488125
using JSON should work with all servers

**Comment by vMeph** [comment]
Thats great news :)

**Comment by luc-github** [comment]
I guess issue can be closed as one ticket already exist
