### ISSUE TITLE
Reset ESP8266 wirelessly

### ISSUE THREAD

**Issue by vader333** [luc-github/ESP3D#213]
I have a Tranceboard Ozone (new smoothieware clone) and it has an esp8266. It used a modified version of ESP3D. I tried flashing the newest ESP3D to it, but somehow it screwed up and it displays a broken webpage. How can I reset/format SPIFFS without a TTL to USB cable? Like, via Telnet?

Edit: Tranceboard uses a modified version of ESP3D. I used their firmware update option while connected in AP mode to try and update to the latest stock ESP3D version. It caused the ESP8266 module to only display a broken index.html page that looks like this:

![untitled](https://user-images.githubusercontent.com/19439978/37867329-7794c0b6-2fd1-11e8-8f80-b3499b70abc0.jpg)

**Comment by luc-github** [comment]
connect your ESP using the data port (8888 by default) using putty in raw mode for example and use the 
https://github.com/luc-github/ESP3D/wiki/Direct-ESP3D-commands
format command 
Format SPIFFS
[ESP710]FORMAT pwd=<admin password>

**Comment by luc-github** [comment]
@vader333  I saw the board and wifi connector here http://singularidea.cn/tranceboard/ - 
Please can you share the wifi module picture ? I do not it see on website but I see connection description so I guess it is sells with board ?

**Comment by luc-github** [comment]
@vader333 is this board better than your MKS + TFT ?

**Comment by vader333** [comment]
![image](https://user-images.githubusercontent.com/19439978/37865153-6e726510-2fb3-11e8-8807-ff7894ae7636.png)

This is the wifi module. 

It's not a bad board. Includes many features like auto shutdown, nice screw terminals for power, blade fused circuitry for heaters, and pins dedicated to Octopi. It requires external stepper motors though, which I think is a good design choice, but is a little messy to implement.

It's much much much better than an MKS Sbase. I'm using MKS LV8729 drivers, and it's extremely quiet on 128 microsteps. Draw back is that you can't use their pretty touch screen with wifi, as they both use the same pins.

![image](https://user-images.githubusercontent.com/19439978/37865202-102e7132-2fb4-11e8-9ac0-aa7efbf7ffbf.png)

**Comment by luc-github** [comment]
But I see several connectors on their TranceScreenOne 
Is there no way to hook wifi module on it like MKS-TFT ?

**Comment by vader333** [comment]
According to the manufacturers, it's possible, but you wouldn't be accessing the sd card on the main board. The TFT acts like a gcode machine. And yea, both 13 and 18 share branches of the same pins. Still, it's not a bad arrangement to hook the esp8266 to the TFT, you just don't get to change the config as easily.

**Comment by vader333** [comment]
I'm afraid they don't have anything of the sort. Could probably ask them, but it isn't opensource or anything like that.

**Comment by luc-github** [comment]
沒問題- thanks for sharing - always interresting to learn new stuff ^_^

**Comment by luc-github** [comment]
Is your ESP board ok now ? Format solved your issue ?

**Comment by vader333** [comment]
Haha, I haven't tried yet =P. I'll do it now

**Comment by luc-github** [comment]
Hi ok that is more clear ^_^
Yes they must use online resources to help to display like smoothie UI do and this won't work if you are nor connected to internet - that is why I made ESP3D web UI independant of external resource and so working in AP mode.
You said they use a modified version of my FW ? 

you can format using this command on ESP3D: [ESP710]FORMAT
the password is only necessary if you have enabled login feature which is disabled by default

but formating is not necessary if you already flashed their board with my FW
if board has my  recent FW just go to embedded uploader
`<your IP>?forcefallback=YES`
you should get a UI allowing to delete/upload files : <img src='https://raw.githubusercontent.com/luc-github/ESP3D/master/images/docs/embedded.png'>
So delete files and upload latest index.html.gz

**Comment by vader333** [comment]
OMG IT WORKS!!!!! The format did the trick! It went to your fallback, and then I could upload the correct files to the SPIFFS! Thank You so much! If you have a donate link, I'd be very happy to donate!

Although, it can't access the SD Card though. But I guess I'll have to ask the manufacturers about that haha. I'm very happy, I was about to send this back to China to have them reflash their interface.

**Comment by luc-github** [comment]
Good to see you make progress
Donate link is in read me : https://github.com/luc-github/ESP3D/blob/master/README.md#donate

About SD card it is weird 
What is M20 command result in terminal

**Comment by vader333** [comment]
![untitled](https://user-images.githubusercontent.com/19439978/37888598-e59b3f7a-30fa-11e8-952c-b68af44ab68f.jpg)
It looks ok... I'll try reflashing the firmware.

**Comment by luc-github** [comment]
Did you select the FW target as smoothieware in webUI ?
can you screenshot the UI ?

**Comment by vader333** [comment]
Yup, I selected Smoothieware.

![image](https://user-images.githubusercontent.com/19439978/37895762-dae67a3a-3114-11e8-898c-6f5bffccc387.png)

**Comment by luc-github** [comment]
there is an issue but I cannot reproduce it, update with latest UI https://github.com/luc-github/ESP3D-WEBUI/blob/master/index.html.gz, also there some bug fixes on FW - you do not have the latest one 

![image](https://user-images.githubusercontent.com/8822552/37896269-b61a7192-30e3-11e8-9141-c5a1e0777834.png)

**Comment by vader333** [comment]
![image](https://user-images.githubusercontent.com/19439978/37896478-72d65abc-3116-11e8-9e9a-296bb45a4d1d.png)

I've updated, but still can't though.

![esp3d1](https://user-images.githubusercontent.com/19439978/37896496-7d46aad8-3116-11e8-9f59-93f684884a27.jpg)
![esp3d2](https://user-images.githubusercontent.com/19439978/37896501-7f9a08f2-3116-11e8-843b-857fa3d465cf.jpg)
![esp3d3](https://user-images.githubusercontent.com/19439978/37896509-820f2b30-3116-11e8-876a-cc7439486a42.jpg)
![esp3d4](https://user-images.githubusercontent.com/19439978/37896513-85c52914-3116-11e8-9fd9-3a6d83fdaa93.jpg)

**Comment by luc-github** [comment]
yes any SD upload will fail as SD is not seen - did you do any modification in FW before flashing ?

**Comment by vader333** [comment]
Nope. It seems to be purely a UI error. I can make a macro that references /sd/on_boot.gcode, and it runs.
![image](https://user-images.githubusercontent.com/19439978/37897060-d4cb56d6-3117-11e8-8b0d-e756b78737ac.png)

**Comment by luc-github** [comment]
can you type this command in manual command and share the output : 
`[ESP800]` I suspect EEPROM data is corrupted by previous FW

**Comment by vader333** [comment]
![image](https://user-images.githubusercontent.com/19439978/37897160-1ab354fa-3118-11e8-869e-f628b74abf5a.png)
Here you go

**Comment by luc-github** [comment]
So yes this is the issue, correct output is:

```
[ESP800]
FW version:0.9.99 # FW target:smoothieware # FW HW:Serial SD # primary sd:/ext/ # secondary sd:/sd/ # authentication:no
```
as you see SD is not defined

**Comment by luc-github** [comment]
there 2 ways 
1 -  use RESET command to clean EEPROM with proper data
2 - set manually the values

**Comment by luc-github** [comment]
as you used a previous FW the cleanest would be to do an EEPROM reset to be sure no other data is missing

**Comment by luc-github** [comment]
but I can give you the manual command to test first

**Comment by vader333** [comment]
I'll do a reset then.

**Comment by luc-github** [comment]
`[ESP401]P=851 T=B V=2`
and
`[ESP401]P=852 T=B V=1`

becareful these update directly the EEPROM

**Comment by luc-github** [comment]
try these command first - to confirm the fix

**Comment by luc-github** [comment]
you need to refresh page after of course to see the update of `[ESP800]` output

**Comment by vader333** [comment]
I've used the commands, and the interface is fixed, but I still can't access the SD card

![image](https://user-images.githubusercontent.com/19439978/37898389-4764dec6-311b-11e8-938a-f8ddb1ce83c8.png)

**Comment by luc-github** [comment]
press the button /SD nothing happen ?

**Comment by luc-github** [comment]
what the command `ls /` and `ls -s /sd` give as output ?

![image](https://user-images.githubusercontent.com/8822552/37899160-03e51ec0-30eb-11e8-8b19-6f624764e695.png)

**Comment by vader333** [comment]
How do I use the Reset command? Just type RESET?

**Comment by luc-github** [comment]
`[ESP444]RESEST`
then `[ESP444]RESTART`

**Comment by luc-github** [comment]
@vader333 
Any update ? 
Is you issue fixed ?

**Comment by luc-github** [comment]
upload is very slow and subject to error as it is serial upload
but even upload fail listing the files is working - right ?

**Comment by vader333** [comment]
Yup. Listing file works

**Comment by luc-github** [comment]
You upload to which directory ? /sd or /ext ?

**Comment by luc-github** [comment]
and can you share the name of the file you try to upload - I will try to reproduce

**Comment by vader333** [comment]
MD1_xyzCalibration_cube.gcode

**Comment by luc-github** [comment]
remove MD1_ from file name
Smoothie does not like name starting like GCODE command (MXXX)

**Comment by luc-github** [comment]
I meet this issue before and I have just checked with small file - upload failed until file is renamed

**Comment by luc-github** [comment]
but my comment about upload stay same :  Serial upload take ages ...

**Comment by vader333** [comment]
Ah, okies, I'll try that! ^_^

**Comment by vader333** [comment]
Yes! It was able to upload! Thank you so much for your help!

**Comment by luc-github** [comment]
great enjoy 😸
