### ISSUE TITLE
ESP EEPROM reset after erase

### ISSUE THREAD

**Issue by luxarts** [luc-github/ESP3D#218]
Hello!
I was working on my projects with the board (ESP-01) and I erased the FLASH selecting Tools -> Erase Flash -> All Flash Contents in Arduino IDE. When I tried to upload the ESP3D firmware again (was working before) the board sent the message "ESP EEPROM reset". I enabled the debug and found what is causing this issue:

When erase the FLASH the EEPROM data is set to 255 in each address. The function _CONFIG::InitExternalPorts()_ always returns False because the webport and dataport (stored in EEPROM) are out of range of _DEFAULT_MIN_ and _DEFAULT_MAX_ definitions .
I solved it writing all the EEPROM with 0's and setting both _DEFAULT_MIN_ definitions to 0 (previously 1).
You can put this routine in a function and call it when the port values are out of range to reset it.

Have a nice day!
Lucas

**Comment by luc-github** [comment]
ESP EEPROM reset after erase is normal behaviour
If not expected data is found in EEPROM sector for ESP3D settings it reset EEPROM with default values so at next restart ESP3D will find default settings 
You mean after EEPROM reset values are still not good?

**Comment by luxarts** [comment]
Yes, after reset the values still 255 in each EEPROM address. I checked with the EEPROM read example sketch (of course, uploading without the erase all option in the Arduino IDE).

**Comment by luc-github** [comment]
Strange. Does command [ESP444]RESET fail reset EEPROM settings?

**Comment by luc-github** [comment]
[ESP400]plain
 will drop ESP3D EEPROM settings

**Comment by luxarts** [comment]
I uploaded the lastest firmware and the same issue. This is what I get in the serial debug:
```
Debug Serial set
Error no EEPROM access
M117 ESP EEPROM reset
Chip ID: 2608836
CPU Frequency: 160Mhz
Free memory: 40.16 KB
SDK: 2.2.1(cfd48f3)
Flash Size: 1.00 MB
Available Size for update: 3.00 GB(Ok)
Available Size for SPIFFS: 1.00 GB
Baud rate: 115200
Sleep mode: Modem
Channel: 1
Phy Mode: 11g
Web port: 0
Data port: 0
Active Mode: Wifi Off
Captive portal: Enabled
SSDP: Enabled
NetBios: Enabled
mDNS: Enabled
Web Update: Enabled
Pin Recovery: Disabled
Authentication: Disabled
Target Firmware: ???
Debug: Debug Enabled :serial",FW version: 0.9.102
Error write string
Restarting
```
The board doesn't respond to any command. Seems like a issue in the EEPROM write routine.

**Comment by luc-github** [comment]
Is EEPROM sample even working?
Could be the puya flash chip used on your ESP instead of normal ones

**Comment by luxarts** [comment]
Yes, the EEPROM works perfect. I uploaded the following sketch:
```
void setup(){
  int val=0;
  EEPROM.begin(512);
  Serial.begin(115200);
  for (int i = 0; i < 512; i++){
    EEPROM.write(i, val);
    val++;
    if(val==256)val=0;
  }
  
  Serial.println("Write finished");
  
  for (int i = 0; i < 512; i++){
    Serial.print("Read->Addr=");
    Serial.print(i, DEC);
    Serial.print("\tValue=");
    Serial.println(EEPROM.read(i), DEC);
  }
  EEPROM.end();
}

void loop(){
}
```
And the output it's correct.
I doubt that it's a ESP problem. As I said, the firmware was working fine before. Can you try to replicate my issue with a board? Erase all and try to run the firmware.

Thanks for the replies!

**Comment by luc-github** [comment]
I use the reset often so I know it works . EEPROM functions did not changed since begining
But I never used erase flash function, I will give a try when back home tonight

So to replicate 
1 erase all flash using ide menu ?
2 flash latest FW 
3 check serial terminal 
Correct ?

**Comment by luxarts** [comment]
Found the problem: I put some `LOG("")` in each `if` of the _CONFIG::reset_config()_ and found that DEFAULT_STA_SSID was the problem so open config.h and the value was an empty string. I wrote whatever and the sketch now works fine.
The `CONFIG::write_string()` was trying to put an empty value and the `if()` at the end is returning false, preventing the call to `EEPROM.write()`.

Thanks for all!

**Comment by luc-github** [comment]
but default value is ESP3D so you did some modification in FW ?

**Comment by luxarts** [comment]
Maybe when I replaced the old files with the new ones that file wasn't replaced. Was my mistake don't watch the modification date of the files after replace, haha.

**Comment by luc-github** [comment]
ok anyway seems still have some glitch in EEPROM output I forget to update on git
Will update soon

Enjoy your ESP

**Comment by luc-github** [comment]
closing issue
