### ISSUE TITLE
After I connect through Wi-Fi and enter the password it tells me my index.HTML.gz file is outdated

### ISSUE THREAD

**Issue by PETEIOT** [luc-github/ESP3D#219]
After I connect through Wi-Fi and enter the password it tells me my index.HTML.gz file is outdated

**Comment by luc-github** [comment]
what version do you use ?

**Comment by PETEIOT** [comment]
Are you asking what version of arduino,  if so I have the most recent version. I  do have a screenshot but not sure how to send it.

**Comment by PETEIOT** [comment]
I was using the mobile browser I switch the desktop and it me add the screenshot 

![ae3d53ba-d536-40e6-9c31-4b8fca9f7d31](https://user-images.githubusercontent.com/35778227/39220836-d4b4833a-47f0-11e8-8029-8564a89846dd.png)

**Comment by luc-github** [comment]
index.html is not outdated is missing as stated in screenshot

check point 4 of readme which explain that you must upload files from data directory, you may noticed screen is same as yours
![image](https://user-images.githubusercontent.com/8822552/39221078-93d46822-4867-11e8-9bd1-4f78de8ad447.png)

**Comment by luc-github** [comment]
I guess this issue can be closed

**Comment by PETEIOT** [comment]
Sorry just got around to it and that worked. Thanks for your help!
