### ISSUE TITLE
Wiki: how to add images?

### ISSUE THREAD

**Issue by onekk** [luc-github/ESP3D#220]
How to add images to the wiki?

**Comment by luc-github** [comment]
You can upload here, I will add to repository later

**Comment by onekk** [comment]
OK, here the images the two schematics cited in the wiki page.

 
![wiresesp12e](https://user-images.githubusercontent.com/7129964/39277189-e579c052-48ec-11e8-9eac-6535969fa729.png)
![mks_gen-pin](https://user-images.githubusercontent.com/7129964/39277203-fe6e26e8-48ec-11e8-9214-678b33ecc8c6.png)

Regards

Carlo D.

**Comment by luc-github** [comment]
Images uploaded - wiki updated  - thank you ^_^
