### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hackintoshlover** [luc-github/ESP3D#230]
How do I save jog commands manually by moving respective axes and then executing them
So what it does is when I click an axis it moves and when I press record button it saves the recent gcode
When stop is pressed gcode is saved as a file and then sent

**Comment by luc-github** [comment]
there is no "record" neither "excecute last command" feature so far

but you can use a macro to execute a gcode file you saved on SPIFFS or on SD

**Comment by hackintoshlover** [comment]
How do I save file on spiffs either
Btw is there any way I could add record and execute last command

**Comment by luc-github** [comment]
SPIFFS is ESP file system:
https://raw.githubusercontent.com/luc-github/ESP3D-WEBUI/master/images/SPIFFS.PNG

what is puprpose of that ?

also a jog is actually 3 GCODE commands (relative mode + position command + absolute mode) not 1  so save last command is not waht you want I guess, it is more "last action"

**Comment by hackintoshlover** [comment]
Ya I mean last action

**Comment by hackintoshlover** [comment]
Any help on saving recent action

**Comment by luc-github** [comment]
I guess issue is closed
