### ISSUE TITLE
Typo in espcom.cpp async branch correction attached

### ISSUE THREAD

**Issue by Amtho** [luc-github/ESP3D#234]
size_t   ESPCOM::write(tpipe output, uint8_t d){
	if ((DEFAULT_PRINTER_PIPE == output) && (block_2_printer || CONFIG::is_locked(FLAG_BLOCK_M117))) return 0;
    if ((SERIAL_PIPE == output) && CONFIG::is_locked(FLAG_BLOCK_SERIAL))return 0;
 switch (output) {
#ifdef USE_SERIAL_0
    case SERIAL_PIPE:
        return **Serial.write(d);**
        break;
#endif
#ifdef USE_SERIAL_1
    case SERIAL_PIPE:
        return **Serial1.write(d);**
        break;
#endif
#ifdef USE_SERIAL_2
    case SERIAL_PIPE:
        return **Serial2.write(d);**
        break;
#endif

**Comment by luc-github** [comment]
good catch fixed by https://github.com/luc-github/ESP3D/commit/1f443a00123e436bb068f97987a44b77f22335b9
