### ISSUE TITLE
Feature Request: Use directly to the ESP connected SD Card

### ISSUE THREAD

**Issue by Amtho** [luc-github/ESP3D#237]
Im trying to get your library work with a directly connected SD Card, but i dont know how to start with this. The plan would be to use a SD Card directly connected acorrding to this connection scheme: https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card

**Comment by luc-github** [comment]
This feature  is done already  but code is not public yet, it will be done when host part will be ready 
This is a planned feature originaly for grbl fw(sd support +host feature+screen +rotary encoder)

**Comment by Amtho** [comment]
Ok thanks for the info. I will close the issue then.
