### ISSUE TITLE
ESP2.0 Serial2 with AsyncServer not working. 

### ISSUE THREAD

**Issue by Amtho** [luc-github/ESP3D#240]
Sorry for reopening it, but the case #236 is still not really fixed.
When you use Asyncserver Serial2 is still buggy. When using SyncServer everything is fine.

**Comment by luc-github** [comment]
Actually there is a missing fix for Serial and async, I forgot to implement it because it was not enough for esp8266, but as serial is ok for esp32 it may solve serial2 issue
Will add it in 2.0 asap

**Comment by luc-github** [comment]
@Amtho I just pushed some commits - they should solve issue as on my side Serial2 is now Ok
https://github.com/luc-github/ESP3D/tree/2.0
Got also some fixes pushed by @me-no-dev that would help a lot on Serial too

Please check and let me know

**Comment by Amtho** [comment]
Yes looks good. Now Serial2 is also working with the AsyncServer. Thanks to you both!

**Comment by luc-github** [comment]
Cool ! thanks for the confirmation
