### ISSUE TITLE
M20 is not working and any answer failed on web commands

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#242]
ESP commands are OK but printers commands answers are not (M105, M114, M20, etc...)
it is working on 2.0 so not related to core orz

**Comment by ekaggrat** [comment]
ok great and i was beginning to think that my esp board is flaky

**Comment by luc-github** [comment]
Actually on my side issue was RX was not properly connected, I have verified connection and now it is OK 
Which make me relieve as I always test this feature

Please check your wiring

**Comment by luc-github** [comment]
Any update ?

**Comment by luc-github** [comment]
If no update I close issue
