### ISSUE TITLE
Azteeg X5 Mini

### ISSUE THREAD

**Issue by ModMike** [luc-github/ESP3D#246]
What is different about the Azteeg version for X5 mini?

**Comment by luc-github** [comment]
Depend of version you have -  Azteeg X5 Mini has wifi version which allow to access directly to SD Card

**Comment by ModMike** [comment]
Sorry, I should have specified the Azteeg X5 Mini wifi, latest version.

**Comment by ModMike** [comment]
Understood.  I can't find the current Azteeg X5 mini version on the Panucatt site.  Do you have a link?

**Comment by luc-github** [comment]
http://www.panucatt.com/azteeg_X5_mini_reprap_3d_printer_controller_p/ax5mini.htm
http://panucattdevices.freshdesk.com/support/solutions/folders/1000183237

**Comment by ModMike** [comment]
Sorry, didn't realize it was already installed.  I am using it with Marlin (I created some pin configs and such to support it).  My current board blew up because of a bad driver and another is on the way.

Will the current version that is preinstalled support Marlin? If so do I have to change anything?  

Merci beaucoup pour les réponses!

**Comment by luc-github** [comment]
oui ESP3D est preinstalle mais Azteeg X5 mini  ce n'est que smoothieware en principe 
Il y a la version 32bit de marlin mais elle n'est pas encore stable

**Comment by ModMike** [comment]
Je te réponds en anglais pour que tous le monde peut suivre.  Et mon français (anglophone quebecois) est horrible.

I am running 32 bit Marlin on it and everything works so far, that it is until I swapped my drivers and shorted the board.  If all goes well, I will do a pull request soon and it will be officially supported.

Marlin 2.0.x bug fix already supports the Azteeg X5 GT and Re-arm.  I used the Re-Arm with Marlin for over a month with no issues.  I even got it to work with the stock CR-10 display.

**Comment by luc-github** [comment]
Ok it is some time I did not tried the 2.0 for LPC1769 - happy to see it is better

**Comment by ModMike** [comment]
So hopefully last question for today, what, if anything, do I need to do to get the Azteeg X5 Mini Wifi to Web UI to work with Marlin?

**Comment by luc-github** [comment]
Just choose Marlin as FW target in Web UI

**Comment by ModMike** [comment]
Great, I wasn't sure that was available in the Azteeg Mini Wifi version.

**Comment by luc-github** [comment]
No problem is on it, as well as repetier and smoothieware

**Comment by ModMike** [comment]
I got my replacement Azteeg X5 mini, loaded Marlin and was able to connect through USB with S3D.  Everything responds fine from the terminal.  

I disconnected from the S3D terminal, set the Web UI to Marlin,rebooted, and tried to send commands through the Web UI terminal but Marlin will not respond.  

Do I need to set up a software serial link between the two?

**Comment by luc-github** [comment]
S3D do not allows TCP connection only serial, as far I kown only repetier and pronterface allow tcp connection

To use S3D with Azteeg Wifi - instead of print from host, print from SD - upload generated GCODE file to Azteeg SD ( can be done using web UI) then launch print ( can be done using web UI)

If you really want to stream from S3D, you need to find a drivers  or device that do a USB/Serial <-> TCP bridge - I never try so I do not know if it works

**Comment by ModMike** [comment]
Luc,

I was not trying to use TCP, I was just pointing out that I am able to get a response to M119 to prove Marlin is running on the board and responsive to commands.

Now I need to get commands working through WEB UI.  DO I need to do anything to get WEB UI to talk to Marlin on that board or should it just work?

When I connect through WEB UI and issue an M119 command from the WEB UI Send command panel, I get no response.

**Comment by luc-github** [comment]
Sorry my mistake I read too fast.
For ESP3D/Marlin communicate you need to be sure : 
1 - Marlin Baud rate and ESP3D baud rate are identical
2 - Marlin read the Serial connector of Azteeg , I know Smoothieware do it by default , I do not know if Marlin do it by default or need to be configured ( I cannot try I do not have any Azteeg Wifi)

**Comment by ModMike** [comment]
Thats what I suspected, thanks!

**Comment by ModMike** [comment]
Do you know which serial port is associated with the wifi on Azteeg?

**Comment by luc-github** [comment]
No sorry - you should contact panucatt I think  - as said I do not have any Azteeg X5 Wifi so hard to help

**Comment by ModMike** [comment]
Understood, thanks.

**Comment by luc-github** [comment]
You may ask also on Marlin - they should know - I remember last time I tested on Re-ARM I had to change the configuration to use the internal serial instead of usb port and at this time could not use both

**Comment by luc-github** [comment]
here the starting point :https://github.com/MarlinFirmware/Marlin/pull/8004#issuecomment-338695158
I had to use Serial 0 instead of -1

**Comment by ModMike** [comment]
Luc, got it working with the following:

#define SERIAL_PORT -1
#define SERIAL_PORT_2 0

Very close to what you said, just need to be exactly that.  Thank you very much.

By the way, is there a way to embed a video stream using the camera function a la Octoprint?

**Comment by luc-github** [comment]
Cool you found out :)
Camera tab is enabled if you click on check box close to camera icon on top left

**Comment by ModMike** [comment]
I understand that :-)  What I am asking is what is the result?  Does it embed a video in the WEB UI a la Octoprint?  Also what camera do you recommend?

**Comment by ModMike** [comment]
Also is it ok to wire an arducam directly to the ESP8266?  is that the preferred method?  How many FPS can you get?

**Comment by ModMike** [comment]
Sort of like this but using the module?

https://www.instructables.com/id/ArduCAM-Mini-ESP8266-Web-Camera/

**Comment by luc-github** [comment]
No, connect an arducam to ESP8266 is bad idea , performance will be bad, I did some tests before (https://github.com/luc-github/ESP3D/issues/82) and for 10$ you got a good wifi cam that won't overload ESP (arducam is not cheap IMHO)- also you won't be able to connect arduicam on Azteeg

On another hand ESP32 is good candidate for this - because it has already hardware support  for camera and more pins.
I have ordered this : https://www.aliexpress.com/item/M5Stack-Official-ESP32-Camera-Module-Development-Board-OV2640-Camera-Type-C-Grove-Port-3D-Wifi-Antenna/32881414545.html?spm=a2g0s.9042311.0.0.498a4c4dq35luy and I need to see how to add such support to ESP3D
but I have others projects to finish first so may not be soon but will be in 2.5

**Comment by ModMike** [comment]
So basically getting a self contained IP cam and linking to it's IP is best option?

**Comment by ModMike** [comment]
What a genius I am.  I have a remarkable grasp of the obvious :-)

From what I gather, the camera you linked to is a fully independent IP camera capable of pictures and streaming, correct?  Do you or anyone else have firmware for it?

If so I will order 3 today.

Thanks!

**Comment by ModMike** [comment]
https://www.instructables.com/id/M5Cam-X-M5Stack/

**Comment by luc-github** [comment]
Sorry what Firmware you talk about ? Actually any camera allowing direct web access will fit

**Comment by luc-github** [comment]
Ho you mean m5stack. There is a fw available already.

**Comment by ModMike** [comment]
Firmware for the M5 camera.  I was originally looking for a webcam but everything has an SD card and battery and is big.  The one you linked too is good but ideally I would like one with a video compressor built in.

**Comment by ModMike** [comment]
If can just plug it in and get 10 to 15 FPS I am happy.  When I use the camera option, does the video display in your WEB UI?

**Comment by luc-github** [comment]
I have only did few test as by default it is in AP mode:
```
[0;32mI (28) boot: ESP-IDF v3.1-dev-1101-g1f7b41e2-dirty 2nd stage bootloader[0m
[0;32mI (28) boot: compile time 10:53:23[0m
[0;32mI (29) boot: Enabling RNG early entropy source...[0m
[0;32mI (34) boot: SPI Speed      : 40MHz[0m
[0;32mI (38) boot: SPI Mode       : DIO[0m
[0;32mI (42) boot: SPI Flash Size : 4MB[0m
[0;32mI (47) boot: Partition Table:[0m
[0;32mI (50) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (57) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (65) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (72) boot:  2 factory          factory app      00 00 00010000 00100000[0m
[0;32mI (80) boot: End of partition table[0m
[0;32mI (84) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x14250 ( 82512) map[0m
[0;32mI (122) esp_image: segment 1: paddr=0x00024278 vaddr=0x3ffb0000 size=0x037f8 ( 14328) load[0m
[0;32mI (128) esp_image: segment 2: paddr=0x00027a78 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (129) esp_image: segment 3: paddr=0x00027e80 vaddr=0x40080400 size=0x08190 ( 33168) load[0m
[0;32mI (151) esp_image: segment 4: paddr=0x00030018 vaddr=0x400d0018 size=0x64270 (410224) map[0m
[0;32mI (295) esp_image: segment 5: paddr=0x00094290 vaddr=0x40088590 size=0x07ba8 ( 31656) load[0m
[0;32mI (309) esp_image: segment 6: paddr=0x0009be40 vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;32mI (319) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (319) boot: Disabling RNG early entropy source...[0m
[0;32mI (320) cpu_start: Pro cpu up.[0m
[0;32mI (324) cpu_start: Starting app cpu, entry point is 0x40080fdc[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (335) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (341) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (347) heap_init: At 3FFB93B0 len 00026C50 (155 KiB): DRAM[0m
[0;32mI (354) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (360) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (366) heap_init: At 40090138 len 0000FEC8 (63 KiB): IRAM[0m
[0;32mI (372) cpu_start: Pro cpu start user code[0m
[0;32mI (167) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (314) camera_demo: Detected OV2640 camera, using JPEG format[0m
[0;32mI (454) camera_demo: ESP_WIFI_MODE_AP[0m
[0;32mI (454) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (454) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (544) phy: phy_version: 3900, 1d94202, May 17 2018, 18:20:07, 0, 0[0m
[0;32mI (554) camera_demo: wifi_init_softap finished.SSID:M5Cam password:[0m
[0;32mI (554) camera_demo: Open http://192.168.4.1/jpg for single image/jpg image[0m
[0;32mI (564) camera_demo: Open http://192.168.4.1/jpg_stream for multipart/x-mixed-replace stream of JPEGs[0m
[0;32mI (574) camera_demo: Free heap: 145312[0m
[0;32mI (574) camera_demo: Camera demo ready[0m

```
here the FW https://github.com/m5stack/esp32-cam-demo
I did not checked yet how to setup as STA

**Comment by luc-github** [comment]
When I tested quality was pretty good

**Comment by ModMike** [comment]
I have 3 on the way, will let you know how it goes when I get them in a month or so.

**Comment by ModMike** [comment]
Bonjour Luc,

I just did a Marlin PR for the Azteeg X5 Mini wifi.  This PR fully supports every feature of the Mini WiFI.  I would like to now migrate to version 2.0 of the Web UI as it seems to offer much improved functionality.

I understand that you said this will be released on their site but I would like to know what needs to be done for this to happen, from the technical to the political.

Merci!

**Comment by luc-github** [comment]
I add to rewrite the 2.0a which was using Async Webserver due to performance issue to be able to use the Sync web server and I never got any feedback until now on 2.0b on esp8266, so I won't release before I got several feedback.
 The only feedback I had were:
1 - on esp32 
2 - on translation on web UI 2.0

2.0c is still under devt and test for both  "public version" and "Azteeg version"

So first need feedback on 2.0c with esp866,  even public one would be great. 

I am currently busy porting 2.0 to Marlin for ESP32 - so every bug I see now are mostly "ESP32 related", they will need to be applied to 2.0, but so far they are small bugs /glitch,  unfortunatly I have only 2 hands and I prefer to finish the ESP3D Marlin porting to apply to "standard" and "Azteeg" version  instead of handle 3 FW at once and so do mistake.

Testing is important, so far Marlin + Direct SD access with 2  SD readers (one on board + one on screen) was never tested so I am not sure of how ESP3D will behave on some corner cases with SD. 
I am still waiting for an Azteeg Wifi board to be able to do test, as the prototype I got, fried after few tests in my desk with 2.0, so I cannot even test your configuration.

What you can ask to Roy from panucatt, is to become a tester, if I agree he may send you the beta FW + web UI files.

**Comment by ModMike** [comment]
Bonjour Luc!

Question stupide, je ne semble pas être capable de charger un fichier, le système me dit toujours qu'il y'a un erreur.  Je suit le protocole de 8.3 mais est ce que il y'a qu'elle que chose de special pour la version 1.0 Azteeg?

Est ce que l'extension doit être .gco?

Merci!

**Comment by luc-github** [comment]
la version 1.0 pour azteeg accède directement au lecteur SD et n'utilise pas le serial
En principe l'upload sur SD ne devrait pas poser de problème car elle ne passe pas par le FW Marlin ou Smoothieware.

qu'elle est l'erreur ?

**Comment by ModMike** [comment]
il me demande de mettre le fichier en forme 8.3, meme quand il est deja.  Maintenant, je ne peut meme pas le sélectionner pour upload.  J'ai meme essayer d'écrire le fichier directement sur la carte.  WEB Ui le voit, mais il ne peut pas l'imprimer.  Quelle est le format et extension?  12345678.GCO?

**Comment by luc-github** [comment]
bizarre oui le format est 12345678.gco 8 + 3, 
Ha ok c'est le formatage qui pose soucis pour les cartes SD il faut ce soft : https://www.sdcard.org/downloads/formatter_4/

c'est la taille de la carte SD esp8266 c'est max 4MB de flash et le SPIFFS est 3MB pour Azteeg

**Comment by ModMike** [comment]
J'ai formatter avec l'outil et j'ai toujours la meme erreur:

![screen shot 2018-08-16 at 10 44 30 am](https://user-images.githubusercontent.com/36581178/44215882-9a642280-a141-11e8-912d-3b15915ce325.png)

[plate123.gco.zip](https://github.com/luc-github/ESP3D/files/2294087/plate123.gco.zip)
![screen shot 2018-08-16 at 10 47 13 am](https://user-images.githubusercontent.com/36581178/44215949-c4b5e000-a141-11e8-839b-a9dd739b6670.png)

**Comment by luc-github** [comment]
plate123.gco.gcode  c'est pas du 8.3 
plate123.gco c'est du 8.3

**Comment by ModMike** [comment]
J'etait sur que j'avais bien changer l'extension.  Quelle idiot!  Mille et une excuse d'avoir gaspiller ton temps sur une connerie.

Maintenant que ca ce régler, peut tu me dire si je peut directement accéder la carte SD avec pour écrire le fichier directement?  Jamais mettre e le path dans le script de Simplify3D.  Genre 192.168.1.xxx/?????

**Comment by luc-github** [comment]
l'upload ne se peut se faire que via l'interface HTML et c'est une requête POST donc Simplify 3D n'y aura pas accès comme ça.
l’idée est inintéressante, il faudrait un protocole webdav je pense, mais la, j'avoue, je ne connais pas trop... désolé,  faudrait faire qq recherches.

**Comment by luc-github** [comment]
après peut etre que faire un uplodeur en ligne de commande qui prend le nom du fichier en paramètre pourrait marcher - je vois peut être un soucis de type `cross origin` mais cela doit être surmontable sans trop de soucis

**Comment by ModMike** [comment]
Je comprends, c'était une fonction sur Octoprint que j'amais beaucoup.

Dernier problème, qu'elle parameter est ce que je doit utiliser pour Azteeg vis a vis la cartes SD?  La fonction imprime ne marche pas.

![screen shot 2018-08-16 at 11 10 58 am](https://user-images.githubusercontent.com/36581178/44217285-190e8f00-a145-11e8-95ee-ca7d8de7d831.png)

**Comment by luc-github** [comment]
ces parametres sont Ok pour Marlin + Azteeg Wifi
Direct SD access : Yes car oui accès direct au SD Reader `Yes` est correct 
Check for Update: c'est pour flasher ESP3D avec le binaire sur la carte SD , pour le moment pas d'update donc pas necessaire `No` c'est Ok
Direct SD boot check : vérifie au démarrage la présence de fichier de mise a jour pour ESP3D soit en activant le lecteur de carte soit en faisant `M20` pour azteeg il faut `No`

Primary SD / Secondary Sd c'est pour un FW smoothieware : donc `None` 'est Ok , de toute façon c'est ignoré pour marlin

**Comment by ModMike** [comment]
Ok, mais j'ai toujours le meme problème.  Je click sur l'icône d'impression et riens ce passe.  Que est ce que j'ai manquer?

J'ai re-demarrer plusieurs fois.

**Comment by luc-github** [comment]
ben plein de chose peuvent se passer en fait - car je n'ai jamais tester ce cas de figure
faudrait se mettre en mode developeur quel est ton browser ?
peux tu faire in [ESP800] dans le terminal du web ui et me mettre ce que cela repond ?

**Comment by ModMike** [comment]
Safari

![screen shot 2018-08-16 at 11 48 59 am](https://user-images.githubusercontent.com/36581178/44219572-66d9c600-a14a-11e8-8377-387876e53c99.png)

**Comment by ModMike** [comment]
Je viens d'essayer Firefox et appart qui sauve les config, ca ne marche pas plus.

**Comment by luc-github** [comment]
Voici comment activer le menu devt

https://support.apple.com/guide/safari/use-the-safari-develop-menu-sfri20948/mac

**Comment by ModMike** [comment]
Luc, excuse moi mais j'avais oublier de te dire que mon menu Develop été activer depuis un ans.

**Comment by luc-github** [comment]
sauve les config ? quelle version du webUI as tu ? c'est dans le menu

**Comment by ModMike** [comment]
![screen shot 2018-08-16 at 12 01 25 pm](https://user-images.githubusercontent.com/36581178/44220285-29763800-a14c-11e8-9da3-720e0fc7a52e.png)

**Comment by luc-github** [comment]
ok regarde si dans le menu developeur s'il y a une erreur détectée , javascript surement

**Comment by luc-github** [comment]
Humm je pense que le soucis est la : https://github.com/luc-github/ESP3D-WEBUI/commit/21cb4bb701afa95e522c5a91d30b9233d0eefc40#diff-4eae35f1b35977a00ebd8086c259d4c9

faudrait mettre le WEBUI a jour : 0.9.80 c'est anterieur a ce fix 
 https://github.com/luc-github/ESP3D-WEBUI/blob/master/index.html.gz

**Comment by luc-github** [comment]
pour Firefox dans le menu dev il faut regarder  le menu console et le menu network 
![image](https://user-images.githubusercontent.com/8822552/44222196-13846980-a184-11e8-97f3-2c84f54ad288.png)
![image](https://user-images.githubusercontent.com/8822552/44222235-331b9200-a184-11e8-9dff-96c6f9c17dd9.png)
M23 cela selectionne le fichier
M24 lance l'impression

**Comment by luc-github** [comment]
il faut verifier que le nom de fichier soit correcte - le soucis doit etre la

**Comment by ModMike** [comment]
Luc, je suis perdu.  J'Aimerais éviter Firefox et rester avec Safari si possible.  Qu'elle et ma prochaine étape?

**Comment by luc-github** [comment]
Il doit y avoir les meme menu dans safari

**Comment by ModMike** [comment]
J'ai essayer M23 et M24 pour voir si Marlin les reconnais, et malheureusement non.  Voice la console:

![screen shot 2018-08-16 at 1 01 44 pm](https://user-images.githubusercontent.com/36581178/44223132-bb823e80-a154-11e8-9325-1d1331a84a6a.png)

**Comment by luc-github** [comment]
Il doit y avoir les meme menu dans safari

**Comment by ModMike** [comment]
Effectivement, regarde mon dernier message.

**Comment by luc-github** [comment]
selectionne la ligne ` command_silent` et la il doit y avoir la possibilitee d'afficher le resume avec la command

**Comment by ModMike** [comment]
Veut tu brancher direct sur mon ordi avec team viewer?

![screen shot 2018-08-16 at 1 18 24 pm](https://user-images.githubusercontent.com/36581178/44223893-eb324600-a156-11e8-9a63-02a822f1ee45.png)

**Comment by ModMike** [comment]
Luc, je pense avoir compris le problème.  JE pense qu'il faut que je "ENABLE_SDCARD" dans Marlin.  Autrement la commande et ignorer.

J'essaye et je te revient sous peut.

**Comment by luc-github** [comment]
bon la bonne nouvelle est que la ligne de commande est correct  donc mon code est Ok ^_^

mais apparement elle est sans effet 
en principe 
M23 /plate123.gco
puis M24 
devrait lancer l'impression si cela ne fait rien c'est que qqchose a changer dans Marlin 2.0
si tu lances les commandes dans le terminal ca renvoit une erreur ?

**Comment by luc-github** [comment]
je viens de faire le test sur mon ESP32 avec marlin 2.0 et ca a l'air de marcher de mon cote

**Comment by ModMike** [comment]
Ok j'ai changer le config.h et maintenant il reconnais les commandes mais ne commence toujours pas.  Peut tu afficher to configuration.h?

**Comment by ModMike** [comment]
Je pense le problème et que Marlin ne vois pas la carte.  J'utilise un Ender 3 avec le X5 Mini Wifi donc la seul place pur une carte SD et dans le X5.  Il me semble que le problème et que marlin doit reconnaître la carte pour voir le fichier.  A tu une idée comment je peut faire?  J'a l'impression quoi et reste que arriver.

**Comment by luc-github** [comment]
il faut activer #define SDSUPPORT
sans ca c'est sur pas de carte SD 
de plus il faut etre sure que la carte soit montee - avec le SD detect c'est automatique mais si ce n'est pas configurer il faut faire un M21 pour 'monter' la carte
et tu as : 
`echo:SD card ok`
apres fait un `M20`

**Comment by ModMike** [comment]
Luc,

Le problème et que J'ai definer le port série -1 (pour USB) et 1 (pour web UI) .  Je pense qu'il y'a un conflit de port série.  Peut tu partager to config.h de marlin et aussi me dire si tu fonctionne sur un board 32 bit avec seulement une carte sd?

**Comment by luc-github** [comment]
moi sur mon ESP32 j'ai : `#define SERIAL_PORT 0`
pour toi cela devrait être
```
#define SERIAL_PORT -1
#define SERIAL_PORT_2 0
 ```

enfin je pense

**Comment by luc-github** [comment]
et oui je n'ai qu'un lecteur SD connecté à mon ESP32

**Comment by ModMike** [comment]
Ce comme ca que je les ai configurer.  Je pense avoir trouver le problème dans la board.pins que jai créer mais j'ai besoin une information pour corriger.

Peut tu me dire qu'elle board 32 bit t'utilise?

Spécifiquement, essaye de definer #define SDSS mais je n'ai pas la bonne pin:.

"The sdcard on the controller shares the spi port that the onboard sdcard uses"

**Comment by ModMike** [comment]
Qu'elle coincidence, je m'en aller ouvrir le meme fichier!  Est ce que le tiens et Enabled?

**Comment by luc-github** [comment]
je n'utilise pas de LPC1768  mais une ESP32 ^_^ 

j'ai une re-arm qq part mais il faut que je remette la main dessus

**Comment by ModMike** [comment]
Je pense que les liens que tu ma donner et vieux, voici la branche officiel:

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_LPC1768/spi_pins.h

**Comment by luc-github** [comment]
le contenu est le meme ^_^
remplace le valeur actives par celle de la onboard et laisse le SDSS en auto define comme decrit

**Comment by ModMike** [comment]
Je ne comprend pas, qu'elle valeur active?

J'avais aussi défini un CR-10 stock display et je pense que ca cause un "bypass" du code.  Voici la portion LCD de mon pins file:

`//
// Display
//
#if ENABLED(ULTRA_LCD)

  #if ENABLED(CR10_STOCKDISPLAY)

    // Re-Arm can support Creality stock display without SD card reader and single cable on EXP3.
    // Re-Arm J3 pins 1 (p1.31) & 2 (P3.26) are not used. Stock cable will need to have one
    // 10-pin IDC connector trimmed or replaced with a 12-pin IDC connector to fit J3.
    // Requires REVERSE_ENCODER_DIRECTION in Configuration.h

    #define BEEPER_PIN          P2_11   // J3-3 & AUX-4

    #define BTN_EN1             P0_16   // J3-7 & AUX-4
    #define BTN_EN2             P1_23   // J3-5 & AUX-4
    #define BTN_ENC             P3_25   // J3-4 & AUX-4

    #define LCD_PINS_RS         P0_15   // J3-9 & AUX-4 (CS)
    #define LCD_PINS_ENABLE     P0_18   // J3-10 & AUX-3 (SID, MOSI)
    #define LCD_PINS_D4         P2_06   // J3-8 & AUX-3 (SCK, CLK)

  #else

    #define BEEPER_PIN          P1_30   // (37) not 5V tolerant

    #define BTN_EN1             P3_26   // (31) J3-2 & AUX-4
    #define BTN_EN2             P3_25   // (33) J3-4 & AUX-4
    #define BTN_ENC             P2_11   // (35) J3-3 & AUX-4

    #define SD_DETECT_PIN       P1_31   // (49) not 5V tolerant   J3-1 & AUX-3
    #define KILL_PIN            P1_22   // (41) J5-4 & AUX-4
    #define LCD_PINS_RS         P0_16   // (16) J3-7 & AUX-4
    #define LCD_SDSS            P0_16   // (16) J3-7 & AUX-4
    #define LCD_BACKLIGHT_PIN   P0_16   // (16) J3-7 & AUX-4 - only used on DOGLCD controllers
    #define LCD_PINS_ENABLE     P0_18   // (51) (MOSI) J3-10 & AUX-3
    #define LCD_PINS_D4         P0_15   // (52) (SCK)  J3-9 & AUX-3

    #define DOGLCD_A0           P2_06   // (59) J3-8 & AUX-2
    #define DOGLCD_CS           P0_26   // (63) J5-3 & AUX-2

    #ifdef ULTIPANEL
      #define LCD_PINS_D5       P1_17   // (71) ENET_MDIO
      #define LCD_PINS_D6       P1_14   // (73) ENET_RX_ER
      #define LCD_PINS_D7       P1_10   // (75) ENET_RXD1
    #endif

    #if ENABLED(NEWPANEL)
      #if ENABLED(REPRAPWORLD_KEYPAD)
        #define SHIFT_OUT         P0_18   // (51)  (MOSI) J3-10 & AUX-3
        #define SHIFT_CLK         P0_15   // (52)  (SCK)  J3-9 & AUX-3
        #define SHIFT_LD          P1_31   // (49)  not 5V tolerant   J3-1 & AUX-3
      #endif
    #else
      //#define SHIFT_CLK           P3_26   // (31)  J3-2 & AUX-4
      //#define SHIFT_LD            P3_25   // (33)  J3-4 & AUX-4
      //#define SHIFT_OUT           P2_11   // (35)  J3-3 & AUX-4
      //#define SHIFT_EN            P1_22   // (41)  J5-4 & AUX-4
    #endif

    #if ENABLED(VIKI2) || ENABLED(miniVIKI)
      // #define LCD_SCREEN_ROT_180

      #undef  BEEPER_PIN
      #define BEEPER_PIN          P1_30   // (37) may change if cable changes

      #define BTN_EN1             P3_26   // (31) J3-2 & AUX-4
      #define BTN_EN2             P3_25   // (33) J3-4 & AUX-4
      #define BTN_ENC             P2_11   // (35) J3-3 & AUX-4

      #define SD_DETECT_PIN       P1_31   // (49) not 5V tolerant   J3-1 & AUX-3
      #define KILL_PIN            P1_22   // (41) J5-4 & AUX-4

      #undef  DOGLCD_CS
      #define DOGLCD_CS           P0_16   // (16)
      #undef  LCD_BACKLIGHT_PIN   //P0_16   // (16) J3-7 & AUX-4 - only used on DOGLCD controllers
      #undef  LCD_PINS_ENABLE     //P0_18   // (51) (MOSI) J3-10 & AUX-3
      #undef  LCD_PINS_D4         //P0_15   // (52) (SCK)  J3-9 & AUX-3

      #undef  LCD_PINS_D5         //P2_06   // (59) J3-8 & AUX-2
      #define DOGLCD_A0           P2_06   // (59) J3-8 & AUX-2
      #undef  LCD_PINS_D6         //P0_26   // (63) J5-3 & AUX-2
      #undef  LCD_PINS_D7         //P1_21   // ( 6) (SERVO1) J5-1 & SERVO connector
      #define DOGLCD_SCK          SCK_PIN
      #define DOGLCD_MOSI         MOSI_PIN

      #define STAT_LED_BLUE_PIN   P0_26   // (63)  may change if cable changes
      #define STAT_LED_RED_PIN    P1_21   // ( 6)  may change if cable changes
    #endif

    //#define MISO_PIN            P0_17   // (50)  system defined J3-10 & AUX-3
    //#define MOSI_PIN            P0_18   // (51)  system defined J3-10 & AUX-3
    //#define SCK_PIN             P0_15   // (52)  system defined J3-9 & AUX-3
    //#define SS_PIN              P1_23   // (53)  system defined J3-5 & AUX-3 - sometimes called SDSS

    #if ENABLED(MINIPANEL)
      // GLCD features
      //#define LCD_CONTRAST   190
      // Uncomment screen orientation
      //#define LCD_SCREEN_ROT_90
      //#define LCD_SCREEN_ROT_180
      //#define LCD_SCREEN_ROT_270
    #endif

  #endif

#endif // ULTRA_LCD`

Est ce que je doit redéfinir DOG LCD dans ma section CR-10?

**Comment by ModMike** [comment]
Merde:

"The onboard card is currently reserved for eeprom (although the new flash based system will more then likely be changed to the default) and the usb drive. Marlin has no access to it.

It's on the todo list with the new framework."

**Comment by luc-github** [comment]
ben voila - il te faut soit brancher un ecran avec SD soit juste un lecteur SD comme je fais pour mon ESP32

**Comment by ModMike** [comment]
Excuse moi mais ca ce chient de leur part.  Merci pour ton aide!

**Comment by luc-github** [comment]
prend un lecteur avec Detection d'insertion tant qu'a faire il y en a sur aliexpress

**Comment by luc-github** [comment]
Pas de soucis ^_^ mon code est bon c'est un bon point :wink:

**Comment by ModMike** [comment]
Ce n’ai pas un option pour plusieurs raison.  Le point du projet était de configurer les imprimante Creality avec Marlin sur le Mini Wifi.  Ce n’était pas un projet personnel.

**Comment by luc-github** [comment]
tu bosses pour creality ?
as tu essaye de : 
1 - desactiver l'EEPROM dans Marlin ? j'ai vu pas mal de mise a jour passer pour ca ces derniers jours
2 - puisque La carte SD ne sert plus d'EEPROM
change 
```
/** onboard SD card */
//#define SCK_PIN           P0_07
//#define MISO_PIN          P0_08
//#define MOSI_PIN          P0_09
//#define SS_PIN            P0_06
/** external */
#ifndef SCK_PIN
  #define SCK_PIN           P0_07 
#endif
#ifndef MISO_PIN
  #define MISO_PIN          P0_08
#endif
#ifndef MOSI_PIN
  #define MOSI_PIN          P0_09
#endif
#ifndef SS_PIN
  #define SS_PIN            P0_06
#endif
#ifndef SDSS
  #define SDSS              SS_PIN
#endif
```
cela ne coute rien d'essayer

**Comment by ModMike** [comment]
Non, j'essaye d'aider Roy a Panucatt. 

Pour bien comprendre, j'ai juste a désactiver EEProm?

**Comment by ModMike** [comment]
Tu parel tu du persistentStore qui a été ajouter il ya quelle que jour?

Michael Triffon
514-927-6459

**Comment by ModMike** [comment]
Tu parel tu du persistentStore.api qu'il a été ajouter y'a qu'elle que jour?

**Comment by luc-github** [comment]
Ok looking at marlin issues list this can be closed

**Comment by ModMike** [comment]
No secret, made a new pin file. You will find it in Marlin 2.0.x bug fix version of the ramps re-arm pins file.

You also need to make sure you plug the cable the right way or you will blow the display.

At a clients, can help you tomorrow morning first thing if you need.

MT

**Comment by ModMike** [comment]
@TwatBurglar Did you get it working?  I am available now if you have questions.

**Comment by TwatBurglar** [comment]
@ModMike  yes, working now, thanks.    Issue was I had the ribbon cable plugged into little daughterboard perched atop RAMPs board....  but this is not how the new pins.h file is config'd  :(  

Once I plugged it directly into rearm's J3  (manhandling the two superflous pins out of the way), it worked.   
Obviously the wrong thread, but I'll post anyway; hopefully someone else won't spend 4 hours diddling...
keywords:  Rearm re-arm CR10_STOCKDISPLAY not working
![bah](https://user-images.githubusercontent.com/15265789/46361752-6931aa00-c63c-11e8-980e-03c59e412f4a.png)

**Comment by ModMike** [comment]
Actually that's exactly how it works and the pins are correct in my rearm config.  Did you define the board as RAMPS_RE_ARM in config.h?

I dremmeled off the right edge of the connector so it would fit.  Best option is to get an * pin connector and assemble with original cable shifted left.

**Comment by ModMike** [comment]
Here are the pin assignments form the pins file in case you used something else:

 #if ENABLED(CR10_STOCKDISPLAY)

    // Re-Arm can support Creality stock display without SD card reader and single cable on EXP3.
    // Re-Arm J3 pins 1 (p1.31) & 2 (P3.26) are not used. Stock cable will need to have one
    // 10-pin IDC connector trimmed or replaced with a 12-pin IDC connector to fit J3.
    // Requires REVERSE_ENCODER_DIRECTION in Configuration.h

    #define BEEPER_PIN          P2_11   // J3-3 & AUX-4

    #define BTN_EN1             P0_16   // J3-7 & AUX-4
    #define BTN_EN2             P1_23   // J3-5 & AUX-4
    #define BTN_ENC             P3_25   // J3-4 & AUX-4

    #define LCD_PINS_RS         P0_15   // J3-9 & AUX-4 (CS)
    #define LCD_PINS_ENABLE     P0_18   // J3-10 & AUX-3 (SID, MOSI)
    #define LCD_PINS_D4         P2_06   // J3-8 & AUX-3 (SCK, CLK)
