### ISSUE TITLE
Platform IO

### ISSUE THREAD

**Issue by ModMike** [luc-github/ESP3D#247]
Is anyone using Platform IO to compile?  Would love to leave Arduino IDE completely behind.

**Comment by luc-github** [comment]
Did you succeed ?

**Comment by ModMike** [comment]
I got it all setup but I didn't pursue, seeing as i had the tool chain setup.  I will try again next week and update you.

**Comment by ModMike** [comment]
Hi Luc,

You need to enable the framework, which is pretty easy:

![screen shot 2018-09-08 at 4 25 58 pm](https://user-images.githubusercontent.com/36581178/45258347-f65a4980-b383-11e8-859d-52618c4c4506.png)

Then pick board:

![screen shot 2018-09-08 at 4 25 29 pm](https://user-images.githubusercontent.com/36581178/45258354-feb28480-b383-11e8-99c9-e466d6221247.png)

After that you can create new project for home screen:

![screen shot 2018-09-08 at 4 27 36 pm](https://user-images.githubusercontent.com/36581178/45258369-1e49ad00-b384-11e8-99c4-31650ec363d6.png)

That will get you going.

**Comment by ModMike** [comment]
Edited comments to keep it concise.

**Comment by luc-github** [comment]
Thanks for sharing  ^_^

**Comment by luc-github** [comment]
I have labeled as FAQ - so issue can be closed - thank you
