### ISSUE TITLE
Socat connection

### ISSUE THREAD

**Issue by Zefram88** [luc-github/ESP3D#248]
As title, i'm asking if it is possible to create a virtual tcp-to-com connection using socat or something similar. This is beacuse i'm using OSX and repetier version is really outdated, so i can't take advantages from network connections.

Thanks

**Comment by Zefram88** [comment]
UPDATE:
I'm able to successfully open a connection through this command:

`socat -d -d pty,raw,echo=0,wait-slave, tcp:[IP_ADDRESS]:[PORT]`

Now the problem is how to select the interface from the slicer (Cura, Repetier etc..)

**Comment by luc-github** [comment]
you may need to set a Serial port in command like : `PTY,link=/tmp/ttyS0`

**Comment by Zefram88** [comment]
With the command `socat -d -d pty,raw,echo=0,link=/tmp/ESP,wait-slave, tcp:[IP_ADDRESS]:[PORT]` work but only on Proterface because you can set every address you want. The problem is on Repetier host/Cura because you are not able to select the interface manually and it is not auto-detected.

The connection itself works just fine

**Comment by luc-github** [comment]
@Zefram88 did you solved your issue ?
In repetier host you should be able to  select TCP connection and enter IP/port

**Comment by Zefram88** [comment]
> @Zefram88 did you solved your issue ?
> In repetier host you should be able to select TCP connection and enter IP/port

Well, yes and no.
Basically the problem is not of ESP-3D itslef i suppose. I can't use repetier beacuse i own a macbook, the repetier version is outdated and doesn't have the IP connection function.
Cura also doesn't detect the connection.
I'm able to use it only on Proterface

The best would be to make ESP3D "findable" by Cura

**Comment by luc-github** [comment]
I guess issue can be closed then
