### ISSUE TITLE
ESP3D V2.0 Wifi disconnect 

### ISSUE THREAD

**Issue by shaddow501** [luc-github/ESP3D#252]
Dear Luc

I have a strange operation with the version 2.0, it seems that after a hour or so the Wifi is disconnected and on the OLED display I see that the unit have been disconnected and the only way to reconnect is to disconnect from the power source and reconnect the power source. (or resetting the module)

**Comment by luc-github** [comment]
do you latest Git Update of ESP32 core ? I remember there was some fix a for disconnection and auto reconnect a while ago but I see still an old open issue : https://github.com/espressif/arduino-esp32/issues/653

ESP3D do not do anything actually for auto reconnect, it rely on ESP32 to autoreconect - but notice the disconnection. That part is definitly area of improvement but I never had issue my ESP32 run 24h a day

**Comment by shaddow501** [comment]
I have updated the git about a week ago.. 
Is it possible when the ESP3D notice the disconnection to retry to reconnect?

**Comment by luc-github** [comment]
Yes that is why I introduced the wifi event in 2.0 to improve that part
you can try to add a simple `WiFi.begin();` in Disconnect event to see if it solve your issue

**Comment by luc-github** [comment]
also ESP32-ARDUINO had new idf update 2 days ago that solve lot of issues

**Comment by shaddow501** [comment]
Dear Luc

I have discovered that the module just freeze after a few min of operation. and that causes the disconnection..

**Comment by luc-github** [comment]
Do you have NetBIOS enabled ?
If yes disable it to see if it stop the freeze - I saw some freeze with ESP32 NetBIOS

**Comment by shaddow501** [comment]
Disabled it and now checking, by the way sometimes on the OLED the IP does not show after connection, but I see in the the serial terminal that it did get IP.

**Comment by luc-github** [comment]
well Serial and Oled are called in same time:
```
		case WIFI_EVENT_STAMODE_GOT_IP:
			ESPCOM::println (WiFi.localIP().toString().c_str(), PRINTER_PIPE);
#ifdef ESP_OLED_FEATURE
			OLED_DISPLAY::setCursor(0, 16);
			ESPCOM::print(WiFi.localIP().toString().c_str(), OLED_PIPE);
			OLED_DISPLAY::setCursor(0, 48);
			ESPCOM::print("", OLED_PIPE);
#endif
```

**Comment by shaddow501** [comment]
Yes, that is why it is strange why it doesnt update the OLED...

**Comment by luc-github** [comment]
need to add a log to check if Info reach function :
```
#ifdef ESP_OLED_FEATURE
    case OLED_PIPE:
		{
		if (!ESPCOM::block_2_oled) {
               //Add log here
			if(!(!strcmp(data,"\n")||!strcmp(data,"\r")||!strcmp(data,"\r\n"))) {
				OLED_DISPLAY::print(data);
				OLED_DISPLAY::update_lcd();	
				}
			}
        }
        break;
#endif
```
if function is reached - then check the OLED functions - may be need time between print and update if OLED is slow

**Comment by shaddow501** [comment]
Can you say where I should put those lines? (in which file?)

**Comment by luc-github** [comment]
espcom.cpp - the log depend of your choice

**Comment by shaddow501** [comment]
It seems that disabling the NetBios fixed all those issues... also fixed the display IP address issue.
I guess case closed. :)

**Comment by luc-github** [comment]
Ho really ?
I reported the NetBIOS  issue long time ago - and reported again with latest IDF update it happen with Webserver + Netbios only  - hope it will be fixed

**Comment by shaddow501** [comment]
Well the module doesnt crash, I dont have wifi disconnection anymore and the OLED display the IP with each reset.
Now I will continue testing it before I install it on my printer.

**Comment by shaddow501** [comment]
Dear Luc
For the version 2.0 you need to use Web-Gui of 2x. 
In this version I dont see the Webcam option and I dont have the print configuration setting...
Have you noticed that?

**Comment by luc-github** [comment]
you have a menu preferences all is there

**Comment by shaddow501** [comment]
Yes, thanks found that, but I the page under printer configuration  - ESP3D for Repetier for Davinci
 there is only refresh button and - 

Label | Value | Help
-- | -- | --

and that is all.

is it suppose to be like that?

**Comment by luc-github** [comment]
When you refresh you do not have EEPROM content ?

**Comment by shaddow501** [comment]
I dont know what you mean but this is what I get.
![image](https://user-images.githubusercontent.com/21113491/46016882-b19e1480-c0de-11e8-943a-0680ae51c32d.png)

**Comment by shaddow501** [comment]
This window is shown for marlin, but it show the same page also for Repetier for Davinci

My printer is Anycubic I3 Mega

**Comment by luc-github** [comment]
Which FW your printer use ?

**Comment by shaddow501** [comment]
In Repetier I select Marlin

**Comment by luc-github** [comment]
.....
What is the output of command M115 ?

**Comment by luc-github** [comment]
So it is not Marlin FW Neither Repetier FW 

Marlin use M503 command to display configuration
Repetier use M205 command to display configuration

You tried both and none fit what ESP3D expect, so you cannot edit FW settings in ESP3D

**Comment by shaddow501** [comment]
Dear Luc
As I said the ESP3D is not connected to the printer yet, I run all those test as stand alone.
So maybe it need to be connected to the serial port.

**Comment by luc-github** [comment]
I see you edited and now have  FIRMWARE_NAME:Marlin 1.1.0-RC8 
man it is really painful to debug with you

**Comment by shaddow501** [comment]
I guess we both got confused, I didnt know that it is a firmware setting page and the printer has to be connected, It wasnt clear what is this page for... and when looking at the pictures you added in the install page I was thinking that it is something that related to the ESP3D printer settings. Not actual the printer firmware...

**Comment by luc-github** [comment]
In Marlin there is :
`#define DISABLE_M503  `
usualy it is commented but if not commented the command won't work and so the editor feature

**Comment by shaddow501** [comment]
maybe it was more clear if instead "Printer configuration" it should be "Printer Firmware Settings"

about the #define DISABLE_M503 it is not commented out since when I run it in the Repetier host I get:
Steps per unit:
M92 X80.00 Y80.00 Z400.00 E92.60
Maximum feedrates (mm/s):
M203 X500.00 Y500.00 Z6.00 E60.00
Maximum Acceleration (mm/s2):
M201 X3000 Y2000 Z60 E10000
Accelerations: P=printing, R=retract and T=travel
M204 P3000.00 R3000.00 T3000.00
Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s), Z=maximum Z jerk (mm/s), E=maximum E jerk (mm/s)
M205 S0.00 T0.00 B20000 X10.00 Y10.00 Z0.40 E5.00
Home offset (mm)
M206 X0.00 Y0.00 Z0.00
Z2 Endstop adjustment (mm):
M666 Z0.00
Material heatup parameters:
M145 S0 H180 B70 F0
M145 S1 H240 B110 F0
PID settings:
M301 P16.43 I1.04 D61.37
Filament settings: Disabled
M200 D1.75
M200 D0

**Comment by luc-github** [comment]
for ESP3D settings there is a tab already:
![image](https://user-images.githubusercontent.com/8822552/46033267-1157e800-c0fe-11e8-81b8-6fac7147d6df.png)

Printer Settings is for Printer

**Comment by shaddow501** [comment]
Well, if I did not understand that it is not related to the ESP3D settings but was related directly to the printer firmware I guess that there might be more that will do that mistake...

**Comment by luc-github** [comment]
There will be always people who do not understand what ever it is writen - cannot have 100% success this is life.

Even  the  read me describe each part : https://github.com/luc-github/ESP3D-WEBUI  
 I know screen shots are not updated yet for 2.0 but no one read the read me.... so if at the end always have questions I do when I have time

**Comment by shaddow501** [comment]
Cool thanks

**Comment by luc-github** [comment]
I guess issue can be closed
