### ISSUE TITLE
8.3 Format for Marlin

### ISSUE THREAD

**Issue by ghost** [luc-github/ESP3D#265]
Yesterday I went to the devs of marlin and asked them to change up 8.3 filename and they said to 

> "take it up with the developer of esp3d"

I kindly told them that already have but they closed the topic.

You try and fix it when you can. I can contribute if needed.

Bailey.

p.s i tried the wireless printing for cura topic but he doesn't support windows and doesn't want to.

**Comment by luc-github** [comment]
What channel did you used  to communicate with Marlin devs? I see you did not used github tracker
I am curious to know  what they say to reject

**Comment by luc-github** [comment]
Close issue as user no more exists
