### ISSUE TITLE
Settings do not change when pressing SET button

### ISSUE THREAD

**Issue by ClumsyPenguin** [luc-github/ESP3D#266]
the setting won't change regardless what i do. I setted the ESP in station made but it stays in AP mode.

**Comment by luc-github** [comment]
For some settings like WiFi mode you need to restart ESP - I am working on "hot" changes for WiFi but it is not ready yet

**Comment by luc-github** [comment]
do you confirm restarting your ESP apply settings ?

**Comment by luc-github** [comment]
I guess yes as no answer
