### ISSUE TITLE
Feature request: switch ON/OFF

### ISSUE THREAD

**Issue by axl12ap** [luc-github/ESP3D#268]
Good afternoon,
I'm new to Esp3D (just flashed on my device Wemon D1 miniPro) and I like it for WebServer side also... thank you for your work.

I would like to have a feature like a graphical button on the web server that can switch a generic output (ON/OFF) and command a relay for switching on a PSU of a printer.

I do not want to use the PS_ON pin of a RAMPS because I would like to have the ESP3D always on (powered separately), and to turn on the PSU (and therefore the Ramps) only on command.

Thanks

**Comment by luc-github** [comment]
use the macro of the WEB-UI and the command ESP201  

*Get/Set pin value
[ESP201]P<pin> V<value> [PULLUP=YES RAW=YES]pwd=<admin password>
if no V<value> get P<pin> value
if V<value> 0/1 set INPUT_PULLUP value, but for GPIO16 INPUT_PULLDOWN_16
GPIO1 and GPIO3 cannot be used as they are used for serial
if PULLUP=YES set input pull up, if not set input
if RAW=YES do not set pinmode just read value

**Comment by axl12ap** [comment]
![image](https://user-images.githubusercontent.com/31867260/47025442-c6148080-d163-11e8-8094-d18012bb9299.png)

There're a lot of digital pins to use...
I'll try next evening on my Wemos :+1: 

Thanks

**Comment by LL1r1k** [comment]
ried to do it but i could not. I have NodeMCU and separately powered printer and ESP. RX ESP -> TX MKS gen L, TX ESP -> RX MKS gen L< GND ESP -> GND MKS gen L. When i try to turn on the power of ESP, it doesn't start (in the normal state, the LED flashes once), if I press the RESTART button, the LED will blink and everything will turn on. Can u help me.
