### ISSUE TITLE
Esp3D 2.0x power on fail on some hardware conditions

### ISSUE THREAD

**Issue by axl12ap** [luc-github/ESP3D#272]
Hello,
I've a Wemos D1 mini pro, and I made this hardware connection:
Tx Wemos    <---> Rx2 Arduino2
Rx Wemos    <---> Tx2 Arduino2
Gnd Wemos <---> Gnd Arduino2

To power Wemos D1 I use the USB connector, or 5V.

Bug: when I power on the Wemos, and leave the Arduino2 off, Wemos doesn't start and I can't find any access point. Instead, when I power on both Wemos and Arduino2, I can see the AP correctly after some seconds.

If I power the Wemos without the TX/RX/GND signals connected I can see the AP also.

What's the matter? 
Maybe Rx Wemos signal is locked from Tx2 Arduino when power off?
In that the case, does the Esp3D firmware can be corrected?

**Comment by luc-github** [comment]
Do you have same behavior with AP sample code from ESP8266 core ?

**Comment by axl12ap** [comment]
I didn't try.. only with your firmware, then come back to normal configuration (3v3 and gnd connected from Arduino2), power on togheter.

**Comment by axl12ap** [comment]
I'm thinking to put an octal tri-state LV buffer on both TX and RX, and enable when powering Arduino2.

**Comment by luc-github** [comment]
any update ?

**Comment by luc-github** [comment]
I think issue can be closed
