### ISSUE TITLE
ESP3D v2.0 after changing web port, it will stuck at the connecting page and please wait forever.

### ISSUE THREAD

**Issue by TheFlash12314** [luc-github/ESP3D#277]
In the version 1, this problem does not occur.

**Comment by luc-github** [comment]
reproduced and fixed - it is a bug of WebUI and syncwebserver  websocket -  good catch
you can use http://192.168.1.18:82/?forcefallback=yes to upload latest ESP3D-WEBUI 2.0 or 2.1

**Comment by TheFlash12314** [comment]
After update, some of the setting boxes becomes small and blank

**Comment by TheFlash12314** [comment]
![screenshot 279](https://user-images.githubusercontent.com/36818971/49214158-ff960800-f400-11e8-9455-4c08eb33f22f.png)

**Comment by luc-github** [comment]
what web-ui version do you use ? what is your browser and OS ?

**Comment by TheFlash12314** [comment]
the latest web ui v2.0 chrome and firefox all same

**Comment by TheFlash12314** [comment]
windows8.1

**Comment by luc-github** [comment]
I do not have windows 8.1 ...

can you try the web-ui 2.1 ? It should be fixed on it 
once done go to preferences and uncheck connection monitoring or you will be disconnected after 20s
![image](https://user-images.githubusercontent.com/8822552/49215756-cbebbb80-f3c9-11e8-8e23-526b4827c8ab.png)

**Comment by TheFlash12314** [comment]
the version v2.1 is working. thanks
