### ISSUE TITLE
Error For missing Function definition when  #define DEBUG_ESP3D  is enabled

### ISSUE THREAD

**Issue by MirkoUgoliniDev** [luc-github/ESP3D#282]
Hello Luc

I tried to uncomment debug line #define DEBUG_ESP3D , but I get the same type of error both on version1 and on version2:

**'LOG' was not declared in this scope**

what's wrong?

Regards Mirko

**Comment by MirkoUgoliniDev** [comment]
Silly  question :(

#define DEBUG_ESP3D
//#define DEBUG_OUTPUT_SPIFFS
#define DEBUG_OUTPUT_SERIAL
//#define DEBUG_OUTPUT_TCP

solved

**Comment by luc-github** [comment]
I agree I could be confusing - on 3.0 there will be only one define

**Comment by luc-github** [comment]
I guess issue can be closed
