### ISSUE TITLE
Webcam Future

### ISSUE THREAD

**Issue by mralperem** [luc-github/ESP3D#283]
Hello can someone please explain me how to connect my camera to ESP8266

**Comment by luc-github** [comment]
You already asked question here : https://github.com/luc-github/ESP3D-WEBUI/issues/43
and currently there is no direct connection support for camera in ESP3D only IP using WebUI

**Comment by luc-github** [comment]
Also ESP8266 is not great candidat for direct connection - have a look to ESP32 instead

**Comment by mralperem** [comment]
Yes you are right I am sorry to ask it here also I just mixed up the links.I couldnt find the other link to reply. What I actually wanted to ask is that if it is possible to directly connect camera to ESP32 or ESP8266. Because of the price tag of IP cameras

**Comment by luc-github** [comment]
have several using google you will find them average price is 10$ which is a price of cheap IP cam:
https://www.aliexpress.com/item/ESP32-CAM-WiFi-Bluetooth-module-ESP32-serial-to-WiFi-with-camera-module-ESP32-CAM-development-board/32931586411.html
https://www.aliexpress.com/item/ESP32-CAM-ESP32CAM-Module-OV2640-Camera/32956799822.html

**Comment by mralperem** [comment]
I understand I will try the both options. Thank you for your reply. Really appreciated for the great work

**Comment by fred2088** [comment]
will this esp32-cam work as ip-cam and usable by ESP3D ?

> have several, using google you will find them, average price is 10$ which is a price of cheap IP cam:
> https://www.aliexpress.com/item/ESP32-CAM-WiFi-Bluetooth-module-ESP32-serial-to-WiFi-with-camera-module-ESP32-CAM-development-board/32931586411.html
> https://www.aliexpress.com/item/ESP32-CAM-ESP32CAM-Module-OV2640-Camera/32956799822.html

**Comment by luc-github** [comment]
in theory yes = they are IP cam that can be seen in browser so they meet the requirement

**Comment by luc-github** [comment]
Need to try but video use a lot of power. Not sure can do video and handle ESP3D feature at once.
