### ISSUE TITLE
How to install on esp32

### ISSUE THREAD

**Issue by delchrys** [luc-github/ESP3D#285]
HI,

i love this project but i cant seem to understand what i exactly need to do to upload esp3d to my ESP32.
i Have installed arduino
i have installed the board and tested it with a Wifiscan sketch. that works
But now i have to figure out how to upload ESSP3d sketch to my ESP32.
Cant seem to figure out where to place the folders/libraries and which package i need to download. (ESP3d or V2).

Can someone write some small steps please.
I have arduino experience but no ESP32 experience yet and cant figure it out.

Kind regards,

Bert

**Comment by luc-github** [comment]
For esp32 use 2.0 branch is better.
Read the readme of 2.0 branch it describe what need to do

**Comment by delchrys** [comment]
i tried but i just cant figure it out.
opened the example ino file in arduino but it doesnt compile

**Comment by delchrys** [comment]
C:\Users\bertb\AppData\Local\Temp\arduino_build_893025\sketch\basicesp3d.ino.cpp.o:(.literal._Z5setupv+0x8): undefined reference to `Esp3D::begin(unsigned short, unsigned short)'

C:\Users\bertb\AppData\Local\Temp\arduino_build_893025\sketch\basicesp3d.ino.cpp.o:(.literal._Z4loopv+0x0): undefined reference to `Esp3D::process()'

C:\Users\bertb\AppData\Local\Temp\arduino_build_893025\sketch\basicesp3d.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_myesp3d+0x4): undefined reference to `Esp3D::Esp3D()'

C:\Users\bertb\AppData\Local\Temp\arduino_build_893025\sketch\basicesp3d.ino.cpp.o: In function `setup()':

C:\Users\bertb\Downloads\ESP3D-2.0\ESP3D-2.0\examples\basicesp3d/basicesp3d.ino:29: undefined reference to `Esp3D::begin(unsigned short, unsigned short)'

C:\Users\bertb\AppData\Local\Temp\arduino_build_893025\sketch\basicesp3d.ino.cpp.o: In function `loop()':

C:\Users\bertb\Downloads\ESP3D-2.0\ESP3D-2.0\examples\basicesp3d/basicesp3d.ino:35: undefined reference to `Esp3D::process()'

C:\Users\bertb\AppData\Local\Temp\arduino_build_893025\sketch\basicesp3d.ino.cpp.o: In function `_GLOBAL__sub_I_myesp3d':

C:\Users\bertb\Downloads\ESP3D-2.0\ESP3D-2.0\examples\basicesp3d/basicesp3d.ino:24: undefined reference to `Esp3D::Esp3D()'

collect2.exe: error: ld returned 1 exit status

exit status 1
Fout bij het compileren voor board DOIT ESP32 DEVKIT V1

**Comment by delchrys** [comment]
the libraries i have to copy to my library directory of arduino.
where do i place the src folder???

**Comment by delchrys** [comment]
what first bullet?

**Comment by luc-github** [comment]
First bullet of installation process in readme

**Comment by delchrys** [comment]
Please follow installation of the ESP core you want to use : ESP8266 core version or ESP32 core version

**Comment by delchrys** [comment]
never mind, i give up. Going for a Raspi

**Comment by luc-github** [comment]
This is first line,  bullet is point after
* this is bullet

**Comment by delchrys** [comment]
DNSServer (from https://github.com/bbx10/DNSServer_tng)

**Comment by delchrys** [comment]
those arent added in the git?

**Comment by luc-github** [comment]
That is why I ask you , you do not read 2.0 branch read me but master one

**Comment by luc-github** [comment]
The 2.0 branch read me explain better for esp32 and esp3d library

**Comment by delchrys** [comment]
ESP3D because it is now a library so copy project to your arduino library folder.

**Comment by delchrys** [comment]
so now i copied the library folders to my library folder in C:\program files\arduino\libraries.

**Comment by luc-github** [comment]
Yes this is the correct read me, esp3d is a library so copy it in library folder

**Comment by delchrys** [comment]
and now i open????:::::???

**Comment by luc-github** [comment]
No library folder is in my document/Arduino/libraries on windows

**Comment by delchrys** [comment]
yeah sorry i meat that folder....now what?? i need to open a *.ino file toupload??

**Comment by luc-github** [comment]
Yes everything is explained in readme
You can also check the travis.yml script which build everything the path are under linux but it is easy to understand all actions

**Comment by delchrys** [comment]
readme is a bit difficult for a noob..lol
do i need to upload all files and folders manually????

**Comment by luc-github** [comment]
You just need index.html.gz

**Comment by delchrys** [comment]
thanks for the help...
So when a new version comes, can i just update the firmware through a file

**Comment by luc-github** [comment]
Yes

**Comment by delchrys** [comment]
so now all i have to do is to cennect to my ender 3 board.

**Comment by luc-github** [comment]
I guess issue can be closed
