### ISSUE TITLE
sd card Ender 3

### ISSUE THREAD

**Issue by zeppy14** [luc-github/ESP3D#287]
Hi,
I want use ESP3D with my Ender 3.
All work fine, move axe, control  temperature …
But I have a problem with the SD card. I can't read the SD card. I have test two different SD card.
I tried to format in FAT and FAT32… I see no file !!
If I upload a file, the upload indicate 100% but it never finish. After the upload ESP3D is dead and I can see this message in the windows Commands : 
Error 503 :Communication locked!

I have flash my Wemos with the ESP3D firmware 1.0 (https://github.com/luc-github/ESP3D/releases/tag/1.0)
I have a board creality 3d v1.1.2 with the original firmware.
The M115 command give me this information : 
FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:http://www.mendel-parts.com PROTOCOL_VERSION:1.0 MACHINE_TYPE:www.creality3d.cn EXTRUDER_COUNT:1 UUID:00000000-0000-0000-0000-000000000000

Can you help me ?

![esp3d webui](https://user-images.githubusercontent.com/38042544/51057360-ae735980-15e5-11e9-9e8e-170cdc8098ec.jpg)

**Comment by luc-github** [comment]
What is the  M20 command output when you have files on SD ?

**Comment by zeppy14** [comment]
It look good !
![esp3d webui](https://user-images.githubusercontent.com/38042544/51059003-02347180-15eb-11e9-987b-8e508bc2e82e.jpg)
![sd](https://user-images.githubusercontent.com/38042544/51059007-0496cb80-15eb-11e9-95e8-4e99627bfc96.png)

**Comment by luc-github** [comment]
Why did you closed ? Did you solved issue ?

**Comment by zeppy14** [comment]
Sorry, I dont

**Comment by luc-github** [comment]
Ok in that case I think issue come from Marlin support in 1.0
I suggest you to use ESP3D 2.0 and ESP3D-WEBUI 2.1 they have lot of fixes for Marlin 
Once in WebUI 2.1 go to preferences to disable `Connection monitoring` or you will be disconnect after 20s

**Comment by zeppy14** [comment]
I test theESP3D 2.0 and ESP3D-WEBUI 2.1 ...it is not better

![2019-01-12 07_46_08-esp_7350bd](https://user-images.githubusercontent.com/38042544/51070233-5fa5de00-163e-11e9-89e1-f9a7658cadcf.jpg)
![2019-01-12 07_47_36-esp_7350bd](https://user-images.githubusercontent.com/38042544/51070235-60d70b00-163e-11e9-97d3-d25c5edfefda.jpg)

**Comment by luc-github** [comment]
Ok I just tested on my test system with Marlin 1.1.9 and it works :
![image](https://user-images.githubusercontent.com/8822552/51071631-9a1a7580-1654-11e9-9cbf-0e9348c360e2.png)

Look like the M20 on your system does not give file size so file name is not found as not matching the expected patern
Can you try the enclosed webUI and feedback 
[index.html.gz](https://github.com/luc-github/ESP3D/files/2751877/index.html.gz)

**Comment by zeppy14** [comment]
Hi Luc, 
It look better but not good ... I see the file, I can do nothing with : no print, no delete, no updload : 
![2019-01-12 11_36_30-esp_7350bd](https://user-images.githubusercontent.com/38042544/51072300-90960b00-165e-11e9-9908-1127cd8e1988.jpg)

**Comment by luc-github** [comment]
Ok lets check what your FW is sensitive to and able to do
The upload will be for the end as it is the more complex
try delete using command and let see which one is working:
M30 /TEST.GCO
M30 TEST.GCO

**Comment by luc-github** [comment]
for printing try 
M23 TEST.GCO 
then
M24

**Comment by zeppy14** [comment]
M30 /TEST.GCO
M30 TEST.GCO

Don't work => Deletion(bin) failed.

M23 TEST.GCO
M24

Do nothing.

What do you mind ? It is  better to update my Marlyn ?

**Comment by luc-github** [comment]
Well I do not have ender3 so I can just comment on your feedback 
if M30 do not work with error message it means issue with SD file system  as message state command exists but failed - so I would format SD using proper tools instead of PC : https://www.sdcard.org/downloads/formatter_4/

about printing command if M23  which select file and M24 which launch print , these commands are in theory present if I read well : https://github.com/Creality3DPrinting/Ender-3
But I am not sure why it does not work on your printer as you can see launch manually seems doing nothing or you do not have the open source version of the FW

Upgrading to Marlin is more on you - I do not use Marlin as none of my Printers use Marlin, I just have it on test boards, so I cannot comment what is the best for your Printer. I suggest you to ask on Forum what would be the benefit and also the possible drawback.

Bon Courage ^_^

**Comment by zeppy14** [comment]
Ok, I have format my SD card with SD Card Formatter : No change 
Thank for our help ... perhaps I will use octoprint but the raspeberry hasn't same cost that a esp8866. 

Merci,

**Comment by luc-github** [comment]
No problem - as your FW does not support the basic GCODE commands there is not much ESP3D can do sorry

**Comment by zeppy14** [comment]
Hi I upgrade my FW to marlin 1.1.19.
Thanks

**Comment by IInickII** [comment]
Hi, I made same try yesterday and with same result. Is there any chance to make it working?

**Comment by luc-github** [comment]
Ender FW does not provide the SD commands there is no choice but change ender FW

**Comment by IInickII** [comment]
Thank you for information, do you have some link to guide how to do it on Ender 3?

**Comment by zeppy14** [comment]
Https://youtu.be/p5rUR8Skp1c
Sorry it IS un french.

**Comment by IInickII** [comment]
Thank you, I will check it for inspiration. Do you know how I can check actual firmware version in my printer?

**Comment by zeppy14** [comment]
with the command M115

**Comment by zeppy14** [comment]
Finally, I will use another solution because the transfert of the SD Card are to slow. 
See the issue 290.

**Comment by IInickII** [comment]
Can you give me more info? I am very interested in this topic or can I contact you in any other way? Thank you

**Comment by zeppy14** [comment]
@IInickII 
Look at this octoprint.org
