### ISSUE TITLE
Upload Speed

### ISSUE THREAD

**Issue by zeppy14** [luc-github/ESP3D#290]
Hi,
the Upload file to the SD card are very very very slow.
It's work but a 585 kb file, I wait more that 10 mn : it's normal ?

The communication speed is set to 115200. For me it is the max speed for my Ender 3 with a motherboard V1.1.2.

It is possible to improve file transfer rate ?

![2019-01-15 19_58_18-esp_7350bd](https://user-images.githubusercontent.com/38042544/51202878-08cf2b80-1900-11e9-808e-de73f04e4a4b.png)

**Comment by luc-github** [comment]
Yes it is normal
The bottleneck is not the baud rate but the protocol itself

**Comment by luc-github** [comment]
This serial transfert is slow like hell

**Comment by zeppy14** [comment]
You think use a SD card direct connect at the ESP.
Do ESP3D support this ? have this solution approved ?

**Comment by zeppy14** [comment]
Ok thank.
So I close this issue.
