### ISSUE TITLE
Store g-code on SPIFFS

### ISSUE THREAD

**Issue by BlackWarriorNT** [luc-github/ESP3D#295]
Hello! Can i store g-code for print on SPIFFS?

**Comment by luc-github** [comment]
Hi this is currently not good idea, when it is currently used for macro which are small batch of GCODE 
* The SPIFFS capacity is very small 
* the ESP3D is not yet an host currently, will be in 3.0,  currently the macro are send without any control/check which is not safe for a print job, so store files won't be really useful if cannot be printed
* the SPIFFS is flash and have limited number of write/rewrite so using it for intensive storage and update may shorter the flash life time

**Comment by luc-github** [comment]
I guess question was answered. Close issue then
