### ISSUE TITLE
Error 503 :Communication locked!

### ISSUE THREAD

**Issue by Sanju-K** [luc-github/ESP3D#303]
Hello,

I loved your software and also appreciate the efforts you took in this project.
I uploaded the firmware (V1.0 )on ESP8266 and conected to Tevo Black Widow 3D printer with Marlin (1.1.0 - RC8).
Its working very well and all functions are working expect the actual printing, Whenever I upload file it uploads till 100% but nothing happens after, at same time in comments window it shows

>  "Error 503 :Communication locked!"

![ca](https://user-images.githubusercontent.com/47913517/53283828-fd2e1a80-3771-11e9-90f3-d4baf69e0c5d.PNG)

and then continue normal.....
the file is uploaded on the SD card in the printer, and also the timer for print is started but it stays ideal, not the temperature rises . Also the files in SD card is not displayed in

**Comment by luc-github** [comment]
In 1.0 there is no good control of commands so because esp8266 cannot handle any commands when uploading every commands during upload is rejected
And because you have auto check temperature checked commands are rejected
So 503 connection locked is not an error just not really frendly way to reject command during upload

What printer fw do you use ?

**Comment by luc-github** [comment]
Sorry just saw it in your comment. Reading from phone.
Please use branch 2.0 of ESP3D and web UI 2.1 they are improved version for Marlin

**Comment by luc-github** [comment]
any update ?

**Comment by Sanju-K** [comment]
Sorry for the delay....... 
The Problem still persist but now only OK comes in the comments window and files are not shown on the SD Window

**Comment by luc-github** [comment]
what is the output in command of M20 command ?
can you share the screenshot of info panel of ESP3D?

**Comment by Sanju-K** [comment]
The Output for M20 is complete list of files in SD Card 
![ca1](https://user-images.githubusercontent.com/47913517/53680497-9cb75400-3d02-11e9-81c1-53e9dff11389.PNG)
(Top one before uploading ...... Bottom on after uploading.....file name : butoon.gco)
and also the file which i uploaded is in list
But no output on SD CARD window
Info of ESP3D
![cap2](https://user-images.githubusercontent.com/47913517/53680589-d63c8f00-3d03-11e9-8450-395bf4947fa9.PNG)
![cap3](https://user-images.githubusercontent.com/47913517/53680591-d6d52580-3d03-11e9-81bb-22ca07980c5c.PNG)
![cap4](https://user-images.githubusercontent.com/47913517/53680592-d6d52580-3d03-11e9-9728-e8767101048a.PNG)

**Comment by luc-github** [comment]
this is settings window, I need the info one - the blue button on left of this window
also please give me the version of WebUI and ESP3D - they are in menu

**Comment by Sanju-K** [comment]
This is given in tab 
![cap11](https://user-images.githubusercontent.com/47913517/53680809-57952100-3d06-11e9-9417-40d15e5c764e.PNG)
![cap12](https://user-images.githubusercontent.com/47913517/53680810-57952100-3d06-11e9-875e-4bba519eadf6.PNG)
 
version of WebUI and ESP3D
UI: 2.0c31 / FW: 1.0

I updated according to Instruction but FW is still 1.0

I tried to upload the bin file in file system and also in firmware update 
![cap13](https://user-images.githubusercontent.com/47913517/53680827-94f9ae80-3d06-11e9-8f67-7c5a69ecee1f.PNG)

**Comment by luc-github** [comment]
Well obviously no you used 1.0 code so FW is 1.0 
use : https://github.com/luc-github/ESP3D/tree/2.0
also please use WebUI 2.1 it is up to date for Marlin not listing Files with file Size

**Comment by luc-github** [comment]
2.0 is different than 1.0 : https://github.com/luc-github/ESP3D/tree/2.0#installation

**Comment by Sanju-K** [comment]
I am not understanding the actual procedure.
The 2.0 Instruction says to add libraries, so the libraries should added in example file as in (#include "LIB.h" ) or in ardunio library folder.
Also it mention to Upload the data content on ESP3D file system - so which file has to upload and where - ESP3D Filesystem or Upload from arduino IDE as code in ESP module 
and also where to upload the .bin file 

PS: A suggestion : Add a video for complete procedure for 2.0 and above as the instructions are not clear enough.

**Comment by Sanju-K** [comment]
Sorry for the mistake my side. 
I updated the UI to 2.1 now the SD Windows shows file list. The printer is currently busy . Will update the print from WEB UI status.
Thank You For Your time and patience. 🥇🙌😊 
 I am Still not able to update the FW to 2.0

**Comment by luc-github** [comment]
This process of adding library is not specific to this project it is same for any arduino project that is why it is not detailed. A little search answer all questions: https://www.arduino.cc/en/guide/libraries
Copy content of libraries directory :
![image](https://user-images.githubusercontent.com/8822552/53681224-b9de2980-3ce6-11e9-8139-ab8131d20358.png)

which is :
![image](https://user-images.githubusercontent.com/8822552/53681230-cc586300-3ce6-11e9-8286-5b9fc26541fa.png)

to arduino libraries directory
![image](https://user-images.githubusercontent.com/8822552/53681236-ed20b880-3ce6-11e9-8d4b-3b5546bb639f.png)

which give you
![image](https://user-images.githubusercontent.com/8822552/53681239-0164b580-3ce7-11e9-90c6-dfa83cec0a3e.png)

then copy the complete ESP3D project as ESP3D is also a library to arduino library
![image](https://user-images.githubusercontent.com/8822552/53681254-340eae00-3ce7-11e9-8995-82618fa6c039.png)

which give :
![image](https://user-images.githubusercontent.com/8822552/53681264-4983d800-3ce7-11e9-9128-d470f0a3c5ac.png)

then go to example and open basicesp3d.ino :
![image](https://user-images.githubusercontent.com/8822552/53681277-7932e000-3ce7-11e9-8f6f-6967470f7ce6.png)

you can compile and flash
I cannot do more clear

**Comment by Sanju-K** [comment]
Thank You luc
for Your patience 
Sorry for the trouble........
its all done it printing from web UI .

**Comment by luc-github** [comment]
Happy printing then 😸
