### ISSUE TITLE
Update Canceled After 100 %

### ISSUE THREAD

**Issue by sancardu** [luc-github/ESP3D#306]
I have a problem with the embedded uploader, when i try to upload the index.html in the serial monitor it shows "M117 UPDATE 100%" but in the browser it says Update Canceled !
![Capture](https://user-images.githubusercontent.com/23182382/54249352-d3b11500-450d-11e9-9a37-284db343f361.PNG)

![Capture15](https://user-images.githubusercontent.com/23182382/54249611-d06a5900-450e-11e9-97c9-52264c52f930.PNG)
![Capture2](https://user-images.githubusercontent.com/23182382/54249612-d06a5900-450e-11e9-8b13-35455f4a215f.PNG)

**Comment by sancardu** [comment]
Even I can upload the SPIFFS Image but when i open the server it doesnt show
![Capture3](https://user-images.githubusercontent.com/23182382/54250538-35737e00-4512-11e9-9637-f0969d91f843.PNG)

Anybody knows what im doing wrong?

**Comment by sancardu** [comment]
Im using a ESP8266 With 1M ang 512KB SPIFFS

**Comment by luc-github** [comment]
Try to enable puya patch , you may have  this  flash issue  https://github.com/luc-github/ESP3D/issues/229

**Comment by sancardu** [comment]
So i found the esp.h [here](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Esp.h) but do i add it to the arduino project where the ESP3D.ino is?

**Comment by luc-github** [comment]
No you update the one already in instaled in core

**Comment by sancardu** [comment]
Ok done ! But still having the same program! When i try to upload the index.html.gz it goes to 90% and says Update failed and with index.html it goes to 100% but says Uodate canceled!
![Capture4](https://user-images.githubusercontent.com/23182382/54297595-30034b80-4585-11e9-9280-1bbf541b7875.PNG)

**Comment by luc-github** [comment]
Can you connect your ESP8266 to your PC and open Arduino Terminal and send the following commands ?
1 - [ESP710]FORMAT
2 - give me the output of [ESP420]plain

**Comment by sancardu** [comment]
Sure!

Formating...Done
Chip ID: 5795032
CPU Frequency: 160Mhz
Free memory: 41.39 KB
SDK: 3.0.0-dev(c0f7b44)
Flash Size: 1.00 MB
Available Size for update: 151.67 KB(Not enough)
Available Size for SPIFFS: 471.36 KB
Baud rate: 115200
Sleep mode: Modem
Channel: 11
Phy Mode: 11g
Web port: 80
Data port: 8888
Active Mode: Access Point (DE:4F:22:58:6C:D8)
SSID: ESP3D
Visible: Yes
Authentication: WPA
Max Connections: 4
DHCP Server: Started
IP: 192.168.0.1
Gateway: 192.168.0.1
Mask: 255.255.255.0
Connected clients: 0
Disabled Mode: Station (DC:4F:22:58:6C:D8) is disabled
Captive portal: Enabled
SSDP: Enabled
NetBios: Enabled
mDNS: Enabled
Web Update: Enabled
Pin Recovery: Disabled
Authentication: Disabled
Target Firmware: ???
FW version: 1.0

**Comment by luc-github** [comment]
Ok does Arduino SPIFFS uploader works after formating ?

**Comment by sancardu** [comment]
I think it doesnt work! But i dont know if i am doing something wrong, first I press and hold the reset button then I press and hold the program button, then Irelease the reset button, the ESP finally I release the program button and upload the sketch and finally I go to tools and Click ESP8266 Sketch Data Upload
![Capture5](https://user-images.githubusercontent.com/23182382/54308740-a65f7800-459c-11e9-8e82-797fe992b54b.PNG)

**Comment by luc-github** [comment]
Upload process for buttons is same process as flash, 100% identical, also must not have arduino serial terminal open

**Comment by sancardu** [comment]
My bad! It does work but it says the same:

Chip ID: 5795032
CPU Frequency: 160Mhz
Free memory: 41.39 KB
SDK: 3.0.0-dev(c0f7b44)
Flash Size: 1.00 MB
Available Size for update: 151.67 KB(Not enough)
Available Size for SPIFFS: 471.36 KB
Baud rate: 115200
Sleep mode: Modem
Channel: 11
Phy Mode: 11g
Web port: 80
Data port: 8888
Active Mode: Access Point (DE:4F:22:58:6C:D8)
SSID: ESP3D
Visible: Yes
Authentication: WPA
Max Connections: 4
DHCP Server: Started
IP: 192.168.0.1
Gateway: 192.168.0.1
Mask: 255.255.255.0
Connected clients: 0
Disabled Mode: Station (DC:4F:22:58:6C:D8) is disabled
Captive portal: Enabled
SSDP: Enabled
NetBios: Enabled
mDNS: Enabled
Web Update: Enabled
Pin Recovery: Disabled
Authentication: Disabled
Target Firmware: ???
FW version: 1.0
![Capture6](https://user-images.githubusercontent.com/23182382/54309811-e7f12280-459e-11e9-84a3-89fc77b3d463.PNG)

**Comment by luc-github** [comment]
so now you can upload index.html.gz - so what is the issue ?

**Comment by sancardu** [comment]
It says that it uploads but it actually doesnt ! When i connect to the ESP8266 I see this page :
![Capture7](https://user-images.githubusercontent.com/23182382/54312100-18878b00-45a4-11e9-96d5-0e0d5554b37d.PNG)

And it shouldnt show that because it is suppose to be already loaded,

And when i try to Upload the firmware update what I get is an Update Canceled

![Capture8](https://user-images.githubusercontent.com/23182382/54312144-3a810d80-45a4-11e9-8415-f572a5d5d0de.PNG)

**Comment by luc-github** [comment]
Check your flash size to be sure you have 1M https://github.com/luc-github/ESP3D/wiki/Flash-Size

**Comment by sancardu** [comment]
Yes I have 1M

![Capture9](https://user-images.githubusercontent.com/23182382/54314709-5b4c6180-45aa-11e9-8af2-c088d9139f70.PNG)

**Comment by luc-github** [comment]
Well I am dry about what is happenning, try flash using another partionning like 194K spiffs

**Comment by sancardu** [comment]
THANK YOUUU! IT WORKED WITH 192K SPIFFS! You have been really helpful!

**Comment by sancardu** [comment]
Do you know if I can connect the ESP3D to a J3 Connector in an Anet A8?

**Comment by luc-github** [comment]
Good - looks like a bug in core of ESP8266
Happy you worked around

I do not know, sorry. I do not have any Anet printer
