### ISSUE TITLE
DHT22 esp32

### ISSUE THREAD

**Issue by Carrotiam** [luc-github/ESP3D#307]
Hello, tell me how to enable DHT22 for esp32.
The sensor is exactly working, when checked with a test sketch for esp32, the readings are displayed.
In the preferences of the web interface, "Show DHT output" is included, but I see only static 20 ° C and 20%.
Perhaps the FW version is not the same, or I’m doing something wrong, but in “ESP3D Settings” I don’t see the DHT22 item.

SDK: v3.2-dev-39-gaaf12390
FW version: 2.0.0.c23 ESP32

I apologize for Google translator.

**Comment by luc-github** [comment]
if DHT is not visible in settings it means it is not enable at compilation, by default it is commented in config.h
Uncomment this line here : https://github.com/luc-github/ESP3D/blob/2.0/src/config.h#L77    

and use proper pin here : https://github.com/luc-github/ESP3D/blob/2.0/src/config.h#L114

**Comment by Carrotiam** [comment]
I did right away, but unfortunately that's not the point.
Here are the screenshots.
![image](https://user-images.githubusercontent.com/48165113/54487048-c98e6e00-48a1-11e9-91f6-0d471011dead.png)
![image](https://user-images.githubusercontent.com/48165113/54487076-4b7e9700-48a2-11e9-922c-bc00ccd24068.png)
![image](https://user-images.githubusercontent.com/48165113/54487083-605b2a80-48a2-11e9-9d1d-f4720ce46d54.png)

**Comment by luc-github** [comment]
Hi thanks for reporting, issue is not related to DHT detection 
 when you compile the ESP3D the config.h is inside the library as on my side when I enable DHT in config.h the DHT appear in settings
![image](https://user-images.githubusercontent.com/8822552/54487537-70b9d800-4897-11e9-95e9-569568e325fd.png)
but as you show you do not have it so - DHT is not enabled in code 

When you recompiled you modified another config.h not the library one  this is my guess

Additionnaly looking at code I have found an ugly bug I never noticed before, I have fixed it but it is not related to your issue

**Comment by Carrotiam** [comment]
You're right. It worked, not quite as I expected.
Thank you for help.
The topic can be closed.

**Comment by luc-github** [comment]
You DHT is not working as you expected ? What is wrong ?

**Comment by Carrotiam** [comment]
Wrong spoke.
ArduinoIDe does not work exactly as I thought)
DHT22 is working now, after your hint.
![image](https://user-images.githubusercontent.com/48165113/54488167-b1bde680-48af-11e9-9e6a-03f89d22deb4.png)

**Comment by luc-github** [comment]
Ok. Cool have fun ^_^
