### ISSUE TITLE
ESP8266NetBIOS.h: No such file or directory

### ISSUE THREAD

**Issue by bennyboom38** [luc-github/ESP3D#310]
Hello

When I try to compile I get the following error : 

ESP3D-1.0\ESP3D-1.0\esp3d\esp3d.ino:69:28: fatal error: ESP8266NetBIOS.h: No such file or directory

Could you help me to understand why ? 

Arduino 1.8.5

Thanks a lot

**Comment by luc-github** [comment]
I think your setup has issue because ESP8266NetBIOS is part of ESP8266 core
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266NetBIOS

**Comment by bennyboom38** [comment]
Hi!
Thanks for your answer, I have upgraded library ESP8266 to version 2.5.0 (from arduino) and I can compile now
