### ISSUE TITLE
Always Loading....

### ISSUE THREAD

**Issue by mjozwiakk** [luc-github/ESP3D#312]
Hello,

I've uploaded GRBL for ESP32 to my ESP32 DevKit V1 board, everything looks fine - in serial port monitor i can see, that esp is connected to my netword, also i can control all the functions using every G-code sender. 
When I try go to WebUI there is only:
"Loading..."
on the screen, and nothing happens. Any ideas how to fix it?

**Comment by luc-github** [comment]
I do not know may be the HTML is corrupted or filesystem table has been modified after you uploaded the index.html.gz
connect to your ESP by serial and send this command to format the file system
`[ESP710]FORMAT pwd=admin` 
then connect your ESP you should have the following UI to help to upload the index.html.gz present in data directory of GRBL_ESP32
![image](https://user-images.githubusercontent.com/8822552/55256366-32d88e80-525d-11e9-8148-66473c35752a.png)

**Comment by mjozwiakk** [comment]
Thank you for the response.
I think that the problem was that i did some modifications in flash memory. 
Uploading factory firmware and then grbl_esp32 solved the problem.

**Comment by luc-github** [comment]
Ok great, I  close issue then

**Comment by mjozwiakk** [comment]
Interesting thing was that clearing flash using esptool (erashe_flash) did not work. Only after uploading the default firmware it helped.

**Comment by luc-github** [comment]
Default FW ?

**Comment by mjozwiakk** [comment]
From this site
https://www.espressif.com/en/support/download/at
