### ISSUE TITLE
MKS GEN V1.0 or 1.2 - LCD TFT and ESP8266

### ISSUE THREAD

**Issue by quichy3016** [luc-github/ESP3D#319]
Hello, good afternoon, sorry, but I use a translator.
 The subject is the following I have an MKS Gen L V1.0 in which I already made the communication using the ESP8266 module and the ESP3D firmware and it was a success. To do this, disconnect my MKS TFT32 from the AUX 1 terminal and at pins TX0 and RX0 connect the pins of the ESP8266. I would like to connect the MKS TFT32 to the AUX 1 and connect the ESP8266 module to the same pins for some resistors like this one and to the TX / RX pins of the AUX 1 with the USB (serial BUS type).
The query is what resistance values ​​should be used to make the connection.
Thank you.

**Comment by luc-github** [comment]
This is not a good idea you will have 2 devices sharing same TX, and will send requests n same tme causing gabage on line due to mixed data flow

**Comment by quichy3016** [comment]
It is not the same when you have connected the USB cable and also the TFT32 screen?

**Comment by luc-github** [comment]
if you connect to same TX - yes but many boards block one of them when both are connected at least Arduino Mega do - now you can try if the esp and TFT do not send data in same time it should be ok, but TFT send permanent requests to get info

**Comment by luc-github** [comment]
connection suggestions are in wiki : https://github.com/luc-github/ESP3D/wiki/ESP8266-01 and https://github.com/luc-github/ESP3D/wiki/ESP8266-01

**Comment by quichy3016** [comment]
Así lo podríamos conectar directamente a los pines tx0 y rx0 recién el TFT conectado?

**Comment by luc-github** [comment]
Depende de la configuración del FW Marlin / Repetier.
si el FW admite TFT en TX0 / RX0 y ESP en TX / RX, se puede

**Comment by quichy3016** [comment]
En el pin tx no llevaría resistencia para que no le ll3gu3 una corriente cuando otro tx este activo??

**Comment by luc-github** [comment]
No entiendo la pregunta, TX0 y TX1 son diferentes.
Como lo he escribo  antes, tener 2 dispositivos en un mismo TX no es correcto

**Comment by luc-github** [comment]
Any update?

**Comment by luc-github** [comment]
ok if no update I close issue
