### ISSUE TITLE
Sbase Smothie 3 problems

### ISSUE THREAD

**Issue by fedonkin** [luc-github/ESP3D#330]
Smoothie firmware, ESP3D 2.1 .You can not see the temperature of the extruder table. No config visible.  Very long delay. Press move x axis 10 mm, after 3 seconds the printer moves x axis 10 mm. Something need to change in the firmware smoothie? or how to fix it all?
![iaQh3I2R](https://user-images.githubusercontent.com/43302315/57874149-9b34fc80-7818-11e9-8658-bf1fd28ef0df.png)
![SikWyzJR](https://user-images.githubusercontent.com/43302315/57874150-9b34fc80-7818-11e9-8a5e-27e2967f4945.png)
![tksrfwcj](https://user-images.githubusercontent.com/43302315/57874152-9bcd9300-7818-11e9-8919-f91d95b0f25b.png)
![3n7MmJAv](https://user-images.githubusercontent.com/43302315/57874153-9bcd9300-7818-11e9-8643-7ebb7534e75b.png)
![FiFuYV3L](https://user-images.githubusercontent.com/43302315/57874154-9bcd9300-7818-11e9-8f4e-6d4631dff6c3.png)

**Comment by luc-github** [comment]
looks like serial communication problem as information from ESP seems Ok.
Can you share  the ESP3D info tab?
Also can you share the wiring you use ?
which esp board you use ?

**Comment by luc-github** [comment]
Any update?

**Comment by luc-github** [comment]
I close issue if no update
