### ISSUE TITLE
SoftwareSerial

### ISSUE THREAD

**Issue by LL1r1k** [luc-github/ESP3D#333]
Can i use SoftwareSerial for my NodeMCU? When i tried to connect my power off printer to NodeMCU and power on ESP, it doesn't start(Led not flashing), but when i press reset button all fine. Maybe if i change my GPIO0 and GPIO3 to other pins something will change.

**Comment by luc-github** [comment]
Sorry - Software serial is not supported in ESP3D and for correct performance, better use hardware serial
You may have power supply issue if such behavior, how do you power your nodeMCU ?

**Comment by LL1r1k** [comment]
I connected the NodeMCU through the power supply and i have relay connected to i which turn on printer. First, I turn on the board, and then switch the relay through the web interface and turn on the printer. In teory) But when i turn on NodeMCU, it doesn't turn on(LED does not flash), if press RESET button everything works fine.

**Comment by LL1r1k** [comment]
NodeMCU connected to printer: TX Node -> RX MKS gen L ; RX Node -> TX MKS gen L ; GND ->GND

**Comment by luc-github** [comment]
does the NodeMCU start properly if you connect by USB ?

**Comment by LL1r1k** [comment]
doesn't matter

**Comment by LL1r1k** [comment]
now, I tried to connect the board to the Arduino Mega turned off and it's the same.

**Comment by LL1r1k** [comment]
Only starts working normally after pressing the restart button.

**Comment by LL1r1k** [comment]
And of course, when the printer is already turned on, the NodeMCU may start up normally.

**Comment by luc-github** [comment]
Serial is GPIO1 /GPIO3 not GPIO0/GPIO3

**Comment by LL1r1k** [comment]
RX TX on NodeMCU,I have written it wrong.

**Comment by luc-github** [comment]
Why do you think is serial pins the problem ?
Does your MCU start if not serial connected ?

**Comment by LL1r1k** [comment]
Yes, MSU starts if nothing is connected and starts when connected to a working printer.

**Comment by luc-github** [comment]
you power 5v or 3.3v ?

**Comment by LL1r1k** [comment]
NodeMCU can be powered by 5v.

**Comment by luc-github** [comment]
well it depend how you connect the 5V - you put in VCC, right ?

**Comment by LL1r1k** [comment]
I connect VIN and GND to power supply

**Comment by luc-github** [comment]
Well I am not great on electronic - so I have no idea - may be 5V tolerance issue on rx/tx ?
There is no difference from FW point of view between hard start and reset so issue is hardware for sure,  and FW even did not boot per your feedback, I doubt changing serial pins will do something, really looks like power issue, may be adding some capacitor ? 
I guess you have same issue what ever the FW - better ask on electronician gurus of ESP8266

**Comment by LL1r1k** [comment]
Ok, thank you anyway.
