### ISSUE TITLE
can i ad wifi to Anet A8 

### ISSUE THREAD

**Issue by CsepregiArtur** [luc-github/ESP3D#334]
Hello

I want to ask if it is possible to add this wifi module to Anet A1284-Base V1.7 Control Board Mother Board Mainboard for Anet A8.
I found a good description here http://lokspace.eu/anet-a8-wifi-mod/
but I want to use esp3d with a Node MCU or D1 mini. 
Do you think it is necessary to unsolder R52 and R53 resistors or?

Thank you

**Comment by luc-github** [comment]
I cannot answer as I do not have any anet printer/board - but links you mention explain that the addon card does not need to unsolder component with some risks. so may be ? 
Better ask to electrocian gurus or on linked article like you did.
 
I will let question open if anyone can answer you - feel free to feedback if you got update

**Comment by rhialto56** [comment]
I do it without pb.  Juste soldier rx and tx wire on the board anet v1.7 just near the chip atmega

**Comment by luc-github** [comment]
@CsepregiArtur @rhia lto56 feel free to add a page in wiki with your board and wiring ^_^

**Comment by rhialto56** [comment]
Ok. I just sold two wires from number 9 and number 11 to connector j3. 
then I connected to the j3 connector as in the tutorials.
do not forget in the console esp3d to disable the M117 code otherwise retrieves error messages on the LCD . That's all
![20190605_201937](https://user-images.githubusercontent.com/51383186/58991540-c643b800-87e8-11e9-8368-b93646791595.jpg)

**Comment by CsepregiArtur** [comment]
super thank you I will try also and I will come back with photos am will
enter it in wiki

**Comment by rhialto56** [comment]
with a better picture
Good luck
![anet a8 board](https://user-images.githubusercontent.com/51383186/59010169-9d471580-8830-11e9-97a9-ba0b46776449.jpg)

**Comment by luc-github** [comment]
Any update ?

**Comment by CsepregiArtur** [comment]
I'm trying to flas marlin to my printer,  and with after that I will try to
connect it. Sorry for it taking so long,  i'm  stuckt to burn the
bootloader

**Comment by CsepregiArtur** [comment]
I'm trying to flas marlin to my printer,  and with after that I will try to
connect it. Sorry for it taking so long,  i'm  stuck to burn the
bootloader. Maybe today I will find something.

**Comment by CsepregiArtur** [comment]
hello

Please close this topic. my anet board is officially blown.

**Comment by luc-github** [comment]
Sorry to read this😐

**Comment by gello0** [comment]
I managed to solder wires on the 1.7 board. Would be nice if this is added in anet a8 wiki :)

**Comment by luc-github** [comment]
@gello0 wiki is open to everyone , addition are always welcome, let me know if you have issue to add things

**Comment by luc-github** [comment]
@gello0 thank you for your contribution - you can use this https://github.com/luc-github/ESP3D/issues/427 to store pictures
