### ISSUE TITLE
wemos d1 mini wiring question

### ISSUE THREAD

**Issue by damienj210** [luc-github/ESP3D#338]
what's the purpose of the zener between rx and ground? if you dont have it will you have issues?

**Comment by luc-github** [comment]
This wiki was done by @mauro - I let him answer

**Comment by damienj210** [comment]
that's why I was confused, the wemos is based on 5 volts. is the TX and RX still 3.3?

**Comment by luc-github** [comment]
ESP is 3.3v - wemos has voltage regulator for power but all GPIO are 3.3v and not 5V tolerant I think

**Comment by firepower9966** [comment]
ESP8266 is 5V tolerant I/O I using D1 mini TX and RX directly connected to atmega TX  and RX.

**Comment by luc-github** [comment]
https://www.espressif.com/en/support/explore/faq?keys=Are%20the%20GPIO%20pins%205V%20compatible%3F

![image](https://user-images.githubusercontent.com/8822552/64015884-ca504f00-cb25-11e9-9869-422e434f36ad.png)
ESP8266  is not 5v tolerant - for the boards it depend

**Comment by firepower9966** [comment]
https://www.ba0sh1.com/blog/2016/08/03/is-esp8266-io-really-5v-tolerant/

**Comment by luc-github** [comment]
this is a third party blog - I shared what espressif  published - now everyone is free to do what he wants
