### ISSUE TITLE
[BUG] Typo in README.md: points ArduinoWebSockets, but is WebSockets

### ISSUE THREAD

**Issue by sl1pkn07** [luc-github/ESP3D#340]
**Describe the bug**
Typo in the README.md

points to ArduinoWebSockets, but is WebSockets

because with ArduinoWebSockets installed:

~~~
In file included from /tmp/arduino_build_196990/sketch/esp3d.cpp:85:0:
syncwebserver.h:25:30: error: WebSocketsServer.h: No such file or directory
 #include <WebSocketsServer.h>
                              ^
compilation terminated.
Usando librería ESP8266WiFi con versión 1.0 en la carpeta: /home/sl1pkn07/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi 
Usando librería ESP8266mDNS con versión 1.2 en la carpeta: /home/sl1pkn07/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS 
Usando librería ESP8266WebServer con versión 1.0 en la carpeta: /home/sl1pkn07/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer 
Usando librería EEPROM con versión 1.0 en la carpeta: /home/sl1pkn07/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/EEPROM 
Usando librería DNSServer con versión 1.1.1 en la carpeta: /home/sl1pkn07/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/DNSServer 
exit status 1
WebSocketsServer.h: No such file or directory
~~~

commit used: 1d7b3ff83f72d5bc5cc8bc0a525ceda4f2333c02

**Comment by sl1pkn07** [comment]
Seems Arduino IDE library manager "ArduinoWebsockers" @ links2004 (Markus Sattler) is named as "WebSockets" and "ArduinoWebSockets" @ gilmaimon (Gil Maimon) is named as "ArduinoWebSockets"

**Comment by luc-github** [comment]
you did not copied https://github.com/luc-github/ESP3D/tree/2.1/libraries/arduinoWebSockets ?

**Comment by sl1pkn07** [comment]
seems my Arduino IDE (1.8.9) linux not used that library and try to find external ones

**Comment by luc-github** [comment]
all libraries are in my repo in directory libraries because version are frozen
I need to emphasis that and update readme

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/59872144-60832e80-9399-11e9-83bc-f52c71af6611.png)

**Comment by sl1pkn07** [comment]
yep. i see it in my local clone repository, but my IDE can't take it

**Comment by luc-github** [comment]
yes - I will emphasis in readme

**Comment by sl1pkn07** [comment]
ok, i copied it, but the IDE say me need update some libraries

![Screenshot_20190620_203004](https://user-images.githubusercontent.com/462213/59872500-32eab500-939a-11e9-8188-6c17a29e94ec.png)

i need keep it?

**Comment by luc-github** [comment]
yes

**Comment by luc-github** [comment]
I cannot test all update for all libraries - so I freeze version
