### ISSUE TITLE
[BUG] no printer config when using marlin 2.0

### ISSUE THREAD

**Issue by TheFlash12314** [luc-github/ESP3D#343]
**Describe the bug**
no printer configuration when using marlin 2.0

**To Reproduce**
1. Go to printers tab
2. Click on refresh
3. nothing except have label, value, help box

**Expected behavior**
list out full printer configuration 

**Screenshots**

**ESP3D Firmware:**
- Version: 2.1
- Wifi mode:[e.g. STA]

**Target Firmware:**
 - Name: [ Marlin]
 - Version [2.0]

**Board used (please complete the following information):**
 - MCU: [esp01s and ESP32] 
 - Name:[Doit devkit v1] 
 - Flash size: [4M i think]

![Screenshot (65)](https://user-images.githubusercontent.com/36818971/59927587-68ad9d80-946f-11e9-95fc-5d70cb4a5de5.png)

**Comment by luc-github** [comment]
What is the output of M503  when you send to Marlin ?

**Comment by TheFlash12314** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/36818971/59935052-7c610000-947f-11e9-9ce6-ef71ba0c390d.png)

**Comment by TheFlash12314** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/36818971/59935140-b6320680-947f-11e9-947b-f39c6598481b.png)

**Comment by luc-github** [comment]
ok so issue is in webui, what is your webUI version? check what display on menu

**Comment by TheFlash12314** [comment]
v2.1

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/59935545-4e16fc80-944e-11e9-8c41-29871983e0d1.png)

**Comment by TheFlash12314** [comment]
UI: 2.1b20 / FW: 2.0.0.c23

**Comment by luc-github** [comment]
this was fixed in 2.1b24 so update with latest webUI and should be Ok

**Comment by TheFlash12314** [comment]
ok... will try

**Comment by luc-github** [comment]
just upload the latest index.html.gz from here https://github.com/luc-github/ESP3D-WEBUI/blob/2.1/index.html.gz

**Comment by TheFlash12314** [comment]
i tried upload that code ... it is still UI: 2.1b20 / FW: 2.0.0.c23

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/59936346-0e511480-9450-11e9-9c3a-aeb74623066a.png)

**Comment by TheFlash12314** [comment]
ok, It's working now, thanks!
