### ISSUE TITLE
ESP-01 with PUYA Flash

### ISSUE THREAD

**Issue by AFUman** [luc-github/ESP3D#353]
**Describe the bug**
I am aware that there are problems with the ESP-01 with a PUYA flash. I tried a lot because I get SPIFFS up and running the ESP3D too. Unfortunately, I have found no tips on the Internet, which work. Unfortunately, after the ESP-01 flashes with ESP3D 2.1, the ESP-01 does not start, no WLAN identifier is transmitted. The ESP-01 is alright, I flashed Tasmota as a test and that starts everything and it works. Does anyone have a hint or maybe a finished bin file, which I can flash. Sit at the problem for a few days and do not get it to work. I tested it on a WEMOS, because ESP3D runs without problems. But I would like to use the ESP-01, because the hardware has a socket for where I can plug it directly.

**ESP3D Firmware:**
- Version:2.1
  

**Board used (please complete the following information):**
 - MCU: ESP8266
 - Name:ESP-01
 - Flash size: PUYA 1M
**Additional context**
Wiring, decoded stack, etc...

**Comment by luc-github** [comment]
1 how did you applied the define ?

**Comment by luc-github** [comment]
Any update?

**Comment by AFUman** [comment]
Unfortunately I did not get any further, I just get ESP3D running on the ESP-01 with Puya Flash.

**Comment by luc-github** [comment]
sorry before you wrote cannot - now can ? so what is the issue ?

**Comment by AFUman** [comment]
Unfortunately there was a mistake in the translation and unhappily I have not got any further. I haven’t found a working solution because of the SPIFFS file system on an ESP-01 with a puya flash. Unfortunately none of the many tips works.

**Comment by luc-github** [comment]
So back to original question how did you applied the patch

**Comment by AFUman** [comment]
I found different esp.ccp files in different forums. I have tried this, I have also found patches but unfortunately no info how to install this.

**Comment by d-a-v** [comment]
When using arduino ide to compile esp3d and if you use latest 2.5.2 esp8266 arduino core, you can create this file `platform.local.txt` next to `platform.txt` in your directories containing:
```
compiler.c.extra_flags=-DPUYA_SUPPORT=1
compiler.cpp.extra_flags={compiler.c.extra_flags}
```

Note: it is ***not*** sufficient to add `#define PUYA_SUPPORT 1` anywhere in your code.

What would be better for everybody is to go to esp8266 arduino github repository and open a new issue asking for default support for these flash chips.

**Comment by luc-github** [comment]
The issue and solution is actually pinned on top of issues

**Comment by luc-github** [comment]
@AFUman thanks to @d-a-v the puya settings is now applied by default
You need to take latest git from https://github.com/luc-github/ESP3D/tree/2.1
and latest git from https://github.com/esp8266/Arduino

and puya is applied by default - hope it solve your issue

**Comment by AFUman** [comment]
Thank you for your help. I can write SPIFFS now. But after flashing of ESP3D will not start unfortunately no output on'dem terminal and also no wifi with ESP3D SSID. I flash Easypesy with the tool on the ESP-01 starts the Smarthome solution without problems. Could you maybe make me a BIN for the ESP-01 I think I'm doing something wrong.

**Comment by luc-github** [comment]
flash using `Erase Flash :  All Flash Contents`
To be in clean situation

**Comment by AFUman** [comment]
OK, thank you I'll give it a try.

**Comment by luc-github** [comment]
@AFUman any update ?

**Comment by AFUman** [comment]
Yes, i have ESP3D on my ESP-01 and all is OK. Many thanks for your help
