### ISSUE TITLE
ESP3d Wont upload

### ISSUE THREAD

**Issue by TurtleDude29** [luc-github/ESP3D#354]
Hey i got this error when trying to upload. I got a different one earlier but i fixed that and got this one. Thank you to anyone trying to help!

esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM15
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "C:\Users\yonat\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.5.2/tools/upload.py", line 25, in <module>
    esptool.main(fakeargs)
  File "C:/Users/yonat/Documents/ArduinoData/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 2653, in main
    esp.connect(args.before)
  File "C:/Users/yonat/Documents/ArduinoData/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 468, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

**Comment by luc-github** [comment]
Hi this one is related to esp8266 core. Better to open issue on esp8266 github

**Comment by luc-github** [comment]
I would suggest to remove esp8266 core completly and do a new fresh install as under windows 10.  2.5.2 works on my side

**Comment by TurtleDude29** [comment]
Okay. Thank you ill try that and if it doesnt work ill ask on the esp github

**Comment by luc-github** [comment]
be sure nothing left in C:\Users\yonat\Documents\ArduinoData\packages\esp8266 after removal

**Comment by TurtleDude29** [comment]
okay

**Comment by TurtleDude29** [comment]
i put a jumper on Ground and GPIO0 because i have a programmer and it worked but i screwed it up.
i connected to the esp wifi and messed up the setup. i misspelled the password or something where the esp3d wifi does not show up in my router or my wifi networks. Will i need a new esp?

**Comment by luc-github** [comment]
Just use serial terminal and ESP commands to setup your wifi  or reset settings

**Comment by TurtleDude29** [comment]
How do i do that? im a noob

**Comment by TurtleDude29** [comment]
Found it. Thank you

**Comment by TurtleDude29** [comment]
Nothing is showing up when i type commands

**Comment by luc-github** [comment]
be sure you use correct baud rate and NL/CR is selected
![image](https://user-images.githubusercontent.com/8822552/62270268-e2a15100-b435-11e9-81d9-6cc8634689fc.png)
then type
`[ESP444]RESET`
and so reboot with `[ESP444]RESTART`

**Comment by luc-github** [comment]
@TurtleDude29 Any update ?

**Comment by TurtleDude29** [comment]
Oh yeah i forgot to say. Yes it worked perfectly. Thank you!!!!!!!!!

**Comment by luc-github** [comment]
-Great
