### ISSUE TITLE
Error EEprom

### ISSUE THREAD

**Issue by Wuckel01** [luc-github/ESP3D#361]
Hello I have a problem with the access to the flash memory is not the web interface is but when it comes to save nothing.

I am using a NODEMCU V3 4MB ESP8266MOD, Marlin 1.8, WiFI STA
on the home page, I can not upload anything and he does not show a memory if I but with telnet memory query this is there.

I have already used several modules ESP8266-01 1MB and also NODEMCU 0.9 everywhere the same problem no memory.
IN IDE I have adjusted the SPiFFS jedenlam suitable.

have in the forum already pushed everything is tried nothing is

[ESP501]<line>
Checksum: 12
Cmd Ok

[ESP400]plain
{"EEPROM":[

]}
[ESP300]
2

[ESP720]
SPIFFS Total:2.81 MB Used:105.40 KB

[ESP800]
FW version:2.1.0.b33 # FW target:??? # FW HW:Serial SD # primary sd:none # secondary sd:none # authentication:yes # webcommunication:Sync:81 # hostname:MYESP

I have a screenshot created. What is missing and not possible.
https://ibb.co/wcD4mRH
https://ibb.co/vL2W1WH

Maybe you have an idea.

**Comment by luc-github** [comment]
I have no idea with current information, please fill the issue template

**Comment by Wuckel01** [comment]
Sorry was not quite finished yet.

**Comment by luc-github** [comment]
what esp core version ?

**Comment by Wuckel01** [comment]
esp verson 2.5.2      IDE 1.8.5

**Comment by luc-github** [comment]
looks like your SPIFFS is not writable or corrupted
try `[ESP710]FORMAT pwd=admin` as it looks like you enabled authentication
then  upload index.html.gz with webpage

**Comment by Wuckel01** [comment]
[ESP710]FORMAT
Formating...Done
I had already done the formatting

echo:Unknown command: "[ESP710]FORMAT"
                                      ok
                                        echo:Unknown command: "Incorrect Cmd"
                                                                             ok
when uploading the index.html.gz file man can wait forever because nothing happens.

**Comment by luc-github** [comment]
your esp is connected to printer ?
please debug it disconnected - your commands seems going to printer not ESP 
Do formating when serial is connected to ESP, use arduino monitor to send commands

**Comment by Wuckel01** [comment]
I made the password function but. I am always checked out for password.
witty ip, he shows in the LCD but esp sends nothing but an error.
G28
Error 401 :Authentication failed!

**Comment by luc-github** [comment]
can you try with authentication disabled ?

**Comment by Wuckel01** [comment]
//AUTHENTICATION_FEATURE: protect pages by login password
//#define AUTHENTICATION_FEATURE

I did it anyway he asks

**Comment by luc-github** [comment]
It won't if disabled -  close arduino editor and open again to be sure you start on clean base

**Comment by luc-github** [comment]
then refresh webUI

**Comment by Wuckel01** [comment]
I have made the same thing he fargt after password and I can not choose printer type and synonymous nix save settings. I have another module taken the same problem igentwas that makes me nit in the flash can write

**Comment by luc-github** [comment]
you enabled authentication what others changes did you do in FW ?

**Comment by Wuckel01** [comment]
hi I read in a forum post that in the config.h
DEFAULT_STA_SSID was the problem I have set it so maybe that's the error

//position in EEPROM
//AP mode = 1; Station client mode = 2
#define EP_WIFI_MODE			2    //1 byte = flag

**Comment by luc-github** [comment]
what forum post ?

do not change anything but within this section : https://github.com/luc-github/ESP3D/blob/2.1/esp3d/config.h#L40-L93

others part do not touch

**Comment by Wuckel01** [comment]
I wanted to have wlan sta mode because there were only those password queries via wlan, that's why I set the values

post
https://github.com/luc-github/ESP3D/issues/218

**Comment by luc-github** [comment]
I this post the guy mess up the values, do not change them, change only the ones I gave before

**Comment by Wuckel01** [comment]
thanks jop that was it I've done it all goes now oh man

**Comment by luc-github** [comment]
Ok great - I close issue then
