### ISSUE TITLE
[FEATURE REQUEST] Reset a pin's state after using [ESP201]

### ISSUE THREAD

**Issue by josedpedroso** [luc-github/ESP3D#364]
I connected GPIO 2 on my ESP01 to my printer's reset pin. To reset the printer, I use a macro in spiffs that contains:

```
[ESP201]P2 V1
[ESP201]P2
```

This is too fast to actually reset the printer, but I have no way to delay the second command that resets the pin. Issuing these commands manually from the dashboard works fine. Using just the first line in the macro also works, ie, the printer reboots, but I'm not comfortable leaving the printer's reset pin high all the time.

I see 2 possibilities here: I either need a command to delay the macro's execution or the [ESP201] command should have an option to reset a pin to its original state after some time.

As a workaround, I tried adding an [ESP410] command between the 2 [ESP201] lines, but that did nothing at all.

UI: 2.0c9 / FW: 2.0.0.c25

Thanks.

**Comment by luc-github** [comment]
we could add a 2 new parameters 
[ESP201]P2 V1 D2000 R0
D for delay in ms
R for revert to the value after delay

**Comment by josedpedroso** [comment]
My printer doesn't like it when I set the reset pin low (0). Would it be possible to use R parameter with no value to set the pin's mode to input?

**Comment by luc-github** [comment]
I am not sure of pin state when in input mode, should be low

**Comment by luc-github** [comment]
but should be able to see 
doing manually the test 
send 
[ESP201]P2 V1
then wait few sec, then send
[ESP201]P2

if acting sam as 
[ESP201]P2 V1
wait few sec
send [ESP201]P2 V0
then send [ESP201]P2

then using [ESP201]P2 V1 D2000 R0 then [ESP201]P2 should be ok

**Comment by josedpedroso** [comment]
In input mode, an arduino's pin is in a high impedance state, ie, floating from my printer's point of view. Reference: https://www.arduino.cc/en/Tutorial/DigitalPins

> equivalent to a series resistor of 100 megohm in front of the pin

**Comment by josedpedroso** [comment]
I tried that, it locks the printer up until I send [ESP201]P2.

**Comment by josedpedroso** [comment]
In any case, just having the delay in the first [ESP201] command would solve my issue.

**Comment by luc-github** [comment]
the delay without changing state is confusing IMHO
so better to create a delay command in that case
e.g. [ESP250]1000  for delay 1000ms

**Comment by josedpedroso** [comment]
That'd work for me. And I bet it could be useful in other situations. Thanks.

**Comment by josedpedroso** [comment]
Just by curiosity, do you know why [ESP410] didn't work to delay the macro? Is that command only available interactively?

**Comment by luc-github** [comment]
Too fast I guess

**Comment by luc-github** [comment]
I have implemented the command in 3.0, but there is not webUI for it yet
* Delay command
[ESP290]<delay in ms>[pwd=<user password>]

**Comment by luc-github** [comment]
Command also added in 2.1
