### ISSUE TITLE
[BUG]SD Upload

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#365]
@Roman-RV78  please use this issue 
Hello. I ran into a similar problem. I can see the files on the SD card, I can delete them, but copying the files to the SD card fails, error. Arduino DUE Marlin 2.0, NODE MCU

M115
FIRMWARE_NAME:Marlin bugfix-2.0.x (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:SERIAL_XON_XOFF:0
Cap:BINARY_FILE_TRANSFER:0
Cap:EEPROM:1
Cap:VOLUMETRIC:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:1
Cap:Z_PROBE:1
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:0
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:0
Cap:PROMPT_SUPPORT:0
Cap:AUTOREPORT_SD_STATUS:0
Cap:THERMAL_PROTECTION:1
Cap:MOTION_MODES:0
Cap:CHAMBER_TEMPERATURE:0
[ESP800]
FW version:2.1.0.b35 # FW target:marlin # FW HW:Serial SD # primary sd:none # secondary sd:none # authentication:no # webcommunication:Sync:81 # hostname:MYESP
M20
Begin file list
CUBE.G 0
End file list

**Comment by luc-github** [comment]
what is the error ? when happen in upload ?

**Comment by Roman-RV78** [comment]
The process of downloading files to the SD card has been in progress for a very long time, and when it reaches 100%, there is an error loading the file, and a file of zero size appears on the SD card.
Translated using Google

**Comment by luc-github** [comment]
what error appear?

**Comment by Roman-RV78** [comment]
![1](https://user-images.githubusercontent.com/48883321/63840844-62b1cc80-c98a-11e9-9cc8-f4ccb37567b1.jpg)
![2](https://user-images.githubusercontent.com/48883321/63840852-65142680-c98a-11e9-81c4-f289eeb02ec4.jpg)

**Comment by luc-github** [comment]
what is the size of upload file ?

**Comment by Roman-RV78** [comment]
I sent a file of 1.53 megabytes in size.
  File from Home.zip archive loaded successfully

**Comment by luc-github** [comment]
If upload of home.g is working then upload is working in normal way
can you share the gcode file you use ?

**Comment by Roman-RV78** [comment]
[cube.zip](https://github.com/luc-github/ESP3D/files/3551562/cube.zip)

**Comment by luc-github** [comment]
ok nothing pop up my eyes, I will add more info when issue raise in websocket message to get some clue

**Comment by luc-github** [comment]
I tried with your configuration with baud rate 250000 and cannot duplicate
the upload happen with long time but at the end the file is there

**Comment by luc-github** [comment]
@Roman-RV78 what is your baud rate ?

**Comment by Roman-RV78** [comment]
250000

**Comment by luc-github** [comment]
I cannot reproduce on my side - and you said it is working with test file - did you tried another file ?
also how is your wiring ? you may have noise on it

**Comment by DiegoGiovany** [comment]
I Cant upload too, but I think its caused by marlin ADVANCED_OK feature...

**Comment by luc-github** [comment]
@DiegoGiovany why do you think isue could come ADVANCED_OK  ?

**Comment by DiegoGiovany** [comment]
Cause when ADVANCED_OK is disabled, upload works....

**Comment by luc-github** [comment]
@DiegoGiovany thank you for this feedback - I will enable ADVANCE_OK to see what is happening then

**Comment by luc-github** [comment]
@Roman-RV78 any update ? do you have ADVANCED_OK  enabled ?

**Comment by Roman-RV78** [comment]
How to check if ADVANCED_OK is enabled or not

**Comment by AnHardt** [comment]
Two ways.
a) Look it up in Configuration_adv.h
b) Look it up in the log. If 'ok' is not followed by Nlinenumber an buffer states `ADVANCED_OK` is not enabled.

**Comment by Roman-RV78** [comment]
In Configuration_adv.h, the line ADVANCED_OK is always commented out by default, I didn’t even touch it
