### ISSUE TITLE
Changing BAUDRATE 115200 for faster file transfer

### ISSUE THREAD

**Issue by CsepregiArtur** [luc-github/ESP3D#371]
**Describe the bug**
It is not realy a bug, it is a question, i cant ask it somewhere else.
I'm using BIGTREETECH-SKR-V1.3 board conected to it a D1 mini, its working fine.
I want to ask you if I change the BAUDRATE 115200 in the Marlin 2.0 to somthing higher and set the BAUDRATE at the ESP3D in the setting i will get a biger data transfer speed? 
To your knowledge this will get me in another problems?

Thank you

**Comment by luc-github** [comment]
the answer is pinned in top of issues : https://github.com/luc-github/ESP3D/issues/292

**Comment by luc-github** [comment]
I guess issue can be closed
