### ISSUE TITLE
[QUESTION] How do Marlin Wifi settings have influence to ESP3D

### ISSUE THREAD

**Issue by kkberg** [luc-github/ESP3D#374]
Good morning,

I can't get information about the Marlin 2.0.x Wifi settings and what really happens when setting them.
What modul is needed to use that settings? Maybe someone has detailed information for sharing.

Thank you very much

**Comment by luc-github** [comment]
What Marlin WiFi settings are you talking about ?

**Comment by kkberg** [comment]
I mean this out of configuration_adv.h


/**
 * WiFi Support (Espressif ESP32 WiFi)
 */
//#define WIFISUPPORT
#if ENABLED(WIFISUPPORT)
  #define WIFI_SSID "Wifi SSID"
  #define WIFI_PWD  "Wifi Password"
  //#define WEBSUPPORT        // Start a webserver with auto-discovery
  //#define OTASUPPORT        // Support over-the-air firmware updates
#endif

**Comment by luc-github** [comment]
they are for Marlin installed on ESP32 as printer board they are not for ESP3D but Marlin FW - they are not used for a daugther board like you do in your previous open question

**Comment by kkberg** [comment]
Thank you, that makes sence. I'm confused with all that stuff, need weekend. :)

**Comment by kkberg** [comment]
clarified, thank you

**Comment by kkberg** [comment]
.. you sea:)

**Comment by luc-github** [comment]
NP
FYI : there is a version of Marlin that support ESP3D for esp32 https://github.com/luc-github/Marlin
