### ISSUE TITLE
Can I use esp07 for this firmware?

### ISSUE THREAD

**Issue by sergeyfk05** [luc-github/ESP3D#375]
How I can flash esp3d on esp07?

**Comment by luc-github** [comment]
like any other esp8266 - use generic esp8266 and proper settings

**Comment by sergeyfk05** [comment]
I'm uninstall arduino ide and install it one time more. If installing without package manager — all is OK.

**Comment by luc-github** [comment]
Be sure you install esp8266 core v2.5.2 to work with esp3d 2.1
