### ISSUE TITLE
[BUG] Cannot start after flashing

### ISSUE THREAD

**Issue by huczas** [luc-github/ESP3D#379]
**Describe the bug**
Not starting after flashing

**ESP3D Firmware:**
- ESP core version: [2.5.2]
- Version:[2.1]
- Web UI Version:[ 2.1]  
- Wifi mode: AP 

**Target Firmware:**
 - Name: Marlin
 - Version 2.0

**Board used (please complete the following information):**
 - MCU: ESP8266 
 - Name:esp01
 - Flash size: 1M

**Additional context**
I'm trying to flash 2.1v branch, with 2.5.2 version of Arduino board esp8266, 
My esp01 have only 1mb, and when I set 1M (128k SPIFFS) there is always not enough space for  UI html file. If I'm trying to change SPIFFS to have more space esp01 is not starting. 
I don't know if I'm doing something wrong or my setup is bad, can you put binary file that should be ready to upload with UI file inside?

**Comment by luc-github** [comment]
yes web UI and FW start to grow with the time  - I think I need to do mono language version of webUI to decrease size

what space did you tried that is not working ?

**Comment by huczas** [comment]
Any above SPIFFS 128 didn’t start. 
Premade UI with proper languages are good choice 👍 nice to try that approach.

**Comment by luc-github** [comment]
this is weird people having 1M flash where using 194kb SPIFFS 
but you may need to use the erase all flash setting

**Comment by huczas** [comment]
Ok, I will try that at the evening. I’m also afraid that I have something wrong with libraries that I have. 
Is there any chance that you can build binary file for me?

**Comment by luc-github** [comment]
you cannot be wrong if you use the libraries present in repository libraries directory. need to copy them as explained in read me to be sure you use the one I tested and certified working

**Comment by huczas** [comment]
Ok, so I've ended with 1M (160k SPIFFS) - that I can confirm is working with esp8266 library v2.5.2.
I've disabled notifications to get little more space.
```
//NOTIFICATION_FEATURE : allow to push notifications
//#define NOTIFICATION_FEATURE
```

New question is: if in the future I want to upgrade firmware using web - how to prepare file? or are you going to prepare next version ready to upload?

**Comment by luc-github** [comment]
in arduino just generate  binary, it will be in sketch folder
![image](https://user-images.githubusercontent.com/8822552/66025295-b0d96300-e528-11e9-89f4-60bd1d44fb2c.png)

Due to all possible configurations I cannot build all binary

**Comment by huczas** [comment]
ok, so there is not any specific naming of that binary - all is clear to me now. Thanks for your work! I will buy you a coffee 😉
