### ISSUE TITLE
Can I buy this ESP?

### ISSUE THREAD

**Issue by goldjunge91** [luc-github/ESP3D#384]
hi is this the right ESP?
 [ESP-ebay](https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.de%2Fulk%2Fitm%2F252718027546)
which ESP is the best for this project? I find this idea so cool that I want to equip all my printers with it
Excuse me.  open for the issues which is not a real issue.

**Comment by luc-github** [comment]
Yes it has 4MB flash so it will fit all configurations

**Comment by goldjunge91** [comment]
Thank you for your help directly on 2 days: D
