### ISSUE TITLE
[BUG] TCP Serial reads corrupted data after a while

### ISSUE THREAD

**Issue by TheCrypt0** [luc-github/ESP3D#387]
**Describe the bug**
While printing using the serial TCP interface everything works fine for a while (usually ~1 hour), after that the TCP serial stream starts to read garbage which hangs Simplify3D and ruins the print. 

**NOTE**: After noticing the issue (a few times) I opened the web interface which always worked fine and the commands sent there were executed successfully by the printer (even with the TCP Serial still active and reading garbage). The memory usage was normal: ~40KB free. This might be useful to troubleshoot the issue.

The problem has been observed with both 115200 and 250000 baud.

**To Reproduce**
1. Connect to ESP3D using [COM2TCP](http://www.astrogeeks.com/AstroGeeks/COM2TCP/index.html) (the issue happens with other TCP serial software too).
2. Start printing via TCP Serial.
3. The issue should happen after ~1 hour.
4. See the following Simplify3D output. You can clearly see where the issue arises.

<details>
  <summary>[SPOILER] Simplify3D Verbose Output</summary>

```
SENT: G1 X116.332 Y86.814 E0.3149
SENT: G1 X116.133 Y86.942 E0.3231
READ: ok
SENT: G1 X115.779 Y87.226 E0.3386
READ: ok
SENT: G1 X115.610 Y87.392 E0.3467
READ: ok
SENT: G1 X115.321 Y87.741 E0.3622
READ: ok
SENT: G1 X115.188 Y87.938 E0.3703
READ: ok
SENT: M105
SENT: G1 X114.975 Y88.338 E0.3859
READ: ok
SENT: G1 X114.886 Y88.555 E0.3939
READ: ok
READ: :200.00 /ok
SENT: G1 X114.813 Y88.777 E0.4019
READ: .00ok
SENT: G1 X114.714 Y89.219 E0.4174
READ: ok
SENT: G1 X114.686 Y89.455 E0.4255
READ: o7 ok
SENT: G1 X114.678 Y89.908 E0.4410
READ: ok0ok
SENT: G1 X114.698 Y90.141 E0.4490
READ: 74
READ: ok:ok
SENT: G1 X114.733 Y90.372 E0.4570
READ: ok
SENT: G1 X114.847 Y90.811 E0.4725
READ: ok
SENT: G1 X114.929 Y91.034 E0.4807
READ: ok
SENT: G1 X115.131 Y91.444 E0.4963
READ: ok
SENT: G1 X115.385 Y91.823 E0.5119
READ: ok
SENT: G1 X115.537 Y92.006 E0.5201
READ: ok
SENT: G1 X115.863 Y92.326 E0.5357
READ: ok
SENT: G1 X116.229 Y92.600 E0.5513
READ: ok
SENT: G1 X116.429 Y92.720 E0.5593
READ: ok
SENT: G1 X116.637 Y92.827 E0.5674
READ: ok
SENT: G1 X117.060 Y92.991 E0.5829
READ: ok
SENT: G1 X117.289 Y93.055 E0.5910
READ: ok
SENT: G1 X117.735 Y93.131 E0.6065
READ: ok
SENT: G1 X117.972 Y93.147 E0.6146
READ: ok
SENT: G1 X118.429 Y93.132 E0.6303
READ: ok
SENT: G1 X118.879 Y93.055 E0.6459
READ: ok
SENT: G1 X119.108 Y92.991 E0.6540
READ: ok
SENT: G1 X119.530 Y92.827 E0.6695
READ: ok
SENT: G1 X119.739 Y92.720 E0.6775
READ: ok
SENT: G1 X119.939 Y92.600 E0.6856
READ: ok
SENT: G1 X120.305 Y92.326 E0.7012
READ: ok
SENT: G1 X120.631 Y92.006 E0.7168
READ: ok
SENT: G1 X120.780 Y91.826 E0.7248
READ: ok
SENT: G1 X120.917 Y91.636 E0.7328
READ: ok
SENT: G1 X124.541 Y90.455 F4800
SENT: G92 E0
READ: ok
READ: ok
SENT: G1 X124.860 Y90.635 E0.0106 F2400
READ: ok
SENT: G1 X125.005 Y90.717 E0.0149
READ: ok T:200.07X:200.92 B:50.40 /:0.00 @:7.0B@:0
SENT: G1 X125.150 Y90.799 E0.0186
READ: ot
READ: ok
SENT: G1 X125.295 Y90.881 E0.0218
READ: ok
SENT: G1 X125.440 Y90.962 E0.0247
READ: ok:ok
SENT: G1 X125.585 Y91.044 E0.0275
READ: 0 Z:k
READ: o0
READ: ok
SENT: G1 X125.730 Y91.126 E0.0304
READ: ok
SENT: G1 X126.049 Y91.306 E0.0366
READ: ok
SENT: G1 X126.628 Y91.623 F4800
SENT: G92 E0
READ: ok
READ: ok
SENT: G1 X126.815 Y91.728 E0.0107 F2400
READ: ok
SENT: G1 X126.889 Y91.769 E0.0149
READ: ok
SENT: G1 X127.037 Y91.852 E0.0227
READ: ok
SENT: G1 X127.184 Y91.934 E0.0300
READ: ok
SENT: G1 X127.331 Y92.017 E0.0366
READ: ok
SENT: G1 X127.404 Y92.060 E0.0397
READ: ok
SENT: G1 X127.476 Y92.106 E0.0427
READ: o6.ok
SENT: G1 X127.548 Y92.152 E0.0454
READ: Yk
READ: ok
SENT: G1 X127.616 Y92.208 E0.0479
READ: o Z:5.ok
SENT: G1 X127.682 Y92.267 E0.0500
READ: o:0.00 Count X
READ: ok
SENT: G1 X127.748 Y92.328 E0.0517
READ: okYok
SENT: G1 X127.942 Y92.548 E0.0596
READ: 59 ok
SENT: G1 X127.867 Y92.565 F4800
SENT: G92 E0
READ: ok0
READ: k
READ: ok
SENT: G1 X127.855 Y92.633 E0.0012 F2400
READ: ok
SENT: G1 X127.844 Y92.696 E0.0023
READ: ok
SENT: G1 X127.826 Y92.766 E0.0035
READ: ok
SENT: G1 X127.767 Y92.990 E0.0075
READ: ok
SENT: G1 X127.709 Y93.213 E0.0117
READ: ok
SENT: G1 X127.690 Y93.285 E0.0133
READ: ok
SENT: G1 X127.669 Y93.360 E0.0151
READ: ok
SENT: G1 X127.602 Y93.592 E0.0214
READ: ok
SENT: G1 X127.558 Y93.748 E0.0261
READ: ok
SENT: G1 X127.536 Y93.821 E0.0285
READ: X:122.74 YX:4.3.8Z:5:92.5:0.:0 C0 nt .07907 Yt 302 Z42327
READ: ok
SENT: G1 X127.500 Y93.891 E0.0312
READ: ok2320
SENT: G1 X127.452 Y93.962 E0.0344
READ: k
Total build time: 21.57 minutes
SENT: M105
READ: X:117.48 Y:85.53 Z:5.80 E:0.00 Count X:77:200.00 /2Z:200 
READ: ok
READ: o3
READ: ok5ok
READ: ok
READ: o74ok
READ: o0
READ: ok
SENT: M105
READ: ok
READ: 00.1:117.5.00:85594 0 5.80 E:0.00 B@:0
SENT: M105
READ:  X:7:200.183820Z:2020
READ: ok
SENT: G91
SENT: G1 Z10.000 F6000
SENT: G90
READ: 21 /50.00T:199.9@ /200.00 Bk
SENT: M105
READ: 0.03:200.07 /200 B@:0
READ: ok
READ: 2k
READ: o50.0
READ: ok
READ: o1 B@:0
READ: 
SENT: M105
READ: ok
READ: :k
READ: o.14 
READ: ok
READ: .00ok
READ: ok
READ: o6 /5014.58 71 B@:0
SENT: M105
READ: Z:5.80 0:0. /2Cou0t X:9995  :74.3 Z:232 B@k
READ: ok
SENT: M105
READ: ok:ok
READ: .0
READ: ok200.00
READ: ok
READ: 9.87 /ok
READ: 0k
READ: ok7ok
READ: @:0
READ: k
SENT: G91
SENT: G1 Z10.000 F6000
SENT: G90
READ: ok
READ: okkok
SENT: G91
SENT: G1 Z10.000 F6000
SENT: G90
READ: ok
READ: ok
READ: ok
SENT: M105
READ: ok:200.0
READ: ok200.00
READ: ok
READ: o.
READ: ok/50.00
READ: ok
READ: ok
SENT: M104 S0 T0
SENT: M140 S0
SENT: M105
READ: @:127200.00 /200:20 B:0 .95 /50.09 @:75 B@00
READ: ok Bk
READ: o27ok
SENT: M106 S254
SENT: M106 S252
READ: okk
READ: k
SENT: M106 S251
SENT: M106 S250
SENT: M106 S248
SENT: M106 S247
READ: okkok
SENT: M106 S246
READ: ok
SENT: M106 S244
READ: ok
SENT: M106 S242
READ: okkok
SENT: M106 S240
READ: 
READ: k
READ: ok
SENT: M106 S237
READ: ok
SENT: M106 S236
READ: ok
SENT: M106 S234
READ: ok
SENT: M106 S235
READ: ok
SENT: M106 S237
READ: ok
SENT: M106 S240
READ: ok
SENT: M106 S243
READ: ok
SENT: M106 S245
READ: ok
SENT: M106 S247
READ: ok
SENT: M106 S248
READ: ok
SENT: M106 S250
READ: ok
SENT: M106 S251
READ: ok
SENT: M106 S252
READ: ok
SENT: M105
READ: ok:ok
READ: .8
READ: ok0.00ok
READ: 49.90 /0.0k
READ: ok
READ: ok@:127
READ: 
SENT: M106 S253
READ: ok
SENT: M106 S254
SENT: M106 S255
READ: ok
READ: k
READ: 
SENT: M105
READ: ok
READ: ok98k
READ: o /0.00k
READ: ok
READ: o1
READ: ok
SENT: M105
READ: ok0ok T:200.00 /200970 B /9.90 /50000  :75 B@:127
READ: o:0ok
SENT: M105
READ: oT:ok
READ: .4
READ: ok0.0
READ: ok
READ: ok
READ: ok
READ: o0
READ: ok
READ: ok
READ:  k
READ: o0
READ: ok
SENT: M105
READ: o:
READ: ok.ok
READ: /0.ok
READ: ok4ok
READ: ok
READ: ok
READ: 0k
READ: o0 B@:0k
SENT: M105
READ: ok
READ: :163.82 /ok
SENT: M105
READ: 0k T:200.070/200.00 B@:0.17 /:1600 4 /4 B@:1278ok
READ:  k
READ: o00ok
READ: ok
READ: @:
READ: ok
SENT: M105
READ: ok:ok
READ: .2
READ: ok0.00 B
READ: ok.83
READ: ok.00
READ: ok
READ: ok
READ: ok
READ: ok
SENT: M105
READ: ok
READ: ok
READ: o6 /0.00
READ: ok4ok
READ: 8k
READ: o.00k
READ: ok
READ: B@
READ: ok
SENT: M105
READ: okTok
READ: 3k
READ: o /0k
READ: ok T:2007 /0.200.00 B::0
SENT: M105
READ: 34 /:1.0073:72.B@:0
READ: ok
READ: 42 /0.00
READ: ok0ok
READ: :k
READ: ok
SENT: M105
READ: o:1ok
READ: 20 /0.00
READ: ok
READ: 8.34k
READ: o.00k
READ: ok ok
READ: 0
READ: 
SENT: M105
READ: ok
READ: :1
READ: X:85 /0.0Y:88.89 Z 5.80 E:0.00@:0
SENT: M105
READ: nt X:1439 Y:8086 Z:2320
READ: o /0.00k
READ: ok
SENT: M105
READ: B@:02.26 Y:94.85 /:5.80 E:0.00 /ount X:7 B4 Y
SENT: M105
READ: 8804:Z:2.91
READ: ok.ok
READ: ok
READ: 8.
READ: X:/22.26 Y: B@:0
SENT: M105
SENT: M105
READ: Z:5T:1 E:38 / Co0nt X:7991 Y:8026 Z:2@:0
READ: ok
READ: T:14k
SENT: M105
READ: o8 X:100.24 Y.105/0.00:5.8 B@:0.00 C:1nt 9:8006 Y:8905 Z3232.
READ: ok
READ: ok
READ: B@
READ: ok
SENT: M105
READ: ok
READ: :1
SENT: M105
READ: ok63:20.004 /200.0  B:50.41 /50.00 @:7: B@.0
READ: ok0ok
READ: ok
READ: ok
SENT: M105
READ: X3 20.24 Y:1 5.05 Z:5.:1 E:7.00 Co0nt X:859 /0.0091 Z B@:0
READ: ok
SENT: M105
SENT: M105
READ: o:1ok
READ: 33 X:121.18 7:10 /29 Z:5.80 E:0.00 Count X: 942 Y:8644 Z:2300
READ: ok
READ: o0
READ: ok:ok
SENT: M105
READ: ok
READ: o139.06 /0.
READ: ok
READ: ok7.76 /0.00 @:0 B@:
READ: ok
  ```
</details>

**Expected behavior**
The print shouldn't stop and the serial shouldn't spit out corrupted "ok"s.

**Screenshots**
![chrome_2019-11-19_14-13-17](https://user-images.githubusercontent.com/45895254/69149484-e0432f80-0ad6-11ea-8c8f-c8b42664f36f.png)

**ESP3D Firmware:**
- ESP core version: 2.5.2
- Version: 2.1.0.b39
- Web UI Version: [latest i guess](https://github.com/luc-github/ESP3D-WEBUI/tree/660d09fdde2a72b52db191d6adea2e29636a1fcd)
- Wifi mode: STA
- Any change done in FW: [config.h](https://github.com/luc-github/ESP3D/files/3863832/config.txt)

**Target Firmware:**
 - Name: Marlin
 - Version: 1.1.9

**Board used (please complete the following information):**
 - MCU: ESP8266
 - Name: ESP02
 - Flash size: 1M

**Additional context**
Ender 3 Pro running the V1.1.4 Creality Board. 

Marlin configuration updated with increased buffer sizes to handle the increased delay introduced by the TCP communication:
```c++
// The number of linear motions that can be in the plan at any give time.
// THE BLOCK_BUFFER_SIZE NEEDS TO BE A POWER OF 2 (e.g. 8, 16, 32) because shifts and ors are used to do the ring-buffering.
#if ENABLED(SDSUPPORT)
  #define BLOCK_BUFFER_SIZE 64 // SD,LCD,Buttons take more memory, block buffer needs to be smaller
#else
  #define BLOCK_BUFFER_SIZE 64 // maximize block buffer
#endif

// @section serial

// The ASCII buffer for serial input
#define MAX_CMD_SIZE 96
#define BUFSIZE 48
```
---
Edit: typo.

**Comment by luc-github** [comment]
the tcp bridge is just a bridge so there is not much I could do - I suggest you to set `Include line numbers and checksums` in S3D  (FW Configuration / communication) to avoid data transfert corruption.

**Comment by TheCrypt0** [comment]
Thank you @luc-github for taking time to answer.

I'm currently following you suggestion but I hope there's more we can try to do to improve the situation.

The bridge is buffered right? Because it looks like some kind of issue with the ACK by the printer (in ESP3D or possibly in Marlin). As you can see in the S3D output the situation gets worse exponentially ending with a lot of corrupted "ok"s being received. I'm not sure on what is actually going on. 

Printing via USB (115200 or 250000) works fine though.

I suspect that the printer gets the commands successfully but S3D doesn't get the actual "ok" so it waits and hangs the print until a timeout is reached.

**Comment by luc-github** [comment]
no, the bridge is actually not buffered https://github.com/luc-github/ESP3D/blob/2.1/esp3d/espcom.cpp#L45

But one question : do you use the webUI when streaming by telnet ?

**Comment by TheCrypt0** [comment]
The webUI is closed during the print, I noticed that the latency goes up when it's opened (I guess it's normal since it uses CPU time and networking).

Shouldn't the bridge be buffered to prevent packet loss?

**Comment by luc-github** [comment]
it may be buffered at packet level (esp core, lwip) , but not at data level (ESP3D), it is bridged as fast as possible (as soon as received) to avoid delay in tranmission.

Adding the checksum and line numbering will ensure the ok match the line (in theory).
I asked if webui was opened to be sure no communication conflict.
If no communication conflict - there is one bottleneck possible : the buffer you use is may be too big
what size did you defined ?

**Comment by TheCrypt0** [comment]
What buffer are you referring to?

**Comment by luc-github** [comment]
this one 
![image](https://user-images.githubusercontent.com/8822552/69229945-b47f8280-0b86-11ea-8eba-2f009a3cce93.png)

may be try without command buffering at all

**Comment by TheCrypt0** [comment]
Disabling the Serial cache on S3D slows down the print to unacceptable levels because it waits for every single "ok" before sending a new command.

I'm currently trying with new buffer sizes both in Marlin and ESP3D, will update if the issue persists.

---

Update: while I was writing the reply the print stopped with the usual garbage received by S3D. The buffers may have helped a lil bit to delay the arise of the issue.
This time I just closed and reopened the virtual COM via S3D and the communication got back to normal.
This could suggests that the issue might  be related to buffers on the computer running the TCP Serial software itself. Further investigation is needed.

I've now switched software to get the TCP Serial data and started a new print. (Currently testing using com0com with com2tcp, an open source alternative to COM2TCP).

**Comment by luc-github** [comment]
My suggestion was to see if issue come buffering,  but seems you may found some clue of the  root cause which is better

**Comment by TheCrypt0** [comment]
I can confirm that the issue was the Serial TCP emulator (COM2TCP by AstroGeeks).

I've been printing for 24 hours without any issue using [com0com ](http://com0com.sourceforge.net/)with com2tcp (the open source alternative). It's a little bit more complex to setup but I found a pretty handy guide to make it work in less that 10 minutes.

Here's a guide to follow to get the thing set up: http://com0com.sourceforge.net/doc/UsingCom0com.pdf

Thanks @luc-github for the support provided. I'm closing the issue now.

**Comment by luc-github** [comment]
@TheCrypt0 Thank you - that is good thing you shared - may be, would be good to put this in wiki
