### ISSUE TITLE
Headbed

### ISSUE THREAD

**Issue by rieders** [luc-github/ESP3D#389]
Hi
I have recently seen esp3d and flashed an esp with it. So far everything runs with the Marlin firmware. The only problem I still have is that I have no temperature history of Headbed.
I can not control temperature. In the Marlin Firm I set the temperature sensor of the bed and extruder to 1.

I would be glad if you could help me.

greetings
André

**Comment by luc-github** [comment]
did you enabled the bed control in webui preferences ?

**Comment by rieders** [comment]
Thank you for the fast answer.

I did not see that there is still a setup menu.

Now it's working.

Many thanks for the help. A great project.

 

greetings

 

 

Von: Luc <notifications@github.com> 
Gesendet: Freitag, 29. November 2019 10:32
An: luc-github/ESP3D <ESP3D@noreply.github.com>
Cc: A. Rieth <rieders23@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [luc-github/ESP3D] Headbed (#389)

 

did you enabled the bed control in webui preferences ?

**Comment by luc-github** [comment]
great

**Comment by rieders** [comment]
Hi there

I am trying to send files via webgui.
Unfortunately the printer answers "wrong format".
How can I send files to the SD card for printing?

Sincerely yours
André
