### ISSUE TITLE
[BUG] Don´t get serial output

### ISSUE THREAD

**Issue by jtkDvlp** [luc-github/ESP3D#391]
**Describe the bug**
Connecting esp2866 with esp3d to serial terminal like putty I dont get any output nor can input. Sending a command via working esp3d web gui wont also get an output on serial console.

Working with another sketch like "esp2866 TestEspApi" works as expected with serial putty console.

**To Reproduce**
1. Setup esp2866 with esp3d 2.1
2. Turn on the device, open web gui to test if its working
3. Connect via putty to com port
4. send am command like M115 via web gui

**Expected behavior**
Sending a command via web gui should give the same command input to serial console output, but got nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/5053494/70374742-a5befc80-18f6-11ea-9c2c-7b916a04aa4b.png)

![image](https://user-images.githubusercontent.com/5053494/70374733-83c57a00-18f6-11ea-91b5-68136b2bdb99.png)

![image](https://user-images.githubusercontent.com/5053494/70374753-c2f3cb00-18f6-11ea-823e-85a78fe83c94.png)

**ESP3D Firmware:**
- ESP core version: not known what you mean
- Version: 2.1.0.b39
- Web UI Version: 2.1.0.b39
- Wifi mode: STA

Actually I am targeting the following setup, but it dont work, so I tried to check the serial communication of esp3d via console, stepping into the above described bug. Serial communication with repitier works as expected.

**Target Firmware:**
 - Name: Repitier
 - Version 1.0.3

**Board used (please complete the following information):**
 - MCU: ESP2866
 - Name: ??
 - Flash size: 1M

See #390 for previous communication.

**Comment by luc-github** [comment]
what is your esp board?

**Comment by jtkDvlp** [comment]
I use an esp2866 ESP-01 and connect it via UART GPIO0 ESP-01 Adaptater. I also upload the sketches via thes adapter. Working with another sketch with this setup works and outputs serial infos to console.

**Comment by luc-github** [comment]
So you have access to webUI 
can you screenshot the ESP3D settings 
![image](https://user-images.githubusercontent.com/8822552/70375577-824c7f80-18ff-11ea-97aa-6e42931bb041.png)

When you says is working with putty what info do get when you connect ESP +  UART GPIO0 ESP-01 Adaptater to your PC and send `ESP111]` and `[ESP420]` (be sure putty send `\n`) ?

How do you wire the ESP01S board with Ramps ?

**Comment by jtkDvlp** [comment]
ESP Settings:
![image](https://user-images.githubusercontent.com/5053494/70375844-06543680-1903-11ea-9af1-57346eecbda7.png)

I cant send anything it seems connect to does also not work. In this case it is not connected to ramp. But I connect it to aux 1 also tried aux 2 and 3, in each case I dont use arduino usb plug to make sure dont get conflicts.

In the meantime I tried an older version of esp3d "ESP3D-0.9.99". With this version it works, I get output on putty console and connecting to ramp etc. I can load printer settings via web gui. So it seems to be a bug of ESP3d 2.1.

**Comment by luc-github** [comment]
reading the output give a clue :
![image](https://user-images.githubusercontent.com/8822552/70376099-a01ce300-1905-11ea-965a-a3afe69b6c1f.png)

go to ESP3D settings and enable serial - it should help ^_^

**Comment by jtkDvlp** [comment]
Where I have to that?

![image](https://user-images.githubusercontent.com/5053494/70376200-b5ded800-1906-11ea-88e6-017ff184c0b1.png)

![image](https://user-images.githubusercontent.com/5053494/70376208-c42cf400-1906-11ea-96ce-00c94b5a4c69.png)

![image](https://user-images.githubusercontent.com/5053494/70376216-d5760080-1906-11ea-88c6-18afd23429fd.png)

**Comment by luc-github** [comment]
do not change anything in FW  code
this is in WEBUI :
![image](https://user-images.githubusercontent.com/8822552/70376285-998f6b00-1907-11ea-831f-a3d09edbd403.png)

You have old one I guess

**Comment by jtkDvlp** [comment]
Damn, you got it I used UI: 0.9.60LE maybe from old test dont know. Using right version and setting up serial works 👍 

Thank you very much 

ps: what is M117 output message?

**Comment by luc-github** [comment]
message that go to printer lcd - so not necessary when printer does not have lcd ^_^

Ok good - I close issue then
