### ISSUE TITLE
[FEATURE REQUEST]<Enter comprehensive title>

### ISSUE THREAD

**Issue by pipi61** [luc-github/ESP3D#398]
**Is your feature request related to a problem? Please describe.**
Upload to SD slow

**Describe the solution you'd like**
please insert baudrate 1000000 to selectable

I check , if the baud rate set 500000 then printer work. If set to 921600, then serial data communications bad.
I check baud rate errors in next page:
[https://3dprint.wiki/reprap/anet/anet_mainboard_overclocking#crystal_selection_and_replacement](url)
If 16MHz clock, then 250000, 500000, 100000 errors 0%, if 921600 then error 8.5%
Thank You

**Comment by luc-github** [comment]
1 - faster baud rate won't make SD upload faster issue is pinned in top of issues : https://github.com/luc-github/ESP3D/issues/292
2 about faster baud rate you  may get errors : https://github.com/luc-github/ESP3D/issues/350

**Comment by pipi61** [comment]
Thank You
