### ISSUE TITLE
[FEATURE REQUEST]<Connect to printer using USB Shield (MAX3421E)>

### ISSUE THREAD

**Issue by siklosi** [luc-github/ESP3D#400]
**Is your feature request related to a problem? Please describe.**
Soldering to traces on printer board can be tricky.

**Describe the solution you'd like**
Connecting via standard USB cable would be much easier. I'm not sure if it is possible at all just crossed my mind. Something to consider...

**Describe alternatives you've considered**
/

**Additional context**
![image](https://user-images.githubusercontent.com/11267757/71358221-9394bd80-2588-11ea-81cb-dfeb0b6452f1.png)

**Comment by luc-github** [comment]
This is in feature list already : point 23 https://github.com/luc-github/ESP3D/issues/239
and current status is : https://github.com/luc-github/ESP3D/issues/239#issuecomment-511144012
It is not so easy to implemented to cover all printer boards
