### ISSUE TITLE
[FEATURE REQUEST]<scrollbars M165 Ax By Cz>

### ISSUE THREAD

**Issue by MarcFerrer** [luc-github/ESP3D#448]
Aadd scrollbars to set real-time filament mix%.

It is also possible to lock one bar to change% of one bar and the other to change automatically.

This is the option you can make in the menu of marlin mixier-> mix.

It serves as a diamond extruder.

thanks

**Comment by luc-github** [comment]
You need to give more explaination, can you elaborate what is the request ? 
what are these control and what are the expected behavior ? - I am not familiar filament mixer

**Comment by MarcFerrer** [comment]
I made a video with the printer working

[https://youtu.be/aRNvUFeQ9tg](url)

The 3 motors can be run at the same time to mix the filaments. Just say % of each color with the M165 command.

For example:
filament / Engine 1: M165 A1 B0 C0
filament / Engine 2: M165 A0 B1 C0

The 3 motors at once: M165 A0.33 B0.33 C0.33;

These changes are made by clicking on the different buttons in the scripts.

it would be nice if the% is could vary, in real time.

For example: color 1 to 20%, color 2 to 20% color 3 to 60%, which would be
M165 A0,2 B0.2 C0.3

To be able to make artistic pieces in terms of colors


I thought one way to do this would be with scroll bars.

And for it to be effective, a color is could be set with a checkbox and when moving the second the third would calculate it automatically until it reaches 100%

I thought one way to do this would be with scroll bars.

The result, a profile of rose (by Sant Jordi in Catalonia ;-)

[https://youtu.be/t4jvDIh400o](url)

**Comment by luc-github** [comment]
so would give something like this ?
![image](https://user-images.githubusercontent.com/8822552/79791704-0d2d9400-834e-11ea-978a-439baa356641.png)

the button will send the GCODE command(s)command according value 0.1 0.3 and 0.6
 * Marlin M165 A0.1 B0.3 C0.6 
 * Repetier :  (for each extruder a command) M163 S0 P0.1 M163 S1 P0.3 M163 S2 P0.6  -
 * Smoothieware: seems not supported 🤔 so need to hide

here only A can be fixed because 3 extruders

if 4 extruders 2 can be fixed, N extruders N-2 can be fixed, the last value is the calculation vs N-2 extruder value

I am correct ?

**Comment by MarcFerrer** [comment]
yes, it is correct and fantastic.

the repiter did not know him.

The option to fix (N-2) extruders also seems correct

**Comment by luc-github** [comment]
you mean instead of A B C label ? put a configurable label ?

**Comment by MarcFerrer** [comment]
that it is possible to put the colors of the filaments

![colors](https://user-images.githubusercontent.com/3359879/79836478-73e39980-83b0-11ea-9eac-25d4f219f9a7.png)

**Comment by luc-github** [comment]
this is special control that is not standard so need to write it I guess, but should be possible

**Comment by MarcFerrer** [comment]
![color2](https://user-images.githubusercontent.com/3359879/79856551-c8950d80-83cc-11ea-8a99-3f47f569246f.png)
changing the background of the div?

**Comment by luc-github** [comment]
yes should be easier

**Comment by luc-github** [comment]
what the step should be  to reach 1 ?
0.1/ 0.05 /0.001 ?

**Comment by MarcFerrer** [comment]
I think 0.05 would be enough

**Comment by luc-github** [comment]
it can also be a preference parameter for mor flexibility

**Comment by MarcFerrer** [comment]
like this?

![colors](https://user-images.githubusercontent.com/3359879/79873461-6e557600-83e7-11ea-9920-1ff271c7d454.png)

**Comment by luc-github** [comment]
yes can be also 
and color will be defined in preferences 
![image](https://user-images.githubusercontent.com/8822552/79875770-664b0580-83ea-11ea-8b0d-fc2769447d87.png)

**Comment by MarcFerrer** [comment]
There is one thing we can keep in mind.

A printer can have 3 extruders or it can have 1 extruder with 3 filament inputs for mixing.

I say this because in preferences it would not be correct to set the number of extruders to 3

Power would be fine to define a new panel named mixer. (with Marlin you can still do more things like virtual tools) where to specify the filaments and colors

**Comment by MarcFerrer** [comment]
I may think about:

A printer can have 3 extruders or it can have 1 extruder and 3 filament inputs for mixing.

He says this because in preferences it would not be correct to set the number of extruders to 3

It may be okay to define a new panel (Mixer) (with Marlin you can do more like vital tools) where you can define the number of filaments, colors, etc.,

**Comment by luc-github** [comment]
you double posted I think

the check box` Mixer extruders`do the trick - if checked it will make controls to appear or not in UI and preferences
Number of extruders is still the same but temperature control is then unique

**Comment by MarcFerrer** [comment]
if it is correct. But I was saying it is not to be confused with other possible configurations (which I do not have)

Examples:
4 different extruders (no mixer)

https://www.youtube.com/watch?v=bn4gWYOzHxQ

The post of kina500 I think it refers to this configuration: (but of 5 inputs, it does not mix)

![Captura de Pantalla 2020-04-21 a les 17 13 30](https://user-images.githubusercontent.com/3359879/79883043-ba0e1c80-83f3-11ea-845d-1a798770d3c4.png)

**Comment by MarcFerrer** [comment]
yes but we have to consider one thing with Marlin:

filament splitter (no color control):  only GCODE T0...
[https://marlinfw.org/docs/gcode/T001-T002.html](https://marlinfw.org/docs/gcode/T001-T002.html)

filament mixer (which display color control) 
can go with M165
[https://marlinfw.org/docs/gcode/M165.html](https://marlinfw.org/docs/gcode/M165.html)

and here T0 ... are used by virtual tools
https://marlinfw.org/docs/gcode/M166.html
(I need to investigate more)

**Comment by MarcFerrer** [comment]
A virtual tool saves a color combination.

for example:
M163 S0 P0.6 ; first component at 0.6. (in the Marlin menu of the Mixer says components)
M163 S1 P0.2 ; second secont at 0.6
M163 S0 P0.2 ; third component at 0.6
M164 S0          ;save to the virtual tool 0 the mixture (T0)

M163 S0 P0.33 ; first component at 0.6. (in the Marlin menu of the Mixer says components)
M163 S1 P0.33 ; second secont at 0.6
M163 S0 P0.33 ; third component at 0.6
M164 S1            ;save to the virtual tool 1 the mixture (T1)

to activate a tool of these 2 defined

M166 T
T1 ; activem la tool 1

(we would get the same color result with  M165 A0.33 B0.33 C0.33)

but since we've defined virtual tools, Marlin gives us more options by working with them using the M166 gcode
[https://marlinfw.org/docs/gcode/M166.html](https://marlinfw.org/docs/gcode/M166.html)

(Marlin uses S0 sometimes as A.. and sometimes as T0...)

**Comment by luc-github** [comment]
@MarcFerrer I have moved  feature request to webUI
