### ISSUE TITLE
[Question]Is it compatible with Ender 3 V2

### ISSUE THREAD

**Issue by sebastien247** [luc-github/ESP3D#533]
Hi,

ESP3D is compatible with Ender 3 V2? If yes, where are the RX and TX pins on the board?

Thanks

**Comment by luc-github** [comment]
what ender 3 v2 board looks like ?

**Comment by sebastien247** [comment]
It is written Creality v4.2.2 on the board

**Comment by luc-github** [comment]
it does not look like the wiki one https://github.com/luc-github/ESP3D/wiki/Creality-Ender-4
And I do not have any - I pinned some tags if anyone has answer

**Comment by luc-github** [comment]
@sebastien247 do you succeed ?
it seems according https://github.com/MarlinFirmware/Marlin/issues/19944#issuecomment-740023411 it is possible
