### ISSUE TITLE
Control Printer EEPROM settings

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP3D#62]
EEPROM is now arround 2K which with description give a 4K of data
Having a JSON file which would be an image of EEPROM on SPIFFS could be a solution to avoid to use too much memory and fast exchange, initialized by doing a first sync a start, then doing manual sync or just focus on changes, will limit the memory usage and activity

**Comment by luc-github** [comment]
another way would be to use json file describing the EEPROM mapping type / position / meaning so it could save computation and match every printer 
so when displaying, page will query setting by setting to display the EEPROM values, and so give the ability to modify any value.
this would avoid to transfer a file too big but 
need to check if there is an command to get EEPROM specific value instead of full EEPROM on 
repetier and marlin

**Comment by luc-github** [comment]
Note for implementaton smoothieware does not use EEPROM but rely on configuration file on SD

**Comment by luc-github** [comment]
Ok now the web command catch the answer of the command - it should be easy to grab the EEPROM content without overloading the ESP at all

**Comment by luc-github** [comment]
Yes a little javascript should be able to handle grabing EEPROM content and set value
here result with M205 in pipe
![image](https://cloud.githubusercontent.com/assets/8822552/20219187/7c5e2d44-a828-11e6-95b6-749047a9c77b.png)

**Comment by luc-github** [comment]
Repetier EEPROM editor is done : https://github.com/luc-github/FW-config-editor

Smoothie configuration file should follow soon 

for marlin I need to see what can be done - seems not really using EEPROM

**Comment by luc-github** [comment]
Smoothieware is now implemented so I close issue - following can be done on https://github.com/luc-github/FW-config-editor

**Comment by angelo-reprap** [comment]
Perfect Work and Thank you luc.

**Comment by luc-github** [comment]
Thank you 
 I will release a new version soon integrated directly in (https://github.com/luc-github/smoothieware-webui-for-ESP3D) with a lot of bug fixes and improvement - current version has issues with Internet explorer - I am adding more feature and will do a release next week I hope

**Comment by luc-github** [comment]
yes - it is orginally for smoothiware but my version support smoothieware/repetier and marlin - that is why I am little bit slow - test on all FW and several browsers take time
