### ISSUE TITLE
[FEATURE REQUEST]<Heltec-rastreador inalámbrico WiFi/LoRa/BLE/GNSS(L5)>

### ISSUE THREAD

**Issue by vicen1206** [luc-github/ESP3D#991]
Hola, compre esta placa de desarrollo: Heltec-rastreador inalámbrico WiFi/LoRa/BLE/GNSS(L5),
Me gustaria usarla como un Traker de lora , como los TTgo, pero esta tiene pantalla TFT y el programa solo tiene para pantalla OLED, cabe la posibilidad de habilita la TFT y como se aria si fuera posibre, adjunto manual de la placa,
[Wireless Tracker 1.1.pdf](https://github.com/luc-github/ESP3D/files/13887047/Wireless.Tracker.1.1.pdf)
Gracias de ante mano

**Comment by luc-github** [comment]
esp3d already support esp32s3 and some oled
what is your issue using esp3d on it?

**Comment by vicen1206** [comment]
Gracias por contestar tan rápido, hago la programación con el Visual studio y todo perfecto pero no se visualiza nada en la pantalla,

**Comment by luc-github** [comment]
do you have heltec sample code to check hardware is ok?
also sample code would allow to check your pinout is correct

**Comment by vicen1206** [comment]
si, una de aqui, https://flasher.meshtastic.org/ y funciona a la perfeccion

**Comment by vicen1206** [comment]
Mi intención es usarlo con esta programación
[LoRa_APRS_Tracker-main (1).zip](https://github.com/luc-github/ESP3D/files/13889527/LoRa_APRS_Tracker-main.1.zip)

**Comment by luc-github** [comment]
what screen this board is using?

**Comment by vicen1206** [comment]
es una TFT 0.96" 80x160

**Comment by luc-github** [comment]
what chipset?

**Comment by vicen1206** [comment]
[Wireless Tracker 1.1.pdf](https://github.com/luc-github/ESP3D/files/13891126/Wireless.Tracker.1.1.pdf)
![1704908509292](https://github.com/luc-github/ESP3D/assets/155820283/48c5efd6-3d3e-4985-8c99-354b0f04e11f)
![1704908509302](https://github.com/luc-github/ESP3D/assets/155820283/e496838e-8722-4332-90d9-b79ea74fadf6)

**Comment by luc-github** [comment]
yes but I do not see what drivers this screen need in the doc neither what chipset it use

**Comment by vicen1206** [comment]
no se si esto te sirve 
![1704909172874](https://github.com/luc-github/ESP3D/assets/155820283/69a8e585-328e-4927-b9ee-0baa175be315)

**Comment by vicen1206** [comment]
![1704909328245](https://github.com/luc-github/ESP3D/assets/155820283/e713e1cb-f120-4041-adfa-f763544ff6ed)

**Comment by luc-github** [comment]
it looks like from the github it is st7735

so you need to do change accordingly as this chip is supported by TFT_eSPI lib

I do not have this board but look like overkill if you do not use its gps / lora features as esp3d does not support them

**Comment by vicen1206** [comment]
Entonces puedo usarla con lora? si es asi , como lo hago?  aun que sea de I-Gate en vez de Traker

**Comment by luc-github** [comment]
esp3d is for 3D printer and cnc it does not make sense to support lora or gps

I do not understand your question

**Comment by vicen1206** [comment]
entonces no puedo instalar LoRa_APRS_Tracker-main o LoRa_APRS_iGate-master a esta placa?

**Comment by luc-github** [comment]
this is not lora github why asking that?

**Comment by vicen1206** [comment]
ok, muchas gracias por todo

**Comment by luc-github** [comment]
I close issue then
